### ISSUE TITLE
On IIS websocket connection throws error

### ISSUE THREAD

**Issue by ideplo** [aspnet/SignalR#1001]
Testing via VS2017 on Win10 using IIS express or Kestrel everything runs fine. When deployed to IIS neither signalR or Websockets work. Below is the error:

signalr-client-1.0.0-alpha1-final.js:65 Uncaught Error: Message is incomplete.
    at Object.parse (signalr-client-1.0.0-alpha1-final.js:65)
    at JsonHubProtocol.parseMessages (signalr-client-1.0.0-alpha1-final.js:552)
    at HubConnection.onDataReceived (signalr-client-1.0.0-alpha1-final.js:375)
    at WebSocketTransport.6.exports.constructor.options.connection.onDataReceived.data [as onDataReceived] (signalr-client-1.0.0-alpha1-final.js:364)
    at WebSocket.11.exports.connect.webSocket.onmessage (signalr-client-1.0.0-alpha1-final.js:677)
parse @ signalr-client-1.0.0-alpha1-final.js:65
parseMessages @ signalr-client-1.0.0-alpha1-final.js:552
onDataReceived @ signalr-client-1.0.0-alpha1-final.js:375
6.exports.constructor.options.connection.onDataReceived.data @ signalr-client-1.0.0-alpha1-final.js:364
11.exports.connect.webSocket.onmessage @ signalr-client-1.0.0-alpha1-final.js:677

I have the AspNetCoreModule installed as well.

Thanks in advance for your help,
MHoward

**Comment by moozzyk** [comment]
It looks like a corrupted message. Here are things to do:
- make sure that both the client and the server are running the same version (e.g. alpha1) - if your client is using the alpha1 version but the server is using a different version things may not work because of the changes to the protocol
- check messages the server sends to the client - are they valid json? (note you should see a separator (0x1e character) after each message)
- try a different transport to see if this is a general issue or transport related
- post a repro application

**Comment by ideplo** [comment]
Ok I double check that. The weird thing is I Have a wpf client and a Console client and things work perfectly but only in debug mode via VS....
