### ISSUE TITLE
question - how to handle exceptions during OnDeserialized

### ISSUE THREAD

**Issue by Apollo3zehn** [aspnet/SignalR#1026]
I am using the [OnDeserialized ](https://msdn.microsoft.com/de-de/library/system.runtime.serialization.ondeserializedattribute(v=vs.110).aspx)callback that is called by the Json.NET deserializer after deserialization to validate the transmitted data (models). When the validation fails, an exception is thrown. 

I was using the old SignalR version before. There I got the exception properly forwarded to my javascript client. But now this closes the connection with error "Websocket closed with status code: 1011 ()". My C# application throws `TargetInvocationException` that wraps my own exception. 

Do you have an idea how to avoid closing the connection? Am I misusing SignalR somehow?

**Comment by moozzyk** [comment]
What do you want to do if the validation fails? Since SignalR supports now not only JSON how would you ensure the models are valid if the client is using MessagePack?

**Comment by Apollo3zehn** [comment]
I have no experience with MessagePack. Is the difference that MessagePack ignores the OnDeserialized attribute? Just trying to understand your point.

When the validation fails I would like to catch that error in my JS client like I did before. If that is not supported, I need to call the validation routine within the actual hub method. I just would like to know how it is intended since my approach was working before.

**Comment by moozzyk** [comment]
> I have no experience with MessagePack. Is the difference that MessagePack ignores the OnDeserialized attribute? Just trying to understand your point.

The MessagePack implementation we are using does not check the `OnDeserializedAttribute`. My point is that SignalR now supports custom protocol formats (not only JSON) and the users are free to implement serialization and deserialization of SignalR messages as they see it fit. (This might be a moot point because you control the application, so you decide what protocols to use. This means that could only use JSON (as you probably do right now - this is the default) and never worry about other protocols). 

It seems to me that validating anything when serialization happens is (at least with this version of SignalR)  much too late or too early. 
- too late - if it is possible to validate the model on the client it would be the best not even to send messages to the server (may not be possible if the server has some data needed to validate the model and the data changes dynamically - e.g. based on requests from other clients - and the clients don't necessarily know the latest state)
- too early - throwing at the serialization level bypasses a lot of SignalR stack including code that is responsible for tracking client invocations and returning responses. If that happens the client can hang because it may be `await`ing on a call that would never be completed. At the moment the server is just closing the connection to prevent from this to happen. We are already tracking this [issue](https://github.com/aspnet/SignalR/issues/815) and, when fixed, I believe it would fix your scenario too. However, I think it would be cleaner to validate your payload in the Hub method you are trying to invoke. You could have a `Validate` method you would invoke at the beginning of the hub method. If `Validate` throws the client will get the exception and the connection will not be closed. It will also work regardless of the  protocol used to send messages.

**Comment by Apollo3zehn** [comment]
Thanks for your clarification. Server side validation is mandatory in my scenario but you are right I also need to improve it on client side (once I find the time for it). Therefore I will consider your second point to do validation after deserialization. I think this is feasable.
