### ISSUE TITLE
Datetime object passed as mindate

### ISSUE THREAD

**Issue by Jon-Murray** [aspnet/SignalR#1058]
Hi guys,

  When using messagepack in the javascript implementation and posting a Date object (where the server is expecting a DateTime or DateTime?) the date is always passed as DateTime.MinValue instead of the proper date.

Passing it as a string and manually parsing it again works fine.

Thanks

**Comment by moozzyk** [comment]
Need to check how are things serialized. It's a bit related to #1043 - we need to cover more types and see which one cause problems and how to resolve them.

**Comment by moozzyk** [comment]
Looks like Dates don't work at all at the moment. I looked at how msgpack5 handles Date objects and it does not have any specific code to handle this type when serializing so it checks if there is an extension registered to handle Date and then - since there is no extensions - it falls back to serializing Date objects as if they were regular objects (i.e. as a map). However, since there are no properties the Date object is serialized as map without properties and it appears as min DateTime on the server side. Serialization from the server side does not work as well. Currently MsgPack-Cli will serialize DateTime as an int64 which represents the number of ticks. This however is not useful without further processing. JavaScript object uses Unix Epoch as the starting point and counts miliseconds whereas DateTime ticks represents the number of 100-nanosecond intervals that have elapsed since 12:00:00 midnight, January 1, 0001 (0:00:00 UTC on January 1, 0001. So, to get the actual Date in Javascript  you have to subtract 621355968000000000 from the value that originated on the server and then divide the result by 10000.
Having said that - I noticed some [changes](https://github.com/msgpack/msgpack-cli/commit/8a6432478ad1aa88802a2c3b7ae00313d5c49df5#diff-ab9fc788500a6a9f7352207163c62e5c) in MsgPack-Cli which have not shipped yet, where DateTime is being serialized as an extension type. I think that with these changes it should be possible to write an extension for msgpack5 which could take care of proper DateTime serialization/deserialization.
/cc @yfakariya

**Comment by muratg** [comment]
#1463 should be fixing this.
