### ISSUE TITLE
Question for the team on SignalR Core

### ISSUE THREAD

**Issue by BenHayat** [aspnet/SignalR#1063]
Hi;

If I develop a mobile app using JS, jQuery and PhoneGap, which uses WebKit browser engine for Android and WebView browser engine for iOS, does SignalR Core support these Web engines as part of "Browser Support"? Another words, can I build PhoneGap Mobile client app using SignalR Core client?

Thanks!

**Comment by moozzyk** [comment]
I guess you need to try and if you find something missing you will need to polyfill. For instance, nodejs does not expose many APIs SignalR JS client needs but the client works just fine if they are polyfilled. You can find more details in my [blog post](https://blog.3d-logic.com/2017/10/01/the-signalr-for-asp-net-core-javascript-client-part-2-outside-the-browser/).

**Comment by BenHayat** [comment]
My question wasn't related to a small case for me to try. I was asking if the SignalR Client supports WebKit and WebView Browser engines as part of their browser support. It's an important topic that MSFT should include on their Browser support list. Can SignalR work with PhoneGap implementation of running in browser engine. Since many mobile apps are developed with Phonegap system.
It's something that the team should test on these polyfill browser engines to give a clear statement on the compatibility.

**Comment by moozzyk** [comment]
The client is supposed to be browser agnostic (i.e. it is not using any specific/non-standard browser features) and is not using any non-standard libraries (as opposed to the previous SignalR JS client which depended on jQuery). The client may work with a limited functionality if a feature is missing (e.g. Edge/IE don't support eventSource API so the serverSentEvents transport will not work out-of-the box in these browsers) which can be polyfilled. 
For the JS client we ran our tests on latest versions of Chrome, Safari, Firefox, Edge, IE9/IE10/IE11 and Opera and all applicable (i.e. ones that did not require polyfilling) tests passed (e.g. on IE9 the only longPolling transport and non-binary protocols (JSON) were tested because IE9 does not support webSockets, eventSource and xhr level 2 features).

**Comment by BenHayat** [comment]
Thanks Moozzyk for the detail info. It would be great by beta, the team will run a test against PhoneGap both on Android (using WebKit engine) and iOS (using WebView) and look at how these two benchmark on your list. There are a lot of Hybrid apps using PhoneGap out there.

Thanks again!

**Comment by littleowlnest** [comment]
I was wondering if there was an outcome for this issue?  Was there any discussion regarding its compatibility in PhoneGap?
