### ISSUE TITLE
How to Configure SignalR with Azure Redis Backplane

### ISSUE THREAD

**Issue by adeelbinkhalid** [aspnet/SignalR#1096]
Hi there,

this might not be the right forum but i dont know here else to ask this quesiton. I am using asp.net core with SignalR alpha 2. my web app is hosted in Azure and trying to use Azure Redis Cache for backplane. So far i have only found the following:

services.AddSignalR().AddRedis();

No idea how to add the Azure Redis cache connection string.  without the connection string i get (on console window)
info: Microsoft.AspNetCore.SignalR.Redis.RedisHubLifetimeManager[0]
      Connecting to redis endpoints:

And exception on route.MapHub<myhub>("myhub");

StackExchange.Redis.RedisConnectionException: 'It was not possible to connect to the redis server(s); to create a disconnected multiplexer, disable AbortOnConnectFail. SocketFailure on PING'

please help :(

**Comment by moozzyk** [comment]
When you call `AddRedis` you can provide an `Action<RedisOption>` which you can use to set the [Factory](https://github.com/aspnet/SignalR/blob/30e7422407760d0d56361f76b73c5930875a03d3/src/Microsoft.AspNetCore.SignalR.Redis/RedisOptions.cs#L19).

**Comment by adeelbinkhalid** [comment]
hi moozzyk,
First of all thanks for replying to my question. I have tried that too.. below is the code:
 
public void ConfigureServices(IServiceCollection services)
        {
           
            services.AddMvc();
            services.AddSignalR()
                    .AddRedis(option => 
                                    {
                                        option.Factory = t => ConnectionMultiplexer.Connect("********.redis.cache.windows.net:1111,password=mypasswprd=,ssl=False,abortConnect=False");
                                    });
        }

and in Congifure function:

  app.UseSignalR(routes =>
            {
                routes.MapHub<XpressHub>("hub");
            });

and the error i am getting is 
![image](https://user-images.githubusercontent.com/33472168/32532982-083817c6-c4a2-11e7-8298-6fcbb0a4dcb2.png)

in the console window it says connecting to redis endpoint:
and it does not say my azure endpoint..
any change you could share a running sample?

thanks again

**Comment by moozzyk** [comment]
What you have should work. I just tried to make sure and was able to run the chat sample with redis on azure. Here my code: 
```C#
            // To use Redis scaleout uncomment .AddRedis and uncomment Redis related lines below for presence
            services.AddSignalR()
                .AddRedis(options => options.Factory = writer =>
                {
                    return ConnectionMultiplexer.Connect("******.redis.cache.windows.net:6380,password=******,ssl=True,abortConnect=False", writer);
                });
```
and I can see keys in my Redis cache on Azure: 

![image](https://user-images.githubusercontent.com/1438884/32580257-48aa7942-c499-11e7-8d05-a76c1eb01089.png)

I noticed that you have `ssl=False` in your query string. I think that by default Redis cache on Azure can only be accessed by SSL, so you won't be able to connect with ssl=False. Try to connect using SSL. If you still cannot connect you can pass a `TextWriter` to the `ConnectionMultiplexer.Connect` method which will be used by StackExchange to write logs which should help you figure out the problem. 

I think this problem is external to SignalR so I am closing the issue.
