### ISSUE TITLE
Need a .net client for SignalR Core.

### ISSUE THREAD

**Issue by JinsPeter** [aspnet/SignalR#1097]
I work on a UWP project developed in JS, and has local DB and background functionalities in Windows Runtime communicating with .NET Core Web server. I used ASP.NETCore SignalR alpha 2 version with JS client. which is working pretty good. 
I think .NET Client library that can communicate to .NET Standard SignalR Server would be a good feature I could make use of in the UWP project. upgrading to UWPCore makes a dependency of having many client upgrade their Windows, which I don't know when they would do.
I wonder if there is anything of the sort being developed.

**Comment by prom3theu5** [comment]
It already has buddy

Check out the samples. Specifically [This, for websockets](https://github.com/aspnet/SignalR/blob/dev/samples/WebSocketSample/Program.cs) & [This, for a client sample](https://github.com/aspnet/SignalR/blob/dev/samples/ClientSample/RawSample.cs) :)

**Comment by moozzyk** [comment]
As noted by @prom3theu5 SignalR client [targets netstandard2.0](https://github.com/aspnet/SignalR/blob/dev/src/Microsoft.AspNetCore.SignalR.Client/Microsoft.AspNetCore.SignalR.Client.csproj#L5). We have not yet thoroughly tested the client on UWP yet since UWP started supporting netstandard 2.0 only recently. This is being tracked here as https://github.com/aspnet/SignalR/issues/423
