### ISSUE TITLE
SignalRFC?

### ISSUE THREAD

**Issue by RandyBuchholz** [aspnet/SignalR#1100]
I playing with SignalR and Razor Pages, and have a hub per page. In some cases I use SignalR like the chat examples, where I am broadcasting. In other cases I do 1-1 communication with the browser, in a real time dashboard. I have cases where I want to do remote function calls (in both directions). I don't have a real good handle on all of this yet, but from what I see, SignalR is doing one-way/atomic exchanges over the bi-directional connection. By that I mean, that if I send a request for information to the browser and the browser sends a back the information, SignalR doesn't have a way to tie those together as two sides of a remote function call. Is that correct?

I don't know if it belongs in SignalR, but it would be nice to be able to do broadcast and RFC's using a single technology component and connection.

extra -
I've been unable to implement this myself (though probably due to my lack of understanding). When trying to wrap a send and receive (execute a function on the browser and get the results async) into a single async function I ether hold up the browser while the function is executing, or dispose the hub mid transaction. Is this something simple to implement? (hint: example), or is this something outside of the SignalR design scope?

**Comment by moozzyk** [comment]
Client side results are currently not supported.

Hubs are transient - each time a hub method is invoked a hub is created and when the invocation is completed the hub will be disposed. You would have to store some state on the server side to track client side invocations. You would assign an Id to each invocation and the client would have to send the Id back to you. You need to handle cases where the client never returns a value (e.g. due to connectivity issues etc.) - maybe you could use a timeout. As you can probably see this gets quite tricky with broadcasts where you invoke a method on multiple clients so you need to handle multiple results (and multiple failures).

**Comment by moozzyk** [comment]
Forgot to include. Here is the link to the issue that tracks clients side results: https://github.com/aspnet/SignalR/issues/335
