### ISSUE TITLE
Authorization in Websockets javascript client

### ISSUE THREAD

**Issue by claylaut** [aspnet/SignalR#1110]
Hi, 
I m trying to pass `Authorization token` from the javascript client, but I cannot find a way/sample how to pass it.

Can you please help me?

I've noticed that  in the old signalr api there was `.qs` method on the connection but in the new api it doesn't exist.

**Comment by anurse** [comment]
You can specify a query string in the URL you provide to `HubConnection` (`http://localhost:5000/hubs?token=[token]`). We don't provide a helper for it but it's easy to concat yourself. Unfortunately, the JavaScript client doesn't support `Authorization` headers because of limitations in Browser WebSocket APIs.

**Comment by claylaut** [comment]
@anurse thanks a lot this worked fine.
