### ISSUE TITLE
Error: Streaming methods must be invoked using HubConnection.stream

### ISSUE THREAD

**Issue by celloudiallo** [aspnet/SignalR#1137]
In my Hub, I have an async function that query a cosmos db for data to be return to the client. the result is an IEnumerable of objects.

`public async Task Get()`
        `{`
            `   var result = await _service.Get();`
           `    await Clients.Client(Context.ConnectionId).InvokeAsync("Get", result);`
        `}`

Invoking this method on the js client as follow throws the error as per the title.
`connection.invoke('get');`

Streaming it like the error mentioned works fine.
`connection.stream("get").subscribe({})`

I am not writing a stream, only an async method. I would like to understand why the framework interprets it as a stream and is there an alternative way of achieving what I want without streaming the result?

**Comment by BrennanConroy** [comment]
What version are you using? Client and Server

**Comment by moozzyk** [comment]
You seem to be using a non-latest post alpha-2 bits. The code that was throwing this exception is now gone.

**Comment by celloudiallo** [comment]
server: `<PackageReference Include="Microsoft.AspNetCore.SignalR" Version="1.0.0-alpha2-final" />`
client: `"@aspnet/signalr-client": "^1.0.0-alpha2-final",`

**Comment by moozzyk** [comment]
OK. Let's step back a little bit and look at this from a different angle. You are trying to invoke a client  side method with `IEnumerable` as an argument (btw. I think you may want to consider just returning the value from your hub method instead of calling the client side method). Does the result contain all the items? If yes, who is supposed to enumerate them (btw. you can likely do that by just calling `.ToArray()` on the result)? If the result does not contain all the items (i.e. items can be generated/added each time `.MoveNext()` is called) then you actually should use streaming so that the client can receive these results.

**Comment by celloudiallo** [comment]
You are right, returning directly the Array works.
