### ISSUE TITLE
*Advice sought* Multiple "logical clients" within single physical client

### ISSUE THREAD

**Issue by williamBurgeson** [aspnet/SignalR#1167]
Our latest project involves multiple tabs within an angular app, which would not be displayed more than one at a time but would each display scores for a given lane. It would preferable not to have to completely unload the scores each time we switch between tabs.

I am torn between the following 2 approaches:
1) Create a Hub/HttpConnecton for each lane, register the connection with the lane so that signals to emit an event go through a specific connection, which is received by the front end component dealing with that lane, or
2) Create a single Hub/HttpConnection for the application instance within the browser, which is not tied to a particular lane but accepts messages for all lanes. Have as part of the message the lane number so that the logic for routing the message to the correct place is implemented within user code.

Solution 1 feels more in line with the way SignalR might be "supposed" to work, but I can't help thinking that with more than 10 lanes active at a given time the system could slow down quite considerably.

I think I might have seen it discussed elsewhere but I can't remember if connections are pooled by the system anyway if they are going to the same client.

It would be good to have the thoughts of somebody on the dev team to advise on what any performance concerns may be.

**Comment by anurse** [comment]
You're also likely to hit the browser max connection limits. Most browsers don't permit more than a relatively low number of concurrent connections to each server (usually 6 is a hard maximum, some are even lower). Each SignalR connection consumes one of those (that's true of native WebSockets, and other real-time technologies as well), so by the time you hit 6 tabs you'll be unable to even fetch your app in a 7th tab.

Apps designed to run in multiple browser tabs are generally very tricky to build because of those limits. I'm afraid I don't have any concrete advice in this area as it's not a scenario we've really done any investigation into (and as I said, there's an inherent limit in browsers). You could try something like [SharedWorkers](https://developer.mozilla.org/en-US/docs/Web/API/SharedWorker) to allow you to have a single Web Worker thread shared between multiple browser windows but that would [severely limit](https://www.caniuse.com/#search=SharedWorker) the browsers your app could run on.

**Comment by williamBurgeson** [comment]
That's absolutely fantastic advice: just as well we're on GMT+1 here so the guys over there could look at this question in time for tomorrow!

Based on what you've said I'll go for option 2, and do the triage on the client side.

thanks, and I'll close the issue #signalr multiple connections
