### ISSUE TITLE
Why TryRead and WriteAsync methods now receive a byte[] instead of Message

### ISSUE THREAD

**Issue by vany0114** [aspnet/SignalR#1197]
Hi guys, 

I just would like to get know why now the `TryRead` and `WriteAsync` methods into the `Channel` class receive a byte[] instead of a `Message` object which one had the next properties: Payload, Type and EndOfMessage. My question is how SignalR is managing now the message type and the end of the message.

Thanks a lot!

**Comment by anurse** [comment]
The Channel<byte[]> is used by the Sockets layer, which is a low-level networking abstraction designed to behave like a standard TCP socket. We used to have a low-level framing protocol we added on top of that raw socket which included this data (though we didn't use it on WebSockets, because it already has framing) but we decided to move it up to the SignalR layer to keep the Sockets layer cleaner.

Message Types, Framing, etc. are all handled in the `IHubProtocol` implementations now. EndPoints work with raw binary data (allowing the EndPoint to apply whatever protocol it wants). This means that EndPoints can easily be used to implement other protocols.
