### ISSUE TITLE
Chat app - SignalR with API

### ISSUE THREAD

**Issue by virzak** [aspnet/SignalR#1198]
Hello,

A client has an ability to post messages to chat both using signalr and through API.
When a message is posted through SignalR all clients get notified, just like in the chat sample, so that's all good.

However, when a message is posted through API, the API's response returns all the necessary information to the client, so there is a need to post to AllExcept(my_connectionId). Since API controller, and doesn't have HubCallerContext.ConnectionId, there is no clear way for specify my_connectionId.

The only hacky way I could think of was to pass it as an API argument:

```
connectionId: (connection as any).connection.connectionId
```

What would be the best way to handle such situation?

**Comment by anurse** [comment]
You are right that you have to manage this yourself right now. There's no default way for an API to know what connection is represented by the API request, and it's not really feasible for us to add one in a general-purpose way (each application is going to have it's own semantics regarding how it wants to do this).

I would actually suggest against using the API response to satisfy the needs of the client here. It seems cleaner to me to have the messages always flow from one place (the SignalR connection) rather than having two pipelines for messages. Instead, just have the API response contain an acknowledgement that the message has been received, and then transmit the message over SignalR as usual. Unless you're using Long Polling, you wouldn't really save on bandwidth by having the API response contain the message, since you already have an SSE or WebSockets connection open. Having a consistent API behavior seems worth any minor bandwidth loss from Long Polling anyway.

If you really wanted to do this though, you'd probably have to do as you suggest and send the Connection ID as a parameter to the API request. You could maintain a mapping from User identities to Connection IDs in your Hub and then make it available to your Controllers through DI. But if you want to support multiple connections from the same user (imagine multiple devices, or multiple browser tabs), then you would have a problem since only one of those devices is going to get the API response, so you'd need a way to send the message to the other devices as well. The only reliable way to do this would be to have the client send it's connection ID in the API response.

**Comment by davidfowl** [comment]
Don’t use he connection id, use groups. There’s another thread on this on a closed issue and it details how you can do this reliably.

**Comment by anurse** [comment]
Yes, Groups would be the most appropriate way to group connections when you need to do so. But as I suggested, your main problem would probably be best done by using SignalR for messages and just sending a simple ACK back from your API request rather than trying to "optimize out" SignalR for that one client prematurely :)

**Comment by virzak** [comment]
Thanks for the responses. 

@anurse , We need to use the API response for our Android client. From what I know Java client is coming at some point. So can't just return an ACK.

Browser client also needs to use API since we have file upload and I didn't find any example of how to do that at this time. Could you point me in the right direction?

@davidfowl Not which of the closed issues I should read, but here is how I think it would work:

- Connect to the server, generate a group with unique name, map it to a connectionId 1-to-1
- Call the server to get a group associated with the connection
- Pass the group to the API call, get the connectionId associated with the group and use AllExcept with that connection.

Is that correct?

**Comment by anurse** [comment]
> We need to use the API response for our Android client. From what I know Java client is coming at some point. So can't just return an ACK.

Gotcha. Yeah, the Java client is on the backlog but we've got a lot of stuff on that backlog right now so I can't commit to exactly when it will arrive.

> Browser client also needs to use API since we have file upload and I didn't find any example of how to do that at this time. Could you point me in the right direction?

We have some limited support for binary data in Hub invocations, but it's only really worth using if you're using the MsgPack protocol. Right now, I think that standard HTTP is the way to go for file upload

> Not which of the closed issues I should read, but here is how I think it would work:

I don't know exactly which issue @davidfowl was talking about but I think you're mostly on track. You shouldn't need to have a 1-to-1 mapping between connection ID and group though, you can send to individual connection IDs just fine. We're also working on a `GroupExcept` call type where we send to all the members of a group **except** the connections you specify. So if you have a Group that represents a "room" or "conversation" in your chat app and your API call takes in the connection ID of the caller, you could use this `GroupExcept` call to send the message to all connections participating in the connection **except** the one that made the API call. Then other devices for the same user will get the update.

However, in the case you describe with the Android client, there wouldn't be a SignalR connection representing that client, correct? You could just have the message sent **both** via the API response **and** SignalR and just have all the SignalR-aware clients ignore the API response, since they know they'll get the message through SignalR.
