### ISSUE TITLE
Custom headers support

### ISSUE THREAD

**Issue by siberianguy** [aspnet/SignalR#1202]
One of the known issues with full .NET framework implementation of SignalR client was that it did not support custom headers. It can be problematic in a number of scenarios (i. e. [here's a long discussion](https://github.com/elcattivo/CloudFlareUtilities/issues/18) of how SignalR doesn't work if you need to bypass CloudFlare). Is there any progress in this regard in a .NET Core implementation or forking and reimplementing a bunch of classes (how it was done for an old version) is the way to go?

**Comment by anurse** [comment]
Yep, we support custom headers. However, due to limitations in the browser we can't support them in WebSockets **in a browser-based client**.

For .NET clients though you can use the `.WithHeader` (for non-WebSockets) and `.WithWebSocketOptions` (for WebSockets; we do plan to unify these at some point) methods on `HubConnectionBuilder` to configure headers.

**Comment by siberianguy** [comment]
@anurse Thanks for bringing good news :) Will try convert a hacky solution for old SignalR to a new one. By the way, are there any specific plans about the first release? Honestly, it feels weird such an important library as SignalR is not released even after .NET Core 2 is out there.

**Comment by anurse** [comment]
The current plan is that SignalR will be part of the .NET Core 2.1 release. I don't have specific dates, but we're moving towards a preview in the next couple months.

> Honestly, it feels weird such an important library as SignalR is not released even after .NET Core 2 is out there.

I hear you. I definitely wish it could've come sooner, but with limited resources and rebuilding the whole ASP.NET platform, some things had to get prioritized above it. We're working hard on getting it out in the next release though!

I'm going to close this issue since it sounds like the question has been resolved. Feel free to comment on this, or re-open it if you still have questions!
