### ISSUE TITLE
Please clarify how https://github.com/SignalR/SignalR relate to this project?

### ISSUE THREAD

**Issue by Bartolomeus-649** [aspnet/SignalR#1226]
There are a lot of sites/pages claiming/appearing to be "**the**" SignalR page.

I suggest there should be _one and only one_  authoritative page on SignalR, no matter which version, platform or whatever.

That page/site could point to other sites if there's a need for it.

Today when I searched for SignalR I found there pages

1. ASP.NET: Learn About ASP.NET SignalR (https://www.asp.net/signalr)
This site contains links to pages from 2014 on docs.microsoft.com/en-us/aspnet/signalr, there are also links to example code from 2014 on code.msdn.microsoft.com. Documentation from 2014, is this really what people should read to understand and use SignalR the correct way?

2. signalr.net: ASP.NET SignalR (http://signalr.net/)
This site links to documentation from 2013 on github.com/SignalR/SignalR/wiki, a site with less then 50 commits during the last year. It also gives a non working link to SignalR on jabbr, where the "SignalR team is supposed to "hang out"

3. Github: SignalR/SignalR (https://github.com/SignalR/SignalR)
A project on GitHub that claims to be the ASP.NET SignalR "home", and as mentioned previously has less than 50 commits this year and documentation from 2013

4. Microsoft Docs: Docs/ASP.NET/ASP.NET SignalR (https://docs.microsoft.com/en-us/aspnet/signalr/overview/getting-started/introduction-to-signalr)
This is the documentation that the ASP.NET (1) site links to. This site is so outdated that it claims SignalR doesn't work in Edge and the list of supported operating systems does not include Windows 10!

5. Github: aspnet/SignalR (https://github.com/aspnet/SignalR)
This is  a much more active project than SignalR/SignalR, but on the other hand it say it is only SignalR for ASP.NET Core.

So, where should people go to read about SignalR?

**Comment by anurse** [comment]
Hey @Bartolomeus-649 . Sorry things are a bit confusing right now as we're work on a completely new version of SignalR.

Except for this repository, all of the above resources you referenced relate to the currently released version of SignalR (the latest version of which is 2.2.2), which is the one designed for the ASP.NET platform. The JabbR link you mentioned doesn't work because JabbR has been shut down (it was really just a side project managed by @davidfowl , and wasn't a full support channel)

This repository is tracking development of a brand new version of SignalR for ASP.NET Core (as you noted in your issue).

The Docs you referenced on https://docs.microsoft.com are the most up-to-date. You're right that there are a number of things that have changed since the docs were written (Windows 10 has been released, etc.) but that doesn't affect the docs that actually cover the usage of the framework.

**Comment by ojorma** [comment]
@EnCey https://channel9.msdn.com/Shows/On-NET/NET-Core-21-Roadmap-PT2

**Comment by anurse** [comment]
> Will the new and improved .NET Core version replace the current one? Will it be ported to full .NET framework?

The new version of SignalR is part of ASP.NET Core, which supports both .NET Framework and .NET Core. However, your main web application has to be ported to ASP.NET Core to use SignalR.

**Comment by Bartolomeus-649** [comment]
Which is the main page where I should go read about SignalR, and where I can find all information necessary to decide on what version, packages and so on to use in a new project?

**Comment by anurse** [comment]
The documentation is still coming, but I can give a brief summary:

* SignalR for ASP.NET 4.x
  * Packages: `Microsoft.AspNet.SignalR.*` on NuGet, `signalr` on NPM
  * Versions: `2.2.x`
  * Use this when you are adding SignalR to an app using ASP.NET 4.x (`System.Web`)
* SignalR for ASP.NET Core
  * Packages: `Microsoft.AspNetCore.SignalR.*`
  * Versions: `1.0.0-preview2-final` (and future previews)
  * Use this when you are adding SignalR to an app using ASP.NET Core

The version of SignalR you use is basically tied to which version ASP.NET you want to use. You can see https://docs.microsoft.com/en-us/aspnet/core/choose-aspnet-framework?view=aspnetcore-2.1 for a comparison of ASP.NET (`System.Web`) and ASP.NET Core. SignalR for ASP.NET (`System.Web`) does not work in an ASP.NET Core application, and SignalR for ASP.NET Core does not work in an ASP.NET (`System.Web`) applications.
