### ISSUE TITLE
Extend Chatsample with groups

### ISSUE THREAD

**Issue by mortenbirkelund** [aspnet/SignalR#1256]
Hi
I have a project where I need to use the presence functionality from the chatsample on multiple pages. Therefore I would like to extend the presence functionality from the chatsample, but I am uncertain as to how the hub should be implemented.
The idea is that the hub can be access from different pages (representing a game between 2 contestant). 

Therefore the user should be added to a group that is specific for the game he is visiting and whenever the `OnUsersJoined` and `OnUsersLeft` is called, it should only be for other users in the same group. 

I just cant figure out how what should be altered in the current chatsample? I hope that i am not the only one that could be needing this functionality, and therefore it could be beneficial with a good example. 

This is a description of the process. 
1. A user visits http://www.domain.com/game/{id}
2. The user is instantly added to the group {id}
3. Only the users in the same group (id) are alerted that a new user joined. 
4. When a user leaves, only the users in the group are alerted that a user have left. 

Thanks in advance for your time.

**Comment by anurse** [comment]
The presence functionality isn't a fully supported feature, which is why it's only in the sample right now, so things are definitely a bit rough there :). Happy to help see if we can figure this out though!

There are a few options here.

First, you could simply avoid using a group. If there are only two players in a game, then when User A sends a message, the Hub knows exactly which user(s) need updates (If you want to support multiple devices, User A may need updates because of the other devices that did not initiate the action). You can simply look up who the other user in the game is and send directly to that user using `Clients.User(username)`

If you want to use a group (which would definitely scale better if you plan to move beyond 2 players), then I would suggest storing a mapping of Usernames to Group IDs, which is updated when a user "joins" a game (how this is defined depends on your app; it sounds like this is when the user navigates to `/game/{id}`). Then, when `OnUsersJoined` fires, you can look up this mapping and add the user to the appropriate group.

**Comment by mortenbirkelund** [comment]
Hi
I am planning to scale to more than 2 users eventually, so the second options sounds like the way to go. I hoped that it would be possible to make some adjustments to the presence sample in order to use groups, but it sounds like the creating a mapping service could be a solution. 

Are there any plans on simplifying the presence functionality. I think this is a very fundamental functionality in signal R.

**Comment by anurse** [comment]
The goal with the presence sample is basically to prove that it our extension points make it possible to build presence, which allows us to prioritize other things for the first release (because presence systems can be built on top of our primitives). I agree, it is an important functionality, but there are a lot of important things in SignalR and only so much time and resources :). So priorities have to be set, and built-in presence didn't quite make the cut. Presence has a lot of application-specific concerns, which means designing a general-purpose system for built-in presence takes a lot of work. The abstractions we have now allow users to build application-specific presence systems for now while we get the core finished and start exploring how to build a good general-purpose system.

**Comment by mortenbirkelund** [comment]
I understand. Thanks for your reply.
