### ISSUE TITLE
query string is too long with big bearer token attached in the URL

### ISSUE THREAD

**Issue by dannyzhan** [aspnet/SignalR#1266]
Guys,
   I am using JWT token in a asp.net core 2.0 project with signalr.
To attach the token in the query string works in my project.
However, after the token gets bigger, the browser tells me the query string is too long.
Is there another way to send token?
Can we send the token with the sub protocol?
Thanks!

**Comment by anurse** [comment]
Unfortunately, there's no way to send a token in the browser other than via the QueryString. It's a limitation of Browser WebSocket APIs. Maybe we could use the sub-protocol as you suggest. Or send it in a WebSocket frame. We don't have the resources to implement those for Preview 1 but we can take another look at this before RTM.

**Comment by anurse** [comment]
How large is your JWT token? Usually large JWT tokens occur because you have many claims in them, are you able to remove any of the claims?

After some quick research, it seems most modern browsers (except IE) support up to about 80,000 characters for URLs (including query string). IE does have a lower limit of 2,000 characters.

**Comment by dannyzhan** [comment]
@anurse , it's about 5KB in size. we have many claims to save permission info in the token.
currently I generates two tokens at the same time, one with full permission claims for normal use,
another one removed most of the permission info for communicating with signalr.
After the removal it's only 900 chars.
This limitation is really a pity. I have to query database to get the permission info every time.

**Comment by anurse** [comment]
Unfortunately we're stuck with browser limitations here. The Browser APIs do not allow Headers to be added to a WebSocket request, which means we're stuck with the URL, which has these limits. If you want to build something for your application, you could explore sending an initial message that performs the authentication (sending the token). Also, you could look up the additional data in the `OnConnectedAsync` method and store it in the `Context.Connection.Metadata` dictionary under your own custom key. That table is preserved in memory for the life of the connection (and since WebSockets are inherently sticky, you know the client is always coming to the same server).

**Comment by eByte23** [comment]
So is there any update on this? I was looking for the same thing and even if you cut back your token to almost bare minimum then you may still get issues.

Or if you believe this will work in current manor is there a nuget feed for the current dev version with this in it? I'd prefer not to have a custom version.

**Comment by pekkah** [comment]
If you have token with 5KB size I would recommend switching to reference tokens. Especially if it's and access token you're transferring withe every request.

**Comment by andrx** [comment]
@pekkah do you have a working configuration example for reference token?

**Comment by usernameAMRUTHA** [comment]
Do anybody have a solution here. We are facing the same problem.
