### ISSUE TITLE
How to add global authorization filter for hubs?

### ISSUE THREAD

**Issue by MhAllan** [aspnet/SignalR#1276]
having [Authorize] attribute works on hubs, but it doesn't use the MVC options. so the code below will still invoke the hub even the user is not authorized.

services.AddMvc(options =>
{
    var policy = new AuthorizationPolicyBuilder()
                      .RequireAuthenticatedUser()
                     .Build();
                options.Filters.Add(new AuthorizeFilter(policy));
}

any solution?

**Comment by MhAllan** [comment]
Found it: app.UseSignalR(route => route.MapHub<YourHub>("HubName")).UseAuthentication();

**Comment by anurse** [comment]
That's somewhat by design. MVC and SignalR are completely unrelated components in the system. MVC Filters don't affect SignalR.

You should be able to use Authorization policies in SignalR, via the `Authorize` attribute. If that's not sufficient, we can explore adding some additional global configuration (but it would be in a SignalR-specific section).

You can always fall back to putting a Middleware in front of SignalR that does the Authorization check you want if the request is headed for the SignalR hub.
