### ISSUE TITLE
Question: SignalR scaling with redis, monitoring

### ISSUE THREAD

**Issue by rdcm** [aspnet/SignalR#1328]
After some attempts i could run signalR app with redis.
But i have some questions about scaling. 
SignalR use Pub/Sub redis mechanism, should i use sticky session on nginx side or redis enough?
If I understood correctly sticky-session is required for all transports except websockets.
Can i monitoring existing connections count, connections fails?

**Comment by BrennanConroy** [comment]
Like you said sticky sessions is required for all transports except websockets, although it is still required by websockets if you don't specify websockets explicitly in the connection creation.

When you call `AddRedis` you can pass in your own redis connection factory. This would allow you to hook onto the `ConnectionFailed` and `ConnectionRestored` events on the redis connection.

**Comment by rdcm** [comment]
Sounds great, thanks for answer!

Two more question about signalR:
-I found how choose only websockets transport type, but can i restrict protocol type(only text for example) on server side?
-protobuf will be supported in future?

**Comment by rdcm** [comment]
Last question about scaling :) Orleans framework suggest alternative way for app scaling, are you considering scaling scheme with grains?

**Comment by BrennanConroy** [comment]
We don't have protocol restriction yet, but we have an issue for it and it's on our radar.
Protobuf probably wont be done by us anytime soon, we chose MsgPack for out of the box binary serialization

**Comment by anurse** [comment]
> protobuf will be supported in future?

We don't expect to support ProtoBuf in the 2.1 release. We explored it early on but found MsgPack was much more appropriate as a built-in binary protocol because it is self-describing (ProtoBuf requires an up-front schema be defined for each method before serialization or deserialization can occur). The protocol is pluggable though so if you find MsgPack is unsuitable as a binary protocol, you could look at adding something custom to your application.

> are you considering scaling scheme with grains?

We aren't considering any scaling schemes outside of Redis and *possibly* Service Bus for 2.1. It's just a matter of prioritization, we don't have the resources to explore everything and we know we want to do those two :). Again, the scale-out system is pluggable so one could build an Orleans-based scale-out provider that could plug in to SignalR.

**Comment by rdcm** [comment]
I think that's all, thanks for all answers!

**Comment by lawgorht** [comment]
in `RedisHubLifetimeManager.cs` there is this comment:

>   if the connection is local we can skip sending the message through the bus since we require sticky connections.

is that an old comment or do we need sticky sessions if using redis even if only websockets are used?

**Comment by anurse** [comment]
Even with WebSockets, I'd strongly recommend using sticky sessions. However, you are correct, if you are configuring your client to explicitly allow only WebSockets (`new signalR.HubConnection(url, { transport: signalR.TransportType.WebSockets })`), then you aren't required to use sticky sessions because the WebSocket itself is already "sticky"

**Comment by lawgorht** [comment]
> because the WebSocket itself is already "sticky"
thanks, that makes sense and it helped me to understand the whole thing.

**Comment by lawgorht** [comment]
May I ask another question regarding stickyness of Websockets? 
If I strictly limit the server and the client to web sockets as you describe, can I in any case assume that even if my Azure Webrole scales up, the connections will still work without interruption?

**Comment by davidfowl** [comment]
I wouldn't assume that, but I don't know enough about the mechanics on how that stuff works to know if that's true.

**Comment by lawgorht** [comment]
thank you. As far as I understand it after reading [Configure the distribution mode for Azure Load Balancer](https://docs.microsoft.com/en-us/azure/load-balancer/load-balancer-distribution-mode) and [Load balancing with sticky sessions (source IP distribution mode for load balancing) in Cloud Services](https://feedback.azure.com/forums/217313-networking/suggestions/20215108-load-balancing-with-sticky-sessions-source-ip-dis) I can use standard _Hash-based distribution mode_ on the Azure load balancer and if the service scales I have to make sure on the client that it reconnects on error.

**Comment by anurse** [comment]
> can I in any case assume that ... the connections will still work without interruption?

From my experience, you shouldn't ever assume your connections will work without interruption, no matter how they're configured :). It's definitely worth thinking seriously about how your application should behave when the client loses the connection to the server. The connection loss could be temporary, in which case a reconnect is the solution, or it could be a long-term loss of connectivity and you'll want to consider disabling UI and providing a mechanism for the user to retry later. You don't want your service going down, coming back up, and then going down immediately under a barrage of clients reconnecting ;)
