### ISSUE TITLE
Question : Support plan for server receiving data from client

### ISSUE THREAD

**Issue by hayha06** [aspnet/SignalR#1329]
Do you have plan to support the server receiving return data from client after an invoke server <--> client.

If no, is there any workaround ? I really need my server to invoke method in client and receive a return result (not in broadcast)

**Comment by anurse** [comment]
We've talked about it. The 1:1 scenario is pretty easy (server invoking a method on a single client), but it gets difficult with fan-out (broadcast, groups, users, etc.). It's on our list, but it may not make 2.1 because of prioritization. We're making sure to take steps to allow us to add it on later though (see #1300 ).

A fairly simple workaround is to have the client invoke a server method and provide the result there. It's not ideal, but it generally works and with a little hacking around with connection metadata and [`TaskCompletionSource`](https://msdn.microsoft.com/en-us/library/dd449174(v=vs.110).aspx) you could also probably make it look a lot like a method invocation returning a value.

**Comment by davidfowl** [comment]
> If no, is there any workaround ? I really need my server to invoke method in client and receive a return result (not in broadcast)

Why do you need to do this? Are you thinking about the case where the client is unreachable? We've discussed it and if we do it, it would only ever work for single clients but even then there's tons of caveats.

**Comment by hayha06** [comment]
@anurse  Thank for your answers, I understand your point. I will have a look on what you suggest.

@davidfowl In fact, I think I need it but maybe I'm wrong, let me explain you my simplified use case that let me think I need it : 
So let's imagine, I have a chat application in angular 4 and asp net core as back end server. And on the client side (angular) I have some timeout that make the chat open or close.
And on my back end server I have an API that use signalR to communicate with the client.
So the caller come from external application, and through the API (with specific connectionId send in the request) use signalR to interacte with the specific client.

So all of this is working as expected, but I'm stuck on the way to get the state of the chat (open or close) in my controller on the asp net core back end so I can send it back to the external caller in the controller return.

Don't hesitate to ask me more if I'm not clear enought.

So maybe there is better way to reach this, but the simplest I see is to have a return from client when called from server.

**Comment by hayha06** [comment]
@davidfowl So does my use case make sense on what I asked?

@anurse I'm a bit stuck on how to implement what you suggest, I create a stackoverflow question (https://stackoverflow.com/questions/48464800/signalr-workaround-to-get-client-data-from-server) May I have some help? Thank you in advance

**Comment by acjh** [comment]
That [Stack Overflow question](https://stackoverflow.com/questions/48464800/signalr-workaround-to-get-client-data-from-server) has been answered :)

**Comment by davidfowl** [comment]
dupe of https://github.com/aspnet/SignalR/issues/903
