### ISSUE TITLE
ASP.NET Middleware run for SignalR requests

### ISSUE THREAD

**Issue by SaltyDH** [aspnet/SignalR#1334]
I'm unsure if this is by design, a configuration issue on my part or something that needs further discussion.

I've got an existing ASP.NET Core application with a number of custom Middleware definitions. Whilst adding SignalR to this application, I noticed that the existing Middleware run for the SignalR request. This request is marked as upgrade to Websockets which has the effect of the Middleware not completing the next() calls until the Websocket disconnects.

For my scenario this means that my unit of work doesn't complete as the HttpRequest is now long lived and I hold a database connection open for the duration of the Websocket's lifetime.

I this something I have to be conscience of when developing ASP.NET Middleware? Or is something else going on here?

**Comment by davidfowl** [comment]
That's by design as the request hasn't ended so the middleware won't run until the websocket connection goes away. What were you expecting to happen with the websocket request?

**Comment by SaltyDH** [comment]
I think the problem stems from not expecting anything to happen - You add SignalR and it has this entirely separate ecosystem around Hubs etc but I didn't correctly identify the parts that are actually coupled to the existing ASP.NET request pipeline (It ran like this for months before I started getting SqlConnection pool exhaustion)

To answer your question, I had (incorrectly) expected that the middleware would complete their next() calls as part of upgrading the Request to a websocket. Essentially handing off what was originally a HTTP request to something that manages it as a websocket.

I wonder if middleware can be attributed or marked in some way to indicate that they are only applicable to certain situations. Essentially a cleaner/terser way of avoiding the need for `if (Request.Path.Equals("/signalr")) next();` checks in all middleware that are not relevant to the long lived Signalr requests?

**Comment by davidfowl** [comment]
> I wonder if middleware can be attributed or marked in some way to indicate that they are only applicable to certain situations. Essentially a cleaner/terser way of avoiding the need for if (Request.Path.Equals("/signalr")) next(); checks in all middleware that are not relevant to the long lived Signalr requests?

Middleware at the core is a function so there's no higher level concept of "run this this path matches". The middleware itself needs to branch. Also in the existing new SignalR, hubs need to be mapped to a specific path.

**Comment by SaltyDH** [comment]
Thanks @davidfowl

**Comment by arishlabroo** [comment]
Ran into a similar problem as SaltyDH. 

Now that I know it, i can justify it, but I am guessing you don't want everyone to learn the hard way. Especially since you have tried so hard (and done an amazing job) to keep things consistent between mvc and signalr, the middleware behavior was expected to be consistent too (at least I thought so). 

As @SaltyDH pointed out, I was expecting (incorrectly) this too

> I had (incorrectly) expected that the middleware would complete their next() calls as part of upgrading the Request to a websocket. Essentially handing off what was originally a HTTP request to something that manages it as a websocket.




And recently in production we realized a memory leak because we had a request logging middleware, profiling middleware, log scoping middleware, a middleware to created custom context and child container per request.. etc..etc.. All these were working stellar in the mvc app for a while and then we introduced a hub expecting everything to just work, and ......memory leak :(

Just leaving this comment here to highlight that this is atleast a significant documentation miss

**Comment by davidfowl** [comment]
How was it a memory leak? Just curious? Do you mean higher than usual memory usage?

**Comment by arishlabroo** [comment]
Yes. Way higher and kept increasing with users. 

for e.g. we have a few middlewares into which we parameter inject a pretty expensive custom request context(it has user information, profile information, environment, culture etc..etc..)..

I understand that the context is valid for the lifetime of the websocket connection since, well, it is the correct context, but did not realize/account for the longer life of expensive objects. Objects with expectation of request scope started behaving like singleton. 

As I said earlier, I understand now why, but still it seems like a very important detail which should be highlighted more in the documents. 

Its mentioned many times, if you have an existing aspnet core mvc site, just `UseSignalR` and everything should just work. all those places should come with a disclaimer 😄

**Comment by arishlabroo** [comment]
Noted😬.
https://twitter.com/davidfowl/status/1007695916558499840?s=21

**Comment by thoemmi** [comment]
@arishlabroo wrote:

> I understand that the context is valid for the lifetime of the websocket connection since, well, it is the correct context, but did not realize/account for the longer life of expensive objects. Objects with expectation of request scope started behaving like singleton.

I'm experiencing the same challenge: Objects like DbContext are used for the lifetime of the connection. So what I would like to know (or what should be described in the docs)

* how to handle per-invocation scopes (like DbContext)
* When writing middleware, is there a way to distinguish "normal" requests and long-living connections like SignalR?

**Comment by davidfowl** [comment]
SignalR creates a scope per hub invocation so scoped services work.

> When writing middleware, is there a way to distinguish "normal" requests and long-living connections like SignalR?

There's nothing definitive, you could use a bunch of heuristics tho.

**Comment by arishlabroo** [comment]
🤔 what will happen if a scoped service is parameter injected into a middleware?

**Comment by davidfowl** [comment]
It’ll get disposed when the websocket connection closes.

**Comment by arishlabroo** [comment]
So just to confirm, an instance of the scoped service will be created per hub invocation. and also, if a middleware depends on the same scoped service, it will just hang on to the first instance created till the websocket connection closes. 🤔

**Comment by davidfowl** [comment]
That's correct.

**Comment by arishlabroo** [comment]
How do you recommend I create a service always scoped to the websocket connection then?

<sup>ps:really appreciate your time @davidfowl </sup>

**Comment by davidfowl** [comment]
@arishlabroo there isn't a generic websocket scope. What specifically are you asking for?

**Comment by arishlabroo** [comment]
as mentioned above 

> for e.g. we have a few middlewares into which we parameter inject a pretty expensive custom request context(it has user information, profile information, environment, culture etc..etc..)..

The `IExpensiveCustomContext` is used both in a middleware and the hub. 

I guess I am asking, what scope should I use for my service if I want only one instance for the life of the websocket connection.

The instance that the middleware hangs on to, how do i make that the only instance.

**Comment by davidfowl** [comment]
`IExpensiveCustomContext` can't be injected into the hub then, you'll want to resolve it directly from the RequestServices if you want to get the same instance.

There is a fundamental issue with that though. If you're using long polling, the connection exists across several requests so `IExpensiveCustomContext` can come and go for the same connection object.
