### ISSUE TITLE
Idea for TagHelpers

### ISSUE THREAD

**Issue by grahamehorner** [aspnet/SignalR#1344]
Please consider create a set of SignalR TagHelpers that simplify integrations with Mvc Razor Views/Pages eg.

<asp-signalr>
<connection name="" hub="" protocol="" />
<events>
<event name="" action=""/>
<events/>
<methods>
 </asp-signalr>

which would scaffold/generate up javascript code placing the code just prior to the </body> tag

**Comment by anurse** [comment]
What would these tag helpers do? This sounds like it would be a fit for a project on top of SignalR rather than built in to SignalR as it would mess with the layering to have SignalR depend upon Razor concepts.

**Comment by grahamehorner** [comment]
Idea is that the TagHelpers would be a separate project and generate the boiler plate code for connecting to a hub handling errors/events/method that receive/call/invoke the hub/client scripts (in essence creating a strongly types proxy) explicitly from TagHelpers or automatically via reflection or decorating the hub with some attributes.

**Comment by anurse** [comment]
So you're basically looking to elimiate the `.invoke("MethodName", ...)` syntax and generate proxies that let you just use `.methodName()` on the client? That's covered by https://github.com/aspnet/SignalR/issues/290

We wouldn't use Tag Helpers for this though, since that would couple it to Razor. We've talked about a build step that generates these proxies as part of your build, for you to pull in to your pages however you see fit. Regardless, I don't expect that to happen for 2.1 as we're pretty fully booked with work for that milestone.

**Comment by grahamehorner** [comment]
Yeah, that it; but I was thinking about having a bit more control over the generation of the proxy as not every page/view requires access to the complete set of functions on the hub, and publishing a proxy script on a page that isn’t secured but has access stubs to secured hub functions is IMHO not good, hence having a set of tag helpers for generation of the proxy when using mvc razor views/pages. I do take your point however this wouldn’t work for non razor projects. Thanks

**Comment by anurse** [comment]
Yeah, we'll want to cover all those things in #290, and make it as customizable as possible. I think a Tag Helper isn't really the right way to do this though. Certainly, once the proxy generation code exists, it could be wrapped up in a Tag Helper.
