### ISSUE TITLE
update samples to use npm

### ISSUE THREAD

**Issue by grahamehorner** [aspnet/SignalR#1354]
currently the samples reference the client directly via the <Target Name="CopyTSClient" BeforeTargets="AfterBuild"> please consider updating the samples to use the published npm package and give guidance on using the npm package within a project

**Comment by BrennanConroy** [comment]
The samples in this repo will use the source directly because we want to be able to easily test changes locally. We have a [readme](https://github.com/aspnet/SignalR/blob/dev/README.md) which gives some instructions on how to consume the packages

**Comment by grahamehorner** [comment]
thanks but I've followed the readme and the scripts aren't deployed into the wwwroot/lib folder as you would expect, also the readme make no reference to the need for any additional steps for the client scripts?

**Comment by anurse** [comment]
Since we deploy via NPM, the scripts are just placed in the `node_modules` folder, it's up to you to build the infrastructure that pulls them in to `wwwroot`. We went this way because it's how most modern JavaScript libraries are deployed and makes things easily consumable from the large variety of JavaScript build systems. You can use tools like [`webpack`](https://webpack.js.org/) to help this process and automatically pull in things from NPM modules. If you want a simple example, look at how the [FunctionalTests csproj](https://github.com/aspnet/SignalR/blob/dev/client-ts/FunctionalTests/FunctionalTests.csproj) pulls in Jasmine (the testing library we use). It's basically just an AfterBuild step that copies the file out of the `node_modules` folder.

**Comment by anurse** [comment]
I've submitted https://github.com/aspnet/SignalR/pull/1355 to clarify the README a bit, since it's not super clear on how to use them once you've installed them

**Comment by muratg** [comment]
:+1:
