### ISSUE TITLE
Transport Fallback

### ISSUE THREAD

**Issue by mikaelm12** [aspnet/SignalR#1373]
Looks like it will be coming back.

**Comment by JinsPeter** [comment]
Does this means, There will a Transport type automatic which will take care of the connection change. I mean if Websocket work, Will it switch itself to Long Polling.??

**Comment by mikaelm12** [comment]
The idea now is that if you fail to initially connect with the requested transport, we will try to fall back to other transports in the order WebSockets, Server Sent Events, then LongPolling. The design isn't completely finalized but we have decided that we want to add the core fallback functionality back

**Comment by JinsPeter** [comment]
This is out of curiosity.. I have not yet contributed to any open source project and may have limited knowledge in that matter.

**Comment by anurse** [comment]
Fallback will need to be implemented in both clients and we'll need to do some design to figure out exactly how we want to accomplish it. There are lots of edge cases that need to be considered when building a general-purpose feature like this :). I'm not sure we'll do any fallback after the connection is established, for example, as that has caused a lot of problems in previous versions of SignalR because you have to deal with what happens with messages sent while transport fallback occurs.

If you're looking for something to contribute back to the project, I don't think this is a great fit, I'm afraid. We certainly appreciate your interest, but we haven't even really defined what this feature is going to look like yet :).

**Comment by alexzaytsev-newsroomly** [comment]
@anurse re: `because you have to deal with what happens with messages sent while transport fallback occurs.` Wouldn't you simply open the second connection, then set the first one to draining (e.g. let old messages finish but not accept new messages); for further requests with the same client id use the second connection, then disconnect at the re-negotiating end?

**Comment by anurse** [comment]
> then set the first one to draining

Except that in the scenario we're talking about, the first transport failed at some arbitrary point with neither the server nor the client knowing for sure which messages it got.

**Comment by mikaelm12** [comment]
Initial commit is merged : adbd964efdfa369b2549407492a6d085c65766ef
More work tracked here:  https://github.com/aspnet/SignalR/issues/1554
