### ISSUE TITLE
How to deploy a SignalR console application to Azure?

### ISSUE THREAD

**Issue by BruceL33t** [aspnet/SignalR#1376]
I've got multiple instances of a SignalR (host/server) console application (created with "dotnet new console") running with dotnet run [args] (or dotnet publish, followed by dotnet mydll.dll [args]) in localhost.

I also have other console applications and web applications which needs to be able to consume / reach these SignalR endpoints.

This works just fine on localhost, with unique ports for different instances, but I have a hard time deploying them to Azure.

For each instance of the SignalR console application I tried to zip it, running it with different command line args in a batch file for each of the zip files (instances). 

Then I added each zip file as a webjob under the already created React frontend web app in Azure (SignalR client/consumer). 

Each of the SignalR instances are running in localhost with a different port, but I cannot seem to reach them if adding them as webjobs. Also if "triggered" is chosen, they will stop shortly after they are started, so I had to chose "continous" even though, once started, they should be running until manually terminated.

Is it necessary to create a separate web app for each instance of a signalr console application, even if all of them can run on localhost with different ports as command line arguments?

Is webjobs the way to go (didn't seem to work for me, when I added it under the React web app)? 

Should we avoid IIS (heard that SignalR doesn't work that well with IIS)

Should we use docker?

Should they be self-contained (exe files)?

Or what is the recommended way to host single/multiple instance(s) of a SignalR console application in Azure?

Hopefully it makes sense - I'm just looking for the easiest and best way to take your SignalR console application and deploy it so Azure.

**Comment by anurse** [comment]
> I also have other console applications and web applications which needs to be able to consume / reach these SignalR endpoints.

I think using multiple Azure App Service applications is your best bet here. WebJobs are only designed for simple batch processing tasks. It's possible they are blocked from binding to ports or otherwise limited. As a reminder, creating multiple App Service applications within the same App Service Plan doesn't incur any additional costs (since all the applications in the Plan share the same server machines).

> Should we avoid IIS (heard that SignalR doesn't work that well with IIS)

I'm not aware of any major issues with IIS and SignalR right now. There are minor issues, which we are looking at resolving before release, but you should feel free to use IIS and report any issues you find here.
 
> Should we use docker?

You could, but for that you'd need to use something like App Service for Containers or Azure Container Service which is a much more complicated system. I don't think it's necessary unless you are planning to switch your entire application to be based on containers.
 
> Should they be self-contained (exe files)?

You shouldn't have to use self-contained deployments unless you want to use a runtime that is not currently installed in App Service.

**Comment by BruceL33t** [comment]
Thanks @anurse that makes it very clear - and good you mentioned that you can create multiple apps within the same App Service Plan :-)

> Multiple Azure App Service applications  

You mean Web Apps, right?

**Comment by anurse** [comment]
> You mean Web Apps, right?

Correct. "Azure App Service" is the umbrella term for "Function Apps", "Web Apps", "Logic Apps", etc.

**Comment by davidfowl** [comment]
I would avoid app service if you want a scalable signalr application (large number of concurrent connections).

**Comment by aspnet-hello** [comment]
We periodically close 'discussion' issues that have not been updated in a long period of time.

We apologize if this causes any inconvenience. We ask that if you are still encountering an issue, please log a new issue with updated information and we will investigate.
