### ISSUE TITLE
Preview 1 and basic authentication in browser

### ISSUE THREAD

**Issue by msmolka** [aspnet/SignalR#1388]
In previous version (alpha), when basic authentication was in use, the browser prompt for credentials for inital connection (OPTIONS). 

Now it is not prompting because of transport upgrade. Is there any way to put authorization header into initial GET negotiation connection?

**Comment by anurse** [comment]
WebSockets and EventSource provide very limited authentication capabilities (neither supports Basic Authentication uniformly, nor do they allow Authorization headers). Also, since SignalR uses multiple requests, authenticating the negotiation is insufficient, all requests need to be authenticated.

You can do authentication via the Query String across all transports. We have APIs in the client for this and a sample describing how to use JWT Bearer Token authentication here: https://github.com/aspnet/SignalR/tree/dev/samples/JwtSample

As with all authentication mechanisms, this is only secure when done over an HTTPS connection.

**Comment by msmolka** [comment]
I know it is not possible for web sockets itself, I was hoped it can be on negotiation level. But I think now this negotiation is gone.

**Comment by anurse** [comment]
Negotiation isn't used when you explicitly choose WebSockets. Also, it is not sufficient to authentication on Negotiation only, so even if we authenticated the Negotiate request, the WebSocket request would be rejected unless it also carried authentication data.

**Comment by msmolka** [comment]
Ok, I can workaround this (for testing) by manually put url to browser. After that all is working, and web socket is authenticated.
