### ISSUE TITLE
Enable CORS for SignalR Asp.Net Core

### ISSUE THREAD

**Issue by omarsourour** [aspnet/SignalR#1400]
How do I enable CORS access to my SignalR Asp.Net Core Hub? In the Asp.Net version, you could do the following:

`app.Map("/signalr", map =>
{
    map.UseCors(CorsOptions.AllowAll);
    var hubConfiguration = new HubConfiguration {};
    map.RunSignalR(hubConfiguration);
});`

How can you do this in this version?

**Comment by anurse** [comment]
See the documentation for the CORS middleware for information on configuring CORS in ASP.NET Core: https://docs.microsoft.com/en-us/aspnet/core/security/cors

**Comment by michaelgregson** [comment]
CORS behaviour has seemingly changed between SignalR 1.0.0-alpha2-final and 1.0.0-preview1-final.

In ConfigureServices:
`            services.AddCors(options => options.AddPolicy("CorsPolicy", builder =>
            {
                builder
                    .AllowAnyMethod()
                    .AllowAnyHeader()
                    .WithOrigins("http://localhost:4200");
            }));
           services.AddSignalR();`

In Configure:

`app.UseCors("CorsPolicy");`

When client is attempting to connect I get OPTIONS is not supported method, HTTP 405 response when using the preview rather than the alpha - tested using the same client code.

Please let me know if I can provide any further information.

**Comment by anurse** [comment]
Are you using the Preview client as well? Pre-release versions of the SignalR server are only compatible with the matching SignalR client version.

**Comment by michaelgregson** [comment]
Thank you for the direction you're absolutely correct - my app had retained an import from @aspnet/signalr-client, updated to @aspnet/signalr and all working.

**Comment by anurse** [comment]
Glad to hear it! Given that the underlying question seems to be resolved, I'm closing this. Feel free to comment further if you have additional questions, we can always re-open it :)
