### ISSUE TITLE
Multiple hubs, but one ws connection?

### ISSUE THREAD

**Issue by pardahlman** [aspnet/SignalR#1430]
I tend to structure my code by functionality, so my application I have a `QueryHub` (handles queries), a `LoggingHub` (captures logging) and I might get more hubs as the application evolves. Each hub is mapped to a route and the frontend connects to these, setting up one web socket connection per hub. What I'm thinking is that this approach might not scale well for larger applications, as it will allocate multiple sockets per user. 

I'm wondering if my approach fits the intended usage of hubs, or if I should just have one large hub. For this application, it would be optimal if I could define multiple hubs but only use one connection. Not sure how the API for this would look like 🤷‍♂️ 

Looking forward hearing your thought on this!

**Comment by davidfowl** [comment]
There's a longer discussion about this here https://github.com/aspnet/SignalR/issues/955. It's one of the things we moved away from because it complicates a couple of things (like authentication and routing for example).

If you're using multiple hubs just for organization within the same project then I'd recommend using a partial class with more methods.

We're going to provide a sample at some point to show how it would be possible to implement multiple other things per hub (I don't want to call them hubs because that's not one to one with a connection). So the hub is the connection, it has a route and it's where authentication lives. Then we can have another thing which is just another layer that lets you dispatch to other classes in the project.

**Comment by pardahlman** [comment]
Thanks @davidfowl - that makes a lot of sense. I'm closing this as a duplicate and keep my eyes out for new SignalR samples. Thanks!
