### ISSUE TITLE
IsWebSocketRequest not working with UseAuthentication (Signalr with Jwt)

### ISSUE THREAD

**Issue by ste4net** [aspnet/SignalR#1454]
Doing test with JWT sample and my code i saw that the approach suggested in JwtSample should not work if you call app.UseAuthentication() in Startup.Configure.
It is not yet perfectly clear for me what's the role of AuthenticationMiddleware (added by UseAuthentication extension method) in JWT authentication.
I start using it as suggested in documentation (https://docs.microsoft.com/en-us/aspnet/core/migration/1x-to-2x/identity-2x#jwt-bearer-authentication)
but if the AuthenticationMiddleware is placed before **UseSignalR** IsWebSocketRequest return always false when you test it from JwtBearerEvents (https://github.com/aspnet/SignalR/blob/dev/samples/JwtSample/Startup.cs).
Maybe this is because AuthenticationMiddleware force the call of JWTMiddleware and if it has been configured before UseSignalR it is called before the WebSocketMiddleware.
If you think i will post the issue to main repo i post here because in my case is something related to Signalr+Jwt.

**Comment by anurse** [comment]
> but if the AuthenticationMiddleware is placed before UseSignalR IsWebSocketRequest return always false when you test it from JwtBearerEvents

This is because `UseSignalR()` is what registers the WebSocket middleware, which is required to detect and process WebSocket requests. If you want to be able to detect the WebSocket request somewhere before SignalR in the Middleware pipeline you can either:

1. Manually detect the `Connection: upgrade` and `Upgrade: websocket` headers in your JwtBearerEvents
2. Put `app.UseWebSockets()` **before** `app.UseAuthentication()` and keep SignalR where it is. That will ensure the WebSockets middleware comes earlier in the pipeline.

**Comment by anurse** [comment]
In general though, you shouldn't need the AuthenticationMiddleware here. It serves two major purposes:

1. Handling OAuth callbacks
2. Automatically calling `AuthorizeAsync` for your default authentication scheme, so that `Context.User` is filled.

However, SignalR calls `AuthorizeAsync` on your behalf when you put the `Authorize` attribute on your hub.

In general, during a request, the first call to `AuthorizeAsync` will cause these events to be fired and the results will be cached. If you need to use the Authentication middleware, you'll have to put WebSockets ahead of it in order to properly read the IsWebSocketRequest value. However, the default sample doesn't put it in because it doesn't require either of the above features from it.

Also, you could simply remove the check on IsWebSocketRequest. It would allow non-WebSocket requests to carry a JWT token in the querystring, but this isn't any more dangerous than transmitting them in the header. SignalR is the only client that will put a token in the querystring anyway.

**Comment by ste4net** [comment]
Thankyou i use it becuase i am using SignalR in a SPA app that should work also without SignalR.
I know that if someone can take a look at query string can also look at the headers but i like the idea to use querystring only for hub even if it is the same security level of header .
Thank you,

**Comment by anurse** [comment]
> i like the idea to use querystring only for hub even if it is the same security level of header .

it is certainly better to only check the query string on WebSocket requests. As I mentioned above, for that simply remove the Authentication Middleware (if you don't need it's features) and SignalR will be the one calling `AuthorizeAsync` first (and triggering the event; AFTER the WebSockets middleware has initialized), or add the WebSockets middleware above the Authentication middleware (and keep SignalR below it).

Glad you got the answers you needed!
