### ISSUE TITLE
@aspnet/signalr npm package not work with asp.net core 2 

### ISSUE THREAD

**Issue by LilanMadusankaSilva** [aspnet/SignalR#1459]
@aspnet/signalr npm package not work with asp.net core 2 but @aspnet/signalr-client work with asp.net core 2 (But it has UglifyJs issue in production mode)

Anyone have any idea why this @aspnet/signalr npm package fails with asp.net core 2. Given samples use asp.net core 2.1 but 2.1 still it not to download

**Comment by davidfowl** [comment]
Because we broke things between the alpha and now.

**Comment by LilanMadusankaSilva** [comment]
That means you guys also very similar to me. I also normally do that ;)

**Comment by anurse** [comment]
Closing this as the question has been answered. Feel free to comment further if you need clarification on something!

**Comment by LilanMadusankaSilva** [comment]
Please let us know when you guys fix that issue :)

**Comment by anurse** [comment]
There's no issue to fix as far as I'm aware. `@aspnet/signalr-client` was the name of the client in the alpha release, and only works with the alpha release. In the upcoming preview, we **renamed** the package to `@aspnet/signalr`, and it only works with the upcoming preview build of the server. During the pre-release period, it's important to match the client and server versions closely. After release, we will have a commitment to ensuring some level backwards/forwards compatibility between client and server.

**Comment by LilanMadusankaSilva** [comment]
@aspnet/signalr npm package compatible with which Asp.net core version. I tried with core 2 but it not work

**Comment by anurse** [comment]
The `@aspnet/signalr` package **requires** ASP.NET Core **2.1**, which has not yet been released (but a preview release is coming shortly). There are nightly builds of ASP.NET Core 2.1 available using the guide here: https://github.com/aspnet/Home#builds

The `@aspnet/signalr-client` package was an **alpha** release that was built to work with ASP.NET Core **2.0**. As you noted, there was a bug with uglifyjs, which is fixed in the upcoming `@aspnet/signalr` release.

Also, to be very clear, when SignalR is released, it will **require** ASP.NET Core **2.1**. The initial alpha versions were built against ASP.NET Core 2.0 in order to allow users to preview the SignalR component before the official ASP.NET Core 2.1 previews.

**Comment by vijaysahu12** [comment]
Now I have core 2.1 but still I am getting same error message 
I have Angular 7 and Core 2.1 

Error Message : "This package has been deprecated. Use '@aspnet/signalr' instead."

Command : npm install @aspnet/signalr-client

**Comment by BrennanConroy** [comment]
> The @aspnet/signalr-client package was an alpha release

Like the error says, use `@aspnet/signalr`

**Comment by LilanSilva** [comment]
Code 2.1 compatible with @aspnet/signalr npm package and it works for me
