### ISSUE TITLE
Low level IConnection refactoring

### ISSUE THREAD

**Issue by davidfowl** [aspnet/SignalR#1475]
So far the client's internal implementation has been changed to use pipelines but we want to move to a model where the underlying connection is just a raw stream and some metadata instead of an evented reusable connection. Connection reusability will be implemented at the hub layer instead of the protocol layer. As part of this refactoring we'd also like to find a way to unify the client and server low level connection objects to enable more complex scenarios like server to server, peer to peer or proxying with extremely low overhead. This also makes it easier to unify the parsing and removes the event queue and other things from the client. 

The work was started here https://github.com/aspnet/SignalR/pull/1446 but was closed due to connection reusability problems.

Here are some related issues

- https://github.com/aspnet/SignalR/issues/1453
- https://github.com/aspnet/SignalR/issues/816
- https://github.com/aspnet/SignalR/issues/828
- https://github.com/aspnet/SignalR/issues/1450

**Comment by JamesNK** [comment]
re: https://github.com/aspnet/SignalR/issues/1633

IConnection currently exposes `SendCore(byte[] data, CancellationToken cancellationToken)`. To optimize some sending scenarios we want to write to `Output` directly. Also want to think about writing `Memory<byte>` instead of an array so we can pass a section of an existing array to be written (although if `Output` was exposed we could just use that).

**Comment by davidfowl** [comment]
@JamesNK we're going to be exposing pipes directly from the IConnection.

**Comment by anurse** [comment]
This is done!
