### ISSUE TITLE
Get active connections count

### ISSUE THREAD

**Issue by FSou1** [aspnet/SignalR#1507]
Is there a way to get active connections / clients at the current moment?

I use SignalR for broadcasting some data and do not want to do some background work in case of there are no connected clients or active connections.

Is there a proper way to handle this situation or I should manage connected users somewhere else?

**Comment by anurse** [comment]
The `OnConnectedAsync` function fires for each connection. You can count, or otherwise track, connections in there. We have no plans to expose the connections directly at this time. If you're looking to implement a user presence system, see the ChatSample in this repo which replaces the HubLifetimeManager with an implementation that allows you to track User presence: https://github.com/aspnet/SignalR/tree/dev/samples/ChatSample
