### ISSUE TITLE
HubConnection Modification to  Copying the callbacks to avoid concurrency issues

### ISSUE THREAD

**Issue by FlorianGrimm** [aspnet/SignalR#1537]
Hello
I have suggestion for HubConnection copying the invocationHandlers for each invoke.

https://github.com/FlorianGrimm/SignalR-1/blob/dev/src/Microsoft.AspNetCore.SignalR.Client.Core/HubConnection.cs

hope you like it.

**Comment by davidfowl** [comment]
Nice!

**Comment by anurse** [comment]
If you'd like to submit a code change, you'd need to open a Pull Request, rather than filing an issue and linking to the code. I know we plan to do some work on HubConnection soon though, so it might be good to wait a bit on that since we wouldn't want to refactor everything and invalidate your suggestion :).

Closing this as issues are the way we review new code suggestions. Please feel free to open a PR if you'd like to propose a change!
