### ISSUE TITLE
SocialWeather sample over TCP Sockets

### ISSUE THREAD

**Issue by KPixel** [aspnet/SignalR#1691]
In order to rewrite my [peer-to-peer sample](https://github.com/KPixel/Prototypes), I've been playing around with the Kestrel and SignalR codebases, and my observation is that neither is a good fit right now because they both focus on HTTP.

I know that the Sockets layer of SignalR is designed to support TCP (and maybe UDP) one day, so I'm working on a `Microsoft.AspNetCore.Sockets.InternetProtocol` project as proof-of-concept.

My goal for now is to get the SocialWeather sample running over TCP Sockets.

By the way, an unfortunate annoyance that I'm hitting right away is that there are naming clashes between classes meant for the Sockets layer, and classes meant to encapsulate System.Net.Sockets stuff. So, I will probably use the names "InternetProtocol" or "NetSocket" (like "WebSocket") for that.

And I don't mind that the EndPoint class will be refactored as part of aspnet/KestrelHttpServer#1980. It shouldn't change anything fundamentally.

**Comment by davidfowl** [comment]
> In order to rewrite my peer-to-peer sample, I've been playing around with the Kestrel and SignalR codebases, and my observation is that neither is a good fit right now because they both focus on HTTP.

The main focus for 2.1 is HTTP, what we've built already works for TCP (It's what Kestrel is built on top of). Can you clarify how you reached this conclusion? Is it because we have clients for HTTP only? That's a point in time problem. 

> My goal for now is to get the SocialWeather sample running over TCP Sockets.

Assuming you have a client this would be a one line change. Here's what you would do: 

https://github.com/aspnet/SignalR/blob/fd54ec2c4f9833fa10a0433917509e1bd8440180/samples/SocketsSample/Program.cs#L37

Change the above line to `UseEndPoint<SocialWeatherEndPoint>()` and you're done. 

> By the way, an unfortunate annoyance that I'm hitting right away is that there are naming clashes between classes meant for the Sockets layer, and classes meant to encapsulate System.Net.Sockets stuff. So, I will probably use the names "InternetProtocol" or "NetSocket" (like "WebSocket") for that.

Which ones? It's important to fix some of this with the rename. I know EndPoint conflicts.

**Comment by KPixel** [comment]
@davidfowl I probably wasn't clear enough. I did mean that as a point-in-time problem.
And I understand that HTTP is the focus for 2.1. I just want to see what the EndPoint/ConnectionHandler "layer" looks like with a TCP transport because it is the core API to implement custom protocols (and Kestrel doesn't use it).

It is also a good exercise for me to get a deeper understanding of these new libraries.

> Which ones? It's important to fix some of this with the rename. I know EndPoint conflicts.

I am mainly talking about all the classes with names starting with "Socket" in `Microsoft.AspNetCore.Sockets.Http` (which I'm using as a starting point). With a TCP transport, it would not be clear if that class is related to the SignalR Sockets layer or to the System.Net.Sockets namespace.
Still, this may end up not being an issue when I'm done.

**Comment by anurse** [comment]
> Reading through the code of the Microsoft.AspNetCore.Sockets.XXX.Http projects, I think they could be renamed to Microsoft.AspNetCore.Connections.XXX.Http or maybe even Microsoft.AspNetCore.Connections.Http.XXX

Way ahead of you ;P: https://github.com/aspnet/SignalR/issues/1669. We actually just decided on renames for the Socket layer earlier this week.

Keep on hackin', we're hoping to be able to put some time in on this after we've locked in the essentials for 2.1.

**Comment by davidfowl** [comment]
> @davidfowl I probably wasn't clear enough. I did mean that as a point-in-time problem.
And I understand that HTTP is the focus for 2.1. I just want to see what the EndPoint/ConnectionHandler "layer" looks like with a TCP transport because it is the core API to implement custom protocols (and Kestrel doesn't use it).

Ah! I see, Sockets won't exist anymore, in fact everything in SignalR *is* focused on Http! Kestrel is the one that exposes the TCP implementation on top of the IConnectionBuilder.

> Way ahead of you ;P: #1669. We actually just decided on renames for the Socket layer earlier this week.

> Keep on hackin', we're hoping to be able to put some time in on this after we've locked in the essentials for 2.1.

Yes, I'm doing to rename (likely next week), depending on how quickly @anurse can finish refactoring things on the client.

**Comment by KPixel** [comment]
Great!
I look forward to all this refactoring.

**Comment by davidfowl** [comment]
See https://github.com/aspnet/SignalR/pull/1696

**Comment by davidfowl** [comment]
The current renames are done for preview2, there's still a bunch of remaining work to fix some APIs for RTM though.

**Comment by KPixel** [comment]
I just got off an airplane and I'm reading all these good news :)
Thank you!

I will dig into this (and the new TCP sample) tomorrow.

**Comment by KPixel** [comment]
A lot has changed since this issue was created, so I'm closing it.

I will create a new one when I have something to share (like my [Pipelines tutorial](https://github.com/KPixel/Prototypes/tree/master/Pipelines) :) ).
