### ISSUE TITLE
'Error during WebSocket handshake: Unexpected response code: 404' when deployed in Azure App Service

### ISSUE THREAD

**Issue by poveilleux** [aspnet/SignalR#1747]
Hi,

In two different occurrences, we've had customers reporting issues with SignalR connectivity. What's bothering me with this issue is this is not happening for everybody. One of the person that has this issue has it only in one of the two datacenters. We had a similar issue in our development environment (Azure App Service with two instances) and we fixed this issue by setting the `transport` to `signalR.TransportType.WebSockets`, but this doesn't fix it in our production environments.

Thank you

Here is the information requested:
- **Server-side package:** Microsoft.AspNetCore.SignalR v1.0.0-preview2-30245
- **Client-side package:** @aspnet/signalr v1.0.0-preview2-30245
- We are using the JavaScript client.
- We are using Kestrel on Azure App Service.
- The Operating System on the Client was Windows 10 in both occurrences.
- The Browser used was Chrome for one person and Chrome *and* Edge for the other person.
- As it happened in our production environment, I didn't have the `logger` option enabled. I will enable the `logger` as soon as I can to get more details.

Additional information on the App Services configuration:
- On the two datacenters in Azure where the problem happened, we have two App Services in two different regions (i.e.: EastUS and WestUS) behind a traffic manager and have **one** instance each.
- On each of the App Services, the 'Web sockets' option is set to 'On' and the 'ARR Affinity' is set to 'Off'.
- Each of the App Services is using HTTPS.
- We use Redis cache as the backplane.

**Comment by anurse** [comment]
Could you collect network traces (instructions listed on the Issue Template: https://github.com/aspnet/SignalR/blob/dev/.github/ISSUE_TEMPLATE.md)?

Note that in order to use _non-WebSockets transports_, ARR Affinity is **required** so that Long Polling and Server-Sent Events requests can always go to the same server. However, if you are explicitly configuring the `transport` to `signalR.TransportType.WebSockets`, we do not require ARR Affinity (because the connection is uses a single duplex connection), so based on your configuration, I don not think this is the issue.

If you **are not** setting `transport` to `signalR.TransportType.WebSockets` on your production server, that is what would cause this issue. Even when we use WebSockets, if you have enabled automatic transport negotiation, we have to make two requests to initialize the server (one to get the list of supported transports, then another to actually establish the connection). It's essential that these two requests go to the same server.

**Comment by anurse** [comment]
We need some more information to diagnose this issue. Were you able to collect the network traces I suggested? Can you also provide a snippet of the client code you are using **in production** to connection to SignalR (including where you initialize the `HubConnection`)

**Comment by poveilleux** [comment]
I just understood what our problem is. We are sending the access token through the query string (`/hub?t=access_token`) and our token is too long for those users. I don't understand why our App Service returns an HTTP 404 though. Do you have any idea?

**Comment by anurse** [comment]
I'm not sure why App Service would be doing that, but it is an unfortunate side effect of being limited to the query string in WebSockets. It's likely that the query string will be the only way we can handle this in 2.1. One suggestion would be to remove some claims from your token and look up the extra data in `OnConnectionAsync` and store it in `HubConnectionContext.Items`.

**Comment by anurse** [comment]
Closing this as we understand the issue but likely aren't going to be able to prioritize it for 2.1. We are tracking some improvements to authentication in https://github.com/aspnet/SignalR/issues/1802 and can continue discussion there.

**Comment by poveilleux** [comment]
It is a default rule from IIS that kicks in and blocks the request. The default is 2048 bytes, which is about when I am getting the HTTP 404. I didn't test it yet, but I have a feeling it's going to fix it.
```xml
<configuration>
   <system.webServer>
      <security>
         <requestFiltering>
            <requestLimits maxQueryString="2048"></requestLimits>
         </requestFiltering>
      </security>
   </system.webServer>
</configuration>
``` 
Source: https://docs.microsoft.com/en-us/iis/configuration/system.webServer/security/requestFiltering/requestLimits/#configuration-sample

**Comment by poveilleux** [comment]
I confirm that by bumping up this value to a bigger number it fixed the issue for me.
