### ISSUE TITLE
Diagnose ChannelWriter performance issue with zero writes

### ISSUE THREAD

**Issue by davidfowl** [aspnet/SignalR#1811]
We should have some numbers here. This implementation isn't very optimized https://github.com/aspnet/SignalR/blob/ac5dfcf9092d4919bda392e2782c0972f4389047/src/Microsoft.AspNetCore.SignalR.Core/Internal/AsyncEnumeratorAdapters.cs#L14

**Comment by JamesNK** [comment]
FYI we have streaming micro benchmarks here - https://github.com/aspnet/SignalR/blob/dev/benchmarks/Microsoft.AspNetCore.SignalR.Microbenchmarks/DefaultHubDispatcherBenchmark.cs from https://github.com/aspnet/SignalR/pull/1574

Do you mean benchmarks captured in PowerBI?

**Comment by davidfowl** [comment]
This benchmarks calling Streaming invocations but doesn't benchmark the actual streaming part of things.

**Comment by JamesNK** [comment]
Reopened to investigate odd streaming benchmark results https://github.com/aspnet/SignalR/pull/1854#issuecomment-378850926

**Comment by JamesNK** [comment]
I'm not quite sure why there is slow performance when using `Channel<T>` without writing an item.

One item:

![image](https://user-images.githubusercontent.com/303201/38474983-aea4de82-3bf8-11e8-814d-ae6cd0492efb.png)

Zero items:

![image](https://user-images.githubusercontent.com/303201/38474987-b7cda688-3bf8-11e8-8c6d-6d7492cfb46c.png)

There is more going on in zero tiems because of an `ExceptionDispatchInfo`, but I can't find where it is being thrown from. It feels like a problem inside `Channel<T>`.

🤷‍♂️

**Comment by davidfowl** [comment]
File an issue on corefx.

/cc @stephentoub

**Comment by stephentoub** [comment]
What's the full ToString of the exception thrown in the zero case?  My off-the-cuff guess would be that, due to race conditions in the consuming code, you're seeing it hit https://github.com/aspnet/SignalR/blob/ac5dfcf9092d4919bda392e2782c0972f4389047/src/Microsoft.AspNetCore.SignalR.Core/Internal/AsyncEnumeratorAdapters.cs#L114 in the one-case and return false rather than throwing, whereas in the zero-case due to how fast it completes you're seeing it get to https://github.com/aspnet/SignalR/blob/ac5dfcf9092d4919bda392e2782c0972f4389047/src/Microsoft.AspNetCore.SignalR.Core/Internal/AsyncEnumeratorAdapters.cs#L116 and throw, which would mean the issue is actually in the check at https://github.com/aspnet/SignalR/blob/ac5dfcf9092d4919bda392e2782c0972f4389047/src/Microsoft.AspNetCore.SignalR.Core/Internal/AsyncEnumeratorAdapters.cs#L112 rather than something in corefx.

**Comment by stephentoub** [comment]
> I can't figure this out

Did you try attaching a debugger and breaking on first-chance exceptions?
Or looking at the call stack in the profile for where the ExceptionDispatchInfo.Throw is called from?

**Comment by JamesNK** [comment]
> Or looking at the call stack in the profile for where the ExceptionDispatchInfo.Throw is called from?

Unfortunately there was no information in dotTrace about where it came from.

**Comment by stephentoub** [comment]
What about attaching a debugger?
