### ISSUE TITLE
Get hub context without DI

### ISSUE THREAD

**Issue by stjephan** [aspnet/SignalR#1831]
Is there a way to get hub context without DI?

In the "old" version it was possible to get the hubcontext with:
GlobalHost.ConnectionManager.GetHubContext<MyHub>();

In the newest version I did'nt find an equal solution WITHOUT DI.

**Comment by spudcud** [comment]
I did not see a way but IMO DI is a much cleaner way to do it. What is your scenario that is making DI not work?

**Comment by stjephan** [comment]
The question is not if is clean or not. The question is only if there is a simple way. There are some discussion about it on stackoverflow, and I like to know it from "offical" source

**Comment by davidfowl** [comment]
Impossible. You need to use the DI container

**Comment by anurse** [comment]
Closing this as the question has been answered. Feel free to comment further if you need clarification on something! We can always re-open the issue if there's something to fix here.

**Comment by glittle** [comment]
I'd love to use the DI container... is there a way to access it?

**Comment by stjephan** [comment]
@glittle see https://stackoverflow.com/questions/46904678/call-signalr-core-hub-method-from-controller/46906849#46906849

**Comment by anurse** [comment]
If you really need to get the DI container from outside of a DI context, you can inject the `IServiceProvider` in to your `Configure` method and store it away on a static variable. This is basically how `GlobalHost` worked in ASP.NET SignalR, because it was the only way to do things in ASP.NET. ASP.NET Core strongly encourages you to use DI to inject things.

Where are you trying to access the DI container? If you have background services that need to access DI components, you could consider using [`IHostedService` and `BackgroundService`](https://blogs.msdn.microsoft.com/cesardelatorre/2017/11/18/implementing-background-tasks-in-microservices-with-ihostedservice-and-the-backgroundservice-class-net-core-2-x/)

**Comment by glittle** [comment]
Thanks, @anurse. I'll have to look at those. However, I doubt they'll work, since I don't think that I can just create a Hub as needed. They appear to be created and configured when they are added to the routing in the Startup file, and I don't know how to find them again.  The framework DI just magically supplies them.

**Comment by anurse** [comment]
> since I don't think that I can just create a Hub as needed.

That's correct. Creating a Hub will give you nothing useful. They are created as needed to service individual messages and disposed of after the message is processed.

> It just seems wrong to have to rely on DI when you don't need it.

I'm curious why you "don't need" DI. It would definitely help us out to know what your design is and why DI isn't working for you.

**Comment by davidfowl** [comment]
It doesn't matter, SignalR uses DI and to get things from it, you need to get the container and resolve things as well. This isn't a philosophical discussion, that's the reality, it's always been this way. The fact that the previous version of SignalR hid it from you came with some downsides (when you did change the container it would break from under you, having a global singleton is untestable).

This isn't up for debate, if you want things to work the way it did before, resolve HubContext once in the Startup class and assign it to a singleton you pass around in your libraries.

**Comment by glittle** [comment]
Thanks, @davidfowl. If I want to try the singleton method, can you point me to any sample code that does this? I haven't found an effective way to resolve a HubContext in Startup.

**Comment by davidfowl** [comment]
It's easier than that, just resolve `IHubContext<THub>` in Configure and store that in a static.

**Comment by glittle** [comment]
Knowing that `IHubContext<THub>` is available in the DI container helps. It is not clear to me how the container knows how to resolve this, since my code did not add it.  It appears that `routes.MapHub<MyHub>("/myhub")` has the undocumented(?) side-effect of registering `IHubContext<MyHub>` into the container.  Is that correct?

**Comment by anurse** [comment]
We register an open-generic `IHubContext<>` implementation in the container in `.AddSignalR` and DI knows to create instances whenever any concrete generic is requested. The implementation is created when it's requested. It's impossible to add to the container from `Configure`, so there'd be no way to register an `IHubContext` implementation that's specific to your Hub as a result of `.MapHub`.

I'm not sure what documentation you're looking for here. We certainly don't document the behavior of every single line of code :). Most ASP.NET Core components register a bunch of services in the DI container, that's why we use DI. Discussing DI and how we use it is beyond the scope of this issue though.

**Comment by glittle** [comment]
I guess just documenting how to get and use the "existing" `IHubContext` from the container from anywhere in my code would have helped.  I think I've got enough now to make progress in my project.
