### ISSUE TITLE
Diagnostic Information from ASP.NET Client Missing in ASP.NET Core Client Library

### ISSUE THREAD

**Issue by meoblast001** [aspnet/SignalR#1832]
The SignalR TypeScript client for ASP.NET (Microsoft.AspNet.SignalR) has methods which allow the user to access diagnostic information about the connection. The connection is a public member of the hub proxy and supports callbacks when events occur, such as changes to the connection or its quality. The transport method is also available. This API is unfortunately not available in the TypeScript client library in SignalR for .NET Core. After briefly looking at the implementation I've realised much of this information is already there, but it is just not summarised and exposed in the public API.

**Comment by davidfowl** [comment]
Can you be more specific?

**Comment by anurse** [comment]
> such as changes to the connection or its quality

The ASP.NET Client had "Connection Slow" events because it supported automatic reconnect. The ASP.NET Core Client does not support automatic reconnect so it only has the one event "onclose" which indicates when the connection is terminated. You can reconnect manually in there by simply restarting the connection, and tracking connection quality can be managed there.

**Comment by meoblast001** [comment]
@davidfowl Sorry about the vagueness. What I was referring to is that in the ASP.NET client, SignalR.Hub.Proxy gives access to the member `connections`, an instance of Connection. From there, the transport name can be queried, the last error that occurred, and other information about the connection. If the member `connection` of SignalR.HubConnection were public (that is, the SignalR.IConnection), some of the information would be available, but I'm not sure what other implications this may have.

@anurse This is good to know. So for that issue I'll just need to make sure I manually recreate the connections and record the current state.

**Comment by anurse** [comment]
> From there, the transport name can be queried, the last error that occurred, and other information about the connection.

Just to be clear, are you referring to the properties on [`Microsoft.AspNet.SignalR.Client.Connection`](https://msdn.microsoft.com/en-us/library/microsoft.aspnet.signalr.client.connection(v=vs.118).aspx)? We can look at which of those are appropriate and bring them forward. `LastError` was needed because of automatic reconnect, so you could see the last error that occurred. In ASP.NET Core SignalR, every error will trigger the `Closed` event, so you can simply track the current state and any errors by handling that event.

Could you provide more detail on why you would like the transport name to be available? If we were to expose that information, we'd want to know more about how you'd use it 😄 .

> manually recreate the connections and record the current state.

FYI, you shouldn't need to **recreate** the `HubConnection`. You can simply call `StartAsync` on it again. We removed the automatic reconnection because the logic wasn't appropriate in most situations and we found many apps had to add custom logic for the automatic reconnection. You can still "restart" a stopped connection, you just have to handle that yourself (and watch for things like reconnect storms, where all your clients attempt to reconnect immediately when the server comes back online).

**Comment by meoblast001** [comment]
@anurse Okay, that seems then that much of this problem is handled through the fact that automatic reconnection is gone and one could monitor much of this information during manual reconnects.

The reason I wanted to use the transport name for diagnostic information is because both the server and the client can influence what transport is used. In the event of performance problems (connection too slow) or simply connection issues which can occur if a transport is used for which the server isn't properly configured, I've found it useful to see what transport is being used and therefore print this in the application diagnostic information.

To be clear though, I'm referring to the TypeScript library and not the ASP.NET side.

**Comment by anurse** [comment]
We do already log the transport information for diagnostic purposes (or at least we should, and if we don't that's definitely a bug). If you provide an `ILoggerFactory` in your `HubConnectionBuilder` you can collect those logs.

If you need it for other diagnostic purposes we can consider exposing it. There's certainly no major reason not to, we just want to make sure we understand why people want to have access to it :).

**Comment by davidfowl** [comment]
> If you provide an ILoggerFactory in your HubConnectionBuilder you can collect those logs.

You can just add a logger provider, no need to write an entire factory.

**Comment by anurse** [comment]
> To be clear though, I'm referring to the TypeScript library and not the ASP.NET side.

Derp :).

Yeah, the logger factory stuff is in the C# client. In TypeScript we have a similar logging abstraction and we should be logging the transport used there. It's not as nicely structured as C# right now.

**Comment by aspnet-hello** [comment]
We periodically close 'discussion' issues that have not been updated in a long period of time.

We apologize if this causes any inconvenience. We ask that if you are still encountering an issue, please log a new issue with updated information and we will investigate.
