### ISSUE TITLE
camelCase vs PascalCase

### ISSUE THREAD

**Issue by samcov** [aspnet/SignalR#1844]
I have set the server to use Pascal:
services.AddSignalR(options => options.JsonSerializerSettings.ContractResolver = new DefaultContractResolver());

Why I need to tell the server to use the default is another issue, and yet another is why change class members without someone specifying that they want the change is yet another, but back to the problem.

I have a Managed Client that communicates with the server for the express purpose of sending something to the javascript client(s). The class is pulled from RavenDB and all members are in tact.

**However, when it lands on the server, it's camelCase**. It appears that the specification of serialization is not bidirectionsl, or something else is going on.

**I just want classes to be exactly the way they were designed**, otherwise the code between clients gets confusing.

Here's hoping there is an easy solution.

**Comment by anurse** [comment]
> Why I need to tell the server to use the default is another issue

The default is designed to match the behavior of ASP.NET SignalR. It was also the overwhelming request of users because it made the client code match the JavaScript style. The config is there to let you bypass that default, as you discovered.

> However, when it lands on the server, it's camelCase.

I'm curious what you mean when you say you are seeing `camelCase` on the server. It should be bound to whatever .NET type you accept in your hub method, and if that type uses PascalCase properties, it should bind (assuming you aren't using MessagePack, as there's a known issue there: #1565). Can you provide an example of where your binding is failing?

**Comment by anurse** [comment]
Can you show the code for the method that is getting camelCase data? Are you binding to an object? To a dictionary?

**Comment by anurse** [comment]
Can you show the code for the method that is getting camelCase data? Are you binding to an object? To a dictionary?

**Comment by anurse** [comment]
Ok, so you're binding to an arbitrary object? In that case, yes, it preserves the casing of what was provided by the client, because there is nothing to bind against. If you want you can configure the serializer on the client to use PascalCase instead of camelCase as well by adding `.WithHubProtocol` to your `HubConnectionBuilder` call:

```csharp
var connection = new HubConnectionBuilder()
    .WithUrl(...)
    .WithHubProtocol(new JsonHubProtocol(Options.Create(new JsonHubProtocolOptions() {
        PayloadSerializerSettings = new JsonSerializerSettings() {
            // Configure as you'd like here
        }
    })));
```

Note: This syntax will be improving dramatically **after** the preview2 release (you can see in the current nightly builds).

**Comment by samcov** [comment]
Thanks, I'll try that and then close this issue.

**Comment by samcov** [comment]
I can resolve everything except for "JsonHubProtocolOptions", where is that located?

**Comment by anurse** [comment]
It's in Microsoft.AspNetCore.SignalR. Same assembly as `JsonHubProtocol`. So if you can resolve that, you should be able to resolve the options type.

**Comment by anurse** [comment]
Ah, are you using preview 1? Hang on a sec, things might be different there.

**Comment by samcov** [comment]
Actually I'm using 1.00 Alpha 2 final.

Are there many breaking changes to move to preview 1?

**Comment by samcov** [comment]
Ok, I moved totally to preview 1, and the breaking changes were pretty massive rippling through almost everything, but it went well.

Configuring the managed client makes things work, and case is maintained.

BTW, I also had to change serializer code in services.AddSignalR, but fortunately, you gave me the correct code earlier in another issue.

You guys are making very good progress, thanks a lot!

**Comment by anurse** [comment]
Cool. I'm going to close this issue then, since it sounds like you've resolved your issue.
