### ISSUE TITLE
Proposal: Browser lock or screen turn-off for iOS connect/disconnect should be handled automatically

### ISSUE THREAD

**Issue by ivankarpey** [aspnet/SignalR#1846]
There is currently a little nasty situation happen in iOS platform with connection drop when user switch app or just locking his phone and no reconnect happen on page become active again. Surely there is some workaround to deal with it, but I think it will be much better if this will be implemented on a framework level.

**Comment by anurse** [comment]
ASP.NET SignalR did automatically hook an event to disconnect when the page was unloaded, but didn't do anything to handle page visibility issues like this or network change. It does sound like an interesting place to improve the framework, but I don't expect we'll have the capacity to do it in the initial release.

We'd probably have to depend on the browser supporting APIs like the [Page Visibility API](https://developer.mozilla.org/en-US/docs/Web/API/Page_Visibility_API) and [Network Information API](https://developer.mozilla.org/en-US/docs/Web/API/Network_Information_API).

You should be able to achieve something like this by hooking those APIs and manually stopping/restarting the connection. If you find some interesting patterns there, please do let us know! We'll be looking to figure out how people are achieving this when it does come to implementing something like this.

**Comment by stajs** [comment]
I'm unsure if the issue (iOS app suspension severing connections) should be addressed in the framework. Having said that, we rolled an Angular service for visibility for that exact reason. Here is an untested reduced version for the basic idea:

```typescript
import { Injectable } from '@angular/core';
import { EventManager } from '@angular/platform-browser';
import { Subject } from 'rxjs/Subject';
import { Observable } from 'rxjs/Observable';

@Injectable()
export class VisibilityService {
   visibilityConfirmed = new Subject<void>();

   constructor(private eventManager: EventManager) {
      if ('hidden' in document) {
         // For recent browsers that support Page Visibility API, this fires both when visible and when hidden.
         eventManager.addGlobalEventListener('document', 'visibilitychange', event => this.onChange(event));
      } else {
         // TODO: Degraded experience warning.
         console.warn('Page Visibility API is not supported.');
      }
   }

   private onChange(event: any) {
      // You probably only care when it becomes visible.
      if (document.visibilityState === 'visible') {
         this.visibilityConfirmed.next();
      }
   }
}
```

We generalized to a service because we also refresh data through Web API calls, not just SignalR.

My unsureness derives from a potentially misunderstood design direction: clients need to plan for and handle disconnections. In our SignalR service, we also handle disconnections with a retry every 5 seconds (again untested/reduced):

```typescript
private setupConnectionManagement(connection: HubConnection, hub: SignalRHub) {
   connection.onclose((error: any) => {
      console.warn('Disconnected', error);
      setTimeout(() => {
         console.log('Retry connection');
         this.initialiseConnection(hub);
      }, 5000);
   });
}
```

IIRC, this was working on iOS devices so the question might become: how long is an acceptable delay in the browser being reactivated and SignalR connecting?

PS, UWP apps can also be suspended/terminated.

**Comment by Nivitha-Gopalakrishnan** [comment]
I am using SignalR in Asp.Net Core 2.0 with typescript. I am also facing this issue in IOS operating system, but its works fine in other operating systems. Is there any workaround to work with this in typescript meanwhile?

**Comment by bradygaster** [comment]
This is something we discussed and we think is better handled by application code.
