### ISSUE TITLE
Review unbounded channel usage in observable stream return scenario

### ISSUE THREAD

**Issue by davidfowl** [aspnet/SignalR#1864]
Today we adapt the `IObservable<T>` return type into an unbounded channel internally to write messages to the client. This means the Observer will never experience back pressure if the client backs up, memory will just grow forever. We need to consider either using a bounded channel here, or changing the approach to properly flow back pressure from the client to the observer.

https://github.com/aspnet/SignalR/blob/61c3d0c4030033013d4ad155d0f284aba384070a/src/Microsoft.AspNetCore.SignalR.Core/Internal/AsyncEnumeratorAdapters.cs#L17

https://github.com/aspnet/SignalR/blob/61c3d0c4030033013d4ad155d0f284aba384070a/src/Microsoft.AspNetCore.SignalR.Core/Internal/AsyncEnumeratorAdapters.cs#L57-L63

**Comment by anurse** [comment]
The thing is, what would we do if the buffer is full? Synchronously block?

**Comment by anurse** [comment]
My thought is that if you want back-pressure to prevent you from gobbling up memory, use a Channel and you can configure your buffering.

**Comment by davidfowl** [comment]
> The thing is, what would we do if the buffer is full? Synchronously block?

Yes. Block hard.

**Comment by anurse** [comment]
I mean, we can do that, but it's a big cannon to point at people's feet. So are unbuffered channels. Backpressure seems to be a pretty [hot](https://github.com/ReactiveX/RxJava/wiki/Backpressure) issue in [RxLand](https://github.com/Reactive-Extensions/Rx.NET/issues/19).

My concern is that `IObservable` is going to seem like the "easy" way to do streaming (since `Channel<T>` is so new) and people are going to flock to that rather than the more appropriate Channel API.

I think we need some people with more Rxperience to chime in here.

**Comment by davidfowl** [comment]
We're going to remove Rx.
