### ISSUE TITLE
Do you support master and slave switching with redis ?

### ISSUE THREAD

**Issue by sean19941103** [aspnet/SignalR#1912]

**Comment by davidfowl** [comment]
We haven't explicit tested with redis setup in this configuration but we only use redis pubsub, not the redis database. The library we're using for redis should reconnect in the event of failure but I don't know enough details here.

/cc @mgravell

**Comment by sean19941103** [comment]
@davidfowl If redis fails, even if the connection is reconnected, publish and subscribe cannot be used. Is it only manual failover?

**Comment by davidfowl** [comment]
> @davidfowl If redis fails, even if the connection is reconnected, publish and subscribe cannot be used.

I believe the library we're using resubscribes to subscriptions redis after reconnecting.

> Is it only manual failover?

Not sure what you mean by manual?

**Comment by sean19941103** [comment]
@davidfowl  I want to use multiple redis instances to achieve automatic failover. sorry, my english is not good.

**Comment by davidfowl** [comment]
Redis pubsub is a bit different. All of the state is per connection. When that connection dies, so do the subscriptions. Once the client reconnects to the appropriate server (based on the configuration) and it should just work.

Here's more on the library we're using https://stackexchange.github.io/StackExchange.Redis/Basics. It describes how to configure to use a master slave configuration.

**Comment by mgravell** [comment]
Master/slave swaps are a PITA because there is no inbuilt "config has changed, please recheck" event built into redis. We cheat by inventing one out of raw cloth, but that only gets raised by our own lib. Thank you for reminding me - something else to mention at redisconf in a few weeks!

In general: yes, the lib should attempt to resubscribe if sockets break. And it *should* survive master/slave swaps *if it knows about them*. If you're seeing a specific failure, let me know and we can take a look.

**Comment by anurse** [comment]
Closing this as the question has been answered. Feel free to comment further if you need clarification on something! We can always re-open the issue if there's something to fix here.
