### ISSUE TITLE
API review TS client

### ISSUE THREAD

**Issue by JamesNK** [aspnet/SignalR#1963]
Should review what the TS client makes public.

**Comment by anurse** [comment]
Turns out many of the things we thought were exported were not and I was just not using the tool right (or the tool doesn't support what I was doing.

From Chrome Dev Tools looking at the actual `signalR` namespace:

![image](https://user-images.githubusercontent.com/7574/38838831-e5e1fddc-418c-11e8-8987-690b15cee6e0.png)

**Comment by anurse** [comment]
This is all done now.
