### ISSUE TITLE
missing: Microsoft.AspNet.SignalR.PersistentConnection

### ISSUE THREAD

**Issue by Bartolomeus-649** [aspnet/SignalR#2025]
What is the name/location of this class: Microsoft.AspNet.SignalR.PersistentConnection here in  Microsoft.AspNetCore.SignalR?

If it doesn't exist, then, how do you migrate a solution based on PersistentConnection?  What is the equivalent class in Microsoft.AspNetCore.SignalR?

**Comment by davidfowl** [comment]
The model has changed significantly. There’s something called a ConnectionHandler but it’s not the same as a persistent connection. The big difference is that it’s stream based instead of message based so you need to deal with parsing and sending batches of messages. Which means you need to invent some way to parse individual “frames”. This can be trivially done with a separator char for text based protocols and length prefixing for binary

**Comment by anurse** [comment]
Closing this as the question has been answered. Feel free to comment further if you need clarification on something! We can always re-open the issue if there's something to fix here.
