### ISSUE TITLE
how to set HttpConnectionContext.ActiveFormat =  TransferFormat.Binary

### ISSUE THREAD

**Issue by chenhongyi** [aspnet/SignalR#2159]
### Please consider the following before filing an issue

Help me!  how to set HttpConnectionContext.ActiveFormat =  TransferFormat.Binary,
In Microsoft.AspNetCore.Http.Connections,and the version is 1.0.0-preview2-final

I used ConnectionHandler create a websocket server, and need to send msg to client by binary data,so i don't know how to set this.

**Comment by JamesNK** [comment]
The transfer format depends on the protocol the connection is using. SignalR comes with two protocols: json and message pack. The json protocol uses text and message pack uses binary. If you configure the client and server to use message pack then `ActiveFormat` for will be `Binary`.

Note that you can still send binary data over JSON, it will just be less efficient because the binary data will be base64 encoded.

**Comment by davidfowl** [comment]
You can set the tranfer format by getting the ITransferFormatFeature and you can set the active format through it. Example https://github.com/aspnet/SignalR/blob/1.0.0-preview2-final/src/Microsoft.AspNetCore.SignalR.Core/HubConnectionContext.cs#L280

**Comment by chenhongyi** [comment]
Thanks ,I will try it.

**Comment by anurse** [comment]
Closing this as the question has been answered. Feel free to comment further if you need clarification on something! We can always re-open the issue if there's something to fix here.
