### ISSUE TITLE
Recommended usage right now?

### ISSUE THREAD

**Issue by prom3theu5** [aspnet/SignalR#217]
I've been using a version compiled from last year in production and have been seeing random 502's which lock up the entire site which I believe is down to SignalR

I realise that it's completely unsupported for production right now, so would I be right in thinking my best course of action (As I want to use signalr and not crossbar or a websockets implementation, as when signalr is ready I will 100% be using it) would be to self host 2.2.1 in a 4.6 console app with owin + cors, then just set the $.connection.hub.url explicitly to that in all my js files before $.connection.start() is called?

**Comment by moozzyk** [comment]
The version you were using does not exist anymore and never was supported.

With regards to selfhosting and 2.x - you can serve static files from your serlfhosted console application and if you serve an html page that contains signalr client you won't have to set url or anything because the url to the SignalR server will be the same as the one that served the file. 
If you want to serve files from an actual web server but run a separate selfhosted SignalR server you can just follow this doc: https://docs.microsoft.com/en-us/aspnet/signalr/overview/deployment/tutorial-signalr-self-host, The important part is that setting url is not enough - you also need to enable CORS.

**Comment by prom3theu5** [comment]
Aye thanks for that.
I won't be hosting static files directly as thats already handled with the .Net Core 1.1 site running in IIS.
I basically need a "MITM" approach so I can use a production stable SignalR for the time being, so I plan to "rip" the version that no longer exists out of the .Net Core, move the Hubs the console app, and have that in the middle of the site and program which were previously communicating with each other, effectively creating a broker service
