### ISSUE TITLE
@aspnet/signalr not working IE11

### ISSUE THREAD

**Issue by camco-ine** [aspnet/SignalR#2296]
### Please include as much of the following as you can in your bug report

* Versions of Client-Side NuGet/NPM Packages:
```
 "@angular/animations": "^5.1",
    "@angular/common": "^5.1",
    "@angular/core": "^5.1",
    "@angular/forms": "^5.2.4",
    "@angular/platform-browser": "^5.1",
    "@angular/platform-browser-dynamic": "^5.1",
    "@angular/router": "^5.2.9",
    "@aspnet/signalr": "^1.0.0-preview2-final",
    "@camco/common": "^1.0.0",
    "@turf/turf": "^5.1.6",
    "@types/d3": "^5.0.0",
    "@types/materialize-css": "^1.0.1",
    "@types/ol": "^4.6.1",
    "core-js": "^2.5.3",
    "d3": "^5.0.0",
    "keysim": "^2.0.0",
    "materialize-css": "1.0.0-alpha.4",
    "ol": "^4.6.4",
    "rxjs": "^5.5.6",
    "zone.js": "^0.8.20"
```
* Are you using the C# client or the JavaScript client:
javascript client
* The Server you are using (Kestrel/HttpSysServer/IIS/IIS Express/Azure Web App/etc.): 
Kestrel
* The Operating System on the Server (Windows/Linux/macOS):
Windows
* The Operating System on the Client (Windows/Linux/macOS):
Windows
* The Browser on the client, if using the JavaScript client (IE/Chrome/Edge/Firefox/etc.):
IE

While developing an application using the Angular CLI (version 5), the application does not seem to start in Internet Explorer while working perfectly fine in Firefox and Chrome.
When attempting to run the application in Internet Explorer 11 after including `@aspnet/signalr` throws a syntax error (see screenshots below):
![angular-issue-devtools](https://user-images.githubusercontent.com/39370794/40171563-e4b2744e-59cb-11e8-9f69-ff4280017029.PNG)
![angular-issue-code](https://user-images.githubusercontent.com/39370794/40171564-e4d3dab2-59cb-11e8-9623-2854d0803d6a.PNG)

The code used to include SignalR is shown below:
```typescript
import { HubConnection } from '@aspnet/signalr';

export class Hub {

	protected connection: HubConnection;

	constructor(url: string) {
		this.connection = new HubConnection(url);
	}

	public connect(reconnect: () => void, onConnectionSucces: () => void, setConnected: (connected: boolean) => void, retry: number) {
		this.connection.onclose(() => {
			setConnected(false);
			setTimeout(reconnect, retry);
		});

		this.connection.start()
			.then(() => {
				onConnectionSucces();
				setConnected(true);
			})
			.catch(() => {
				setConnected(false);
				setTimeout(reconnect, retry);
			});
	}

	protected on(eventName: string, callback: (...msg: any[]) => void) {
		this.connection.on(eventName, callback);
	}
}

```

**Comment by BrennanConroy** [comment]
Try upgrading to rc1 or later

**Comment by anurse** [comment]
IE 11 requires using the ECMAScript 5 build. In Preview 2, the "module" version (which you are using via `import`) required ECMAScript 6. In RC1 we made all builds of the package ES5.

**Comment by dealloc** [comment]
Is there a way to switch to the ES5 build on preview 2 without upgrading to the RC1 build, which also requires upgrading the .NET framework etc (which is currently not exactly a viable option for me)?

**Comment by davidfowl** [comment]
@dealloc staying on preview2 isn't a viable option either. I'm not sure what you're expecting here. What's your actual plan to get bug fixes past preview2 there are *LOTS* of them?

**Comment by camco-ine** [comment]
We don't want to upgrade our back-end at the moment, this would mean we need to upgrade multiple projects and we did this just last month. Our plan is to upgrade when we have more time. How do you use the ES5 build for preview2?

**Comment by anurse** [comment]
I'm going to close this issue as there isn't something to fix for our next release (since our most recent release supports IE 11 fully). We can continue discussing things in this issue, I just want to make sure our issue tracking is up-to-date.

You can reference the ES5 version directly from an ECMAScript/TypeScript Module using this syntax: `import { ... } from "@aspnet/signalr/dist/browser/signalr"`.

As @davidfowl indicated though, this is definitely not a viable option in **any** production deployment. There are many issues in Preview 2 that were fixed in RC1. Upgrading should be as simple as updating package versions, and if it's more complicated than that, we'd love to hear about any issues you're hitting!

**Comment by dealloc** [comment]
Understandable; it's not for production at the moment we're in the stage of building a POC and updating the versions every couple days isn't really boosting productivity :)

Though I don't think it'll be as simple as simply updating a package since I'm assuming the backend would need to be updated as well and if SignalR versioning is following the .NET versioning that would mean we have to retarget to the newer .NET versions and update the backend, which is obviously a lot more work than "just" updating a NPM package.

If I'm wrong in assuming so however, and it's really just updating the NPM package then please do correct me :)

**Comment by davidfowl** [comment]
Every couple of days? The rc1 build just came out and this is one of the issues we fixed. 

You need to update both server and client to rc1 of asp.net Core. If that’s too much for your POC then maybe you should wait for the RTM since there are other known bugs that might bite you.

**Comment by davidfowl** [comment]
Also, the APIs have changed between preview2 and the rc so you’ll need to account for that too.
