### ISSUE TITLE
Identity Cookie Auth via Javascript Client (Electronjs client)

### ISSUE THREAD

**Issue by Banashek** [aspnet/SignalR#2381]
### Please consider the following before filing an issue

* If you are using NuGet Packages that start with `Microsoft.AspNet.SignalR`, use the issue tracker at https://github.com/SignalR/SignalR to report the issue. This 
repository is for packages that start with `Microsoft.AspNetCore.SignalR` (and NPM packages that start with `@aspnet/signalr`)

### Please include as much of the following as you can in your bug report

* Versions of Server-Side NuGet Packages: **2.1.0-rc1-final**
* Versions of Client-Side NuGet/NPM Packages: **^1.0.0-rc1-update1**
* Are you using the C# client or the JavaScript client: **Javascript Client**
* The Server you are using (Kestrel/HttpSysServer/IIS/IIS Express/Azure Web App/etc.): **IIS Express**
* The Operating System on the Server (Windows/Linux/macOS): **Windows**
* The Operating System on the Client (Windows/Linux/macOS): **Windows**
* The Browser on the client, if using the JavaScript client (IE/Chrome/Edge/Firefox/etc.): **Chrome (Electron)**
* Please use the Diagnostics Guide at https://github.com/aspnet/SignalR/wiki/Diagnostics-Guide to collect server-side and client-side logs and network traces if possible. Please **do not** put the traces and logs in the Issue text as they are quite large. The Diagnostics Guide describes how to attach them to the issue.

When in doubt, feel free to file the issue, we're happy to help answer questions. We also suggest using the `asp.net-core-signalr` tag on StackOverflow to ask questions.

## Description
I've got a basic chathub example set up on the server-side, except it has an `[Authorize]` attribute on it so I can restrict it to logged in users.

The client is an Electron application. It creates a browser window to the local site. The user logs in, and when the Electron app detects that the `'.AspNetCore.Identity.Application'` has been set, it attempts to initialize a session from the main electron process.

The issue lies in that the main electron process doesn't automatically send the Identity cookie, and there doesn't seem to be a way to add one to a request (the actual request is buried underneath a bit of abstraction, and [the headers sent](https://github.com/aspnet/SignalR/blob/dev/clients/ts/signalr/src/IHubProtocol.ts#L26) don't seem configurable without heavily modifying the library.

Is there a recommended approach for what is essentially a node client to add an identity cookie?

**Comment by anurse** [comment]
We don't have a great Node story quite yet, we focused on Browsers in the first release but did our best to make it **possible** to use Node, even if it's not simple 😉. We have #2301 filed to track work on making this better in the next release.

The first thing you have to provide in Node is an implementation of our `HttpClient` abstract base class. We provide a default implementation that uses `XMLHttpRequest`, so in theory if your Node environment has that object available, it should work, but configuring it is up to you.

If you just want to get something working right now, I think the best approach would be to start by implementing a custom `HttpClient`. You can use Node's HTTP client APIs to implement it and implement whatever cookie logic you need :).

Here's a brief TypeScript example of configuring an using a custom `HttpClient`:

```typescript
import { HttpClient, HubConnectionBuilder, HttpRequest } from "@aspnet/signalR"

export class NodeHttpClient extends HttpClient {
    public send(request: HttpRequest): Promise<HttpResponse> {
        // Send the HTTP request using the Node APIs here!
    }
}
```

See [`DefaultHttpClient`](https://github.com/aspnet/SignalR/blob/b8bb75d592a1a24ac9e23fe52abd56f9198a2a25/clients/ts/signalr/src/HttpClient.ts#L149) for an example, it's the code that implements our default logic using XMLHttpRequest in browsers.

If you want to use WebSockets, you're going to also need to provide polyfills for that which mimic the browser APIs (which also means they have to be installed onto the global object rather than imported as modules). We're also planning to improve that moving forward.

Once you've got a custom `HttpClient` implementation, and optionally a polyfill for `WebSocket`, you can set everything up using code like this:

```typescript
// if you are using a WebSocket polyfill like https://github.com/websockets/ws
// you need to "install" it into the global scope like this
global.WebSocket = require("ws");

const connection = new HubConnectionBuilder()
    .withUrl("/myhub", { httpClient: new NodeHttpClient() })
    .build();
```

**Comment by Banashek** [comment]
Ah it was the optional httpclient builder parameter I was looking for.

Thanks!

Yeah completely makes sense that browsers are targeted first. The application has been working so far with regular websockets, but figured I'd give the transition to SignalR a shot.

Keep up the good work.
