### ISSUE TITLE
Send AccessToken via JS (Angular) Client for [Authorize] protected hub

### ISSUE THREAD

**Issue by mhosman** [aspnet/SignalR#2425]
There is no good documentation about this. From my client (in Angular), all the requests to the API (in .NET Core) are done with header "Authorization" : "JWT xxxxxxxxxxxxxxxxxxxxxx".

How can I pass this JWT from JS to connect to a HUB with [Authorize] tag?

**Comment by mhosman** [comment]
I'm not able to set JWT parameter in Headers from SignalR JS Client.
The only way is to pass the token through the URL?

In that case I just added this:

```
app.Use(async (_context, next) =>
            {
                if (_context.Request.Query.TryGetValue("access_token", out var token))
                {
                    _context.Request.Headers.Add("Authorization", $"Bearer {token}");
                }
                await next.Invoke();
            });
```

There is a better approach?

**Comment by anurse** [comment]
You should just use the `accessTokenFactory` option in the JavaScript client to specify the token:

```javascript
function getAccessToken() {
    let accessToken = /* generate token */
    return accessToken;
}

let connection = new signalR.HubConnectionBuilder()
    .withUrl("...", { accessTokenFactory: getAccessToken() })
    .build();
```

The browser APIs only allow us to add query string values when using WebSockets or Server-Sent Events, so you also need to configure the server to read from the `access_token` query string value. See https://github.com/aspnet/SignalR/blob/dev/samples/JwtSample/Startup.cs#L35 for an example.

**Comment by korenb** [comment]
> The browser APIs only allow us to add query string values when using WebSockets or Server-Sent Events
Is any explanation why the browsers don't allow us that? what reasons?

**Comment by korenb** [comment]
by the way, having `ws://localhost:5000/im?access_token=eyJhbGci...` url, the IsWebSocketRequest value is always equals `false`.

so instead of condition
`if (!string.IsNullOrEmpty(accessToken) && 
                     (context.HttpContext.WebSockets.IsWebSocketRequest || context.Request.Headers["Accept"] == "text/event-stream"))`
the following worked for me
`if (!string.IsNullOrEmpty(accessToken) && context.Request.Headers["Upgrade"] == "websocket")`

**Comment by anurse** [comment]
> Is there any explanation why the browsers don't allow us that? what reasons?

The primary reason is because WebSockets don't adhere to the same-origin policy that AJAX requests do. In a browser, you can only send HTTP requests to URLs where the domain matches the page you are on. [CORS](https://developer.mozilla.org/en-US/docs/Web/HTTP/CORS) is a protocol that allows a server to allow cross-origin requests, but WebSockets does not support that due to the fact that they were developed separately. But regardless of the history, it's a browser decision and we're limited by it.

> by the way, having ws://localhost:5000/im?access_token=eyJhbGci... url, the IsWebSocketRequest value is always equals false.

Can you provide the code from your `Configure` method? This would indicate that the WebSocket middleware (which is added by `UseSignalR`) ran **after** your authentication code instead of before it, since it's that middleware that sets the IsWebSocketRequest property.

**Comment by korenb** [comment]
> @anurse Can you provide the code from your Configure method? 

```
app.UseCors("one-policy");
app.UseAuthentication();
app.UseHubs();
app.UseMvc();
```

`UseHubs` is extension method for configuring SignalR like: 
```
app.UseSignalR(routes =>
{
    routes.MapHub<ChatHub>("/im");
});
```

**Comment by anurse** [comment]
Try adding `app.UseWebSockets` above the `UseAuthentication` call. The WebSocket middleware is the one that makes `IsWebSocketRequest` work, so it needs to be above where your authentication runs. If you're using the Authentication middleware, then it has to be before of it. SignalR loads the WebSocket middleware for you in `UseSignalR` (immediately before the SignalR middleware itself), but it's harmless to do it manually earlier in the pipeline. So you would do something like this:

```csharp
app.UseCors("one-policy");
app.UseWebSockets();
app.UseAuthentication();
app.UseHubs();
app.UseMvc();
```

One thing to keep in mind is that I don't believe the Authentication middleware is **required** if you're just doing SignalR and MVC authentication via the `Authorize` attribute. The core logic is provided by the Authentication services in DI (which you added in `ConfigureServices`). SignalR and MVC will activate authentication themselves in order to authenticate requests. The middleware is primarily there to handle OAuth landing pages (i.e. when the OAuth provider redirects back to your site). If you removed the middleware, then authentication would be first activated by SignalR or MVC, both of which come after SignalR has already registered the WebSocket middleware. Obviously if you do remove it, you should test all your security-related scenarios to make sure I'm correctly interpreting your scenario :). (cc @Tratcher)

**Comment by Tratcher** [comment]
Yeah, if you're only using Bearer then UseAuthentication is somewhat optional. Might as well keep it though.
