### ISSUE TITLE
Behavior of "On" is inconsistent when multiple handlers are registered for the same method name

### ISSUE THREAD

**Issue by icistrate** [aspnet/SignalR#2429]
Edit by @anurse: I renamed the title to be a little clearer on the issue we're investigating here. The old title was "Is it true that 'Dispatch' method name is not allowed when defining a IClientProxy?"

The issue now is that the behavior appears to be different when `.On` is called in a different order given the same method name, when the generic argument provided to `.On<T>` is different (but one inherits from the other). Example: https://gist.github.com/anurse/07c31162cdf0fd201bc18f9bb973619e

The report is that the order of the `On` methods in the example changes the behavior. When the more-derived type (`AccountMessage`) is registered first, **both** handlers are called (this is the expected behavior) but when the less-derived type (`Message`) is registered first, only the one is called.

Original content follows

----

Hi,

I have a `Hub<IServerToClient>` where `IServerToClient`:
 
```
    public interface IServerToClient
    {
    Task Dispatch<T>(T message) where T : IMessage;
    Task Dispatch(string message);
    }
```

If I try to call this `Dispatch` method anywhere in the hub, eg `this.Clients.All.Dispatch("message")`, it does not get fired on clients side (my client is C# client). It works when I rename the method to `DispatchX` for example.
So, is it true that `Dispatch` method name is not allowed when defining a `IClientProxy`?  Is this some kind of keyword?

Well, I realized that `S2C_Dispatch` or `Send` behaves the same way.. hopefully I find one available synonym that I could use for this method name..

Is there a list of names to avoid?

**Comment by anurse** [comment]
> multiple handlers on same method name

Yeah, SignalR doesn't support overloading because it doesn't know what kind of types were used by the caller (since we support .NET, JavaScript and other clients), so when you have two handlers for the same method name, they should both be called.

> no handler could be invoked either.

This is surprising to me. If you call `.On` twice with the same name on the client it should register two handlers for the same method. Would you be able to provide an example project that reproduces the issue you're seeing? I want to make sure the behavior is clear. If you can provide an example project and describe what you'd expect to happen compared to what actually happens that would help identify if there's a problem in documentation or a problem in the code :)

**Comment by icistrate** [comment]
I realized I had this behavior due to a (probably) invalid handler (note the `IMessage`, instead of `Message`):
```
    _hubConnection.On<IMessage>("Dispatch", (msg) =>
    {
    Console.WriteLine($"Received Message: msg.Description}");
    });
    _hubConnection.On<MyMessage>("Dispatch", (msg) =>
    {
    Console.WriteLine($"Received MyMessage: msg.Description}");
    });
```
Btw, do you have some samples of how to use such inheritance on Messages with SignalR

**Comment by icistrate** [comment]
Well, I find it very strange that after changing `IMessage` to `Message` in the first handler... the second handler is not getting called for some reason.

To have it clear, `MyMessage` derives from `Message`

**Comment by anurse** [comment]
> Btw, do you have some samples of how to use such inheritance on Messages with SignalR

I wouldn't recommend using SignalR directly to handle the inheritance. Since we serialize the JSON and back, the only way to accurately represent the specific type of the instance is to encode it in the JSON, which a) gets ugly fast and b) opens a security risk if not done **extremely carefully**.

Instead, I would suggest that you consider using an enum or some other value to indicate the kind of the message. If you need to send different payloads for different message types, I'd suggest defining a different method on the client for each.

> Well, I find it very strange that after changing IMessage to Message in the first handler... the second handler is not getting called for some reason.

That is odd and shouldn't be the case. Would you be able to put an example project up on GitHub? That will make it really easy for us to identify if there's an issue there.

**Comment by icistrate** [comment]
@anurse 
Ok, I will attach my test client code here.. the server is just echoing back the original message
[Program.zip](https://github.com/aspnet/SignalR/files/2079796/Program.zip)

I just noticed that I get different behavior based on the order of the handlers. Is that possible?

So, when I have `On<Message>`, `On<MyMessage>` order .. only one of them gets called.. but when I have `On<MyMessage>`, `On<Message>` order, then both get called

**Comment by BrennanConroy** [comment]
Found the reason you are getting inconsistent behavior.
https://github.com/aspnet/SignalR/blob/e41764c161574983c49362cfb29ce23eb5941b74/src/Microsoft.AspNetCore.SignalR.Client.Core/HubConnection.cs#L1241

I'm not sure we'll make any changes here, we'll discuss it

**Comment by anurse** [comment]
Yeah, `On` is not designed to be used with handlers that take different types. Attaching multiple handlers to a method is an extremely uncommon scenario. In general, SignalR **does not** support overloading (having multiple methods with the same name but different parameter types).

As @BrennanConroy noticed, this behavior is consistent with our design, so I'm going to re-close this issue. Happy to continue to help you find the right pattern for your application though, so feel free to keep commenting!

**Comment by 009topersky** [comment]
Good day Sir!

Im having a trouble implementing the SignalR on my Ionic 3 Application

the behavior is something like this
- I Implemented it on my Web app , and its working fine and good

here is the issue
- I try implementing the SignalR on my Ionic 3 Project , and same way with the WEB, later on when the

`.on(instanceName, data => {
  // some codes here
});`

- inside the functions, it triggers 2x or 3x on my client part

is there any way i can see the error?

**Comment by anurse** [comment]
How are you invoking the method on the client? Are you using `Clients.Group` or `Clients.Groups`?
