### ISSUE TITLE
CORS with browser code

### ISSUE THREAD

**Issue by knownAsKyle** [aspnet/SignalR#2433]
pulling the latest from @aspnet/signalr gives me browser side code that doesn't allow cross origin requests regardless of the server settings.  It looks like the 'withCredentials' setting is hard coded to true with no obvious way to override it (via some external setting).  I know this use to be an option that you could set - is this a bug or is it truly intended to not allow calls 'withCredentials' set to false?

**Comment by BrennanConroy** [comment]
The server needs to have `AllowCredentials()` on the policy

**Comment by anurse** [comment]
> It looks like the 'withCredentials' setting is hard coded to true with no obvious way to override it

This is required in order to have the client send cookies to the server when doing cross-origin requests. Since SignalR requires sticky sessions (like "ARR Affinity" on Azure), and those are usually implemented with cookies, this setting is mandatory.

We do have [some reference to CORS policy](https://docs.microsoft.com/en-us/aspnet/core/signalr/get-started?view=aspnetcore-2.1&tabs=visual-studio#configure-the-project-to-use-signalr) in our docs, but it's not really clear, so I'm tagging this issue for us to follow up on and improve our docs here.

**Comment by anurse** [comment]
https://github.com/aspnet/Docs/issues/6078 was filed a while ago for this. Closing this issue.
