### ISSUE TITLE
Authenticate a .NET Core 2.1 SignalR console to web app using "Identity as UI"

### ISSUE THREAD

**Issue by kofifus** [aspnet/SignalR#2455]
Using .NET Core 2.1 & VS2017 preview 2 I created a simple web server with "Identity as UI" as explained [here][2] and then added a SignalR chat following [this][1]. 

  [1]: https://docs.microsoft.com/en-us/aspnet/core/signalr/hubs?view=aspnetcore-2.1
  [2]: http://www.talkingdotnet.com/how-to-scaffold-identity-ui-in-asp-net-core-2-1/

In particular I have:

```
app.UseAuthentication();
app.UseSignalR((options) => {
	options.MapHub<MyHub>("/hubs/myhub");
});

..

[Authorize]
public class MyHub : Hub

..

"iisSettings": {
  "windowsAuthentication": false,
  "anonymousAuthentication": true,
     "iisExpress": {
     "applicationUrl": "http://localhost:5000",
     "sslPort": 0
```

I start the debugger which brings the browser, register a user and log in, then go to http://localhost:5000/SignalRtest (my razor page that uses signalr.js) and verify the chat works fine.

I now try to create a .NET Core console app chat client:

```
class Program
{
	public static async Task SetupSignalRHubAsync()
	{
		var hubConnection = new HubConnectionBuilder()
					.WithUrl("http://localhost:5000/hubs/myhub")
					.Build();

		await hubConnection.StartAsync();
		await hubConnection.SendAsync("Send", "consoleapp");
	}

	public static void Main(string[] args)
	{
		SetupSignalRHubAsync().Wait();
	}
}
```

My issue is I don't know how to authenticate this client ?

Looking at some posts I tried:

```
private static async Task<string> GetAccessTokenViaOwnerPasswordAsync()
{
	try
	{
		// discover endpoints from metadata
		var discoveryClient = new DiscoveryClient("http://localhost:5000");
		discoveryClient.Policy.RequireHttps = false;
		var discoveryClientTask = await discoveryClient.GetAsync();
		if (discoveryClientTask.IsError) throw new Exception(discoveryClientTask.Error);

		// request token
		var tokenClient = new TokenClient(discoveryClientTask.TokenEndpoint, "client", "secret");
		var tokenResponse = await tokenClient.RequestClientCredentialsAsync("api1");
		if (tokenResponse.IsError) throw new Exception(tokenResponse.Error);

		// call api
		var client = new HttpClient();
		client.SetBearerToken(tokenResponse.AccessToken);

		var response = await client.GetAsync("http://localhost:5000/identity");
		if (!response.IsSuccessStatusCode) throw new Exception(response.ReasonPhrase);

		var content = await response.Content.ReadAsStringAsync();
		return tokenResponse.AccessToken;
	}
	catch (Exception e)
	{
		return null;
	}
}
```
but at the very beginning `discoveryClientTask.IsError` is true and `discoveryClientTask.Error` is: "Error connecting to http://localhost:5000/.well-known/openid-configuration: Not Found"

If I use Postman on the browser to try a GET to http://localhost:5000/.well-known/openid-configuration it fails with 404 so this seems to be wrong.

How do I authenticate a .NET Core 2.1 SignalR console client with a .NET Core 2.1 web app SignalR server that uses "Identity as UI" ?

**Comment by anurse** [comment]
The reason it works in the browser is because the browser has a Cookie from when you logged in, so it sends it automatically when SignalR makes it's requests. To do something similar in the .NET client you'll have to call a REST API on your server that can set the cookie, scoop the cookie up from `HttpClient` and then provide it in the [`.WithCookie`](https://docs.microsoft.com/en-us/dotnet/api/microsoft.aspnetcore.signalr.client.hubconnectionbuilderhttpextensions.withcookie?view=aspnetcore-2.1#Microsoft_AspNetCore_SignalR_Client_HubConnectionBuilderHttpExtensions_WithCookie_Microsoft_AspNetCore_SignalR_Client_IHubConnectionBuilder_System_Net_Cookie_) method on `HubConnectionBuilder`.

However, when using an API like this, it's recommended you have a system to issue authentication tokens rather than using cookies. Cookies are designed for browsers, not for desktop applications. ASP.NET Core doesn't provide any default components for doing this, but there are third-party solutions like [IdentityServer](https://identityserver4.readthedocs.io/en/release/)

**Comment by kofifus** [comment]
got it thanks!

**Comment by kofifus** [comment]
Is there anywhere an example or can anyone show sample code of how to get the authenticate the console client, get the cookie from the server and then apply it to SignalR ? I can't find anything online
