### ISSUE TITLE
Different configuration methods in 1.0.0 vs 1.0.0-preview1-final ?

### ISSUE THREAD

**Issue by alexiordan** [aspnet/SignalR#2462]
I have update SignalR to 1.0.0 and using the .Net Client 
HubConnectionBuilder no longer has
methods like:
.WithJsonProtocol
.WithTransport

What is weird is that on msdn page
https://docs.microsoft.com/en-us/dotnet/api/microsoft.aspnetcore.signalr.client.hubconnectionbuilderextensions?view=aspnetcore-2.1

seems to have them.

Am I doing something wrong?

**Comment by anurse** [comment]
Yeah, the docs are out of date. There is an issue for updating them: https://github.com/aspnet/Docs/issues/6654. I'm closing this issue since we're tracking the out-of-date docs issue there.

To answer your questions:

* `WithJsonProtocol` was renamed `AddJsonProtocol`
* `WithTransport` is now just an `HttpTransportType` parameter on `WithUrl`:

```csharp
var connection = new HubConnectionBuilder()
    .WithUrl("...", HttpTransportType.WebSockets | HttpTransportType.ServerSentEvents)
    .Build();
```

**Comment by titonton** [comment]
For some reason that extension method doesn't exist on my build either.

**Comment by anurse** [comment]
Which methods? The ones I listed are the ones that should be present in `1.0.0`. See the (now updated) [API documentation](https://docs.microsoft.com/en-us/dotnet/api/microsoft.aspnetcore.signalr.client.hubconnectionbuilder?view=aspnetcore-2.1) for details on the APIs.

**Comment by titonton** [comment]
sorry I had the wrong package installed.
