### ISSUE TITLE
signalR.HubConnectionBuilder is not a constructor

### ISSUE THREAD

**Issue by Ponant** [aspnet/SignalR#2476]
Running the sample here
https://github.com/aspnet/Docs/blob/live/aspnetcore/signalr/hubs/sample/wwwroot/js/chat.js
gives the error in the title in Chrome, Edge and FireFox. The connection is started succesfully with a UWP client instea dof teh WPF sample, the Server is the one from the sample.
Any idea how to solve this?

**Comment by mikaelm12** [comment]
What version of SignalR are you using? 
The `HubConnectionBuilder` code looks correct to me

**Comment by Ponant** [comment]
Microsoft.AspNetCore.SignalR 1.0.0 on the server

**Comment by Ponant** [comment]
It seems to be an issue specific to the chat.js (?)

**Comment by anurse** [comment]
Have you copied the `signalr.js` file and added the script tag for it? See the [Getting Started](https://docs.microsoft.com/en-us/aspnet/core/signalr/get-started?view=aspnetcore-2.1&tabs=visual-studio#create-an-aspnet-core-project-that-hosts-signalr-client-and-server) doc for more information there. The samples do not include a copy of the `signalR.js` file itself (since it would get out-of-date very quickly), so you need to install it yourself.

I'd suggest following the Getting Started doc before jumping in to other samples, since most of those docs assume you're familiar with the Getting Started content.

**Comment by Ponant** [comment]
Yes it is included and the location is correct, SignalR id undefined otherwise in Chrome's console
`<script src="~/lib/signalr/signalr.js"></script>
`

**Comment by Ponant** [comment]
OK the sample was referencing `chat.js` in the index.cshtml file, but there is another one which works and is present
`<script src="~/js/es5-chat.js"></script>
`
The sample docs are outdated but thanks.
