### ISSUE TITLE
Cannot send SignalR message to specific clients using user(userId)

### ISSUE THREAD

**Issue by LuckyNoS7evin** [aspnet/SignalR#2498]
Cannot send SignalR message to specific clients using user(userId)

I use `_hubContext.Clients.User("luckynos7evin")` to get the client which does return a connection however client never receives the message.

(sorry missed the problem description)

**Client Code**
```csharp
_hubConnection = new HubConnectionBuilder()
    .WithUrl("http://localhost:50040/hubs/game", options =>
    {
        options.Headers.Add("x-gladiator-jwt", token.Code);
    })
    .Build();

_hubConnection.On("SendPing", () => 
{
    Console.WriteLine($"Ping");
});
_hubConnection.On<string, string>("SendAction", (user, message) =>
{
    Console.WriteLine($"{user}: {message}");
});
_hubConnection.StartAsync().GetAwaiter().GetResult();
```

Server Hub:
```csharp
[Authorize(AuthenticationSchemes="StreamGladiatorsAuth")]
public class GameHub : Hub
{
    public override async Task OnConnectedAsync()
    {
        await Clients.All.SendAsync("SendAction", Context.User.Identity.Name, "joined");
    }

    public override async Task OnDisconnectedAsync(Exception ex)
    {
        await Clients.All.SendAsync("SendAction", Context.User.Identity.Name, "left");
    }

    public async Task Send(string message)
    {
        await Clients.All.SendAsync("SendMessage", Context.User.Identity.Name, message);
    }
}
```

Server Controller (used for testing only):
```csharp
public class ViewerController : Controller
{
    private readonly IHubContext<GameHub> _hubContext;
    public ViewerController(IHubContext<GameHub> hubContext)
    {
        _hubContext = hubContext;
    }
       
    [HttpGet]
    public async Task<string> Get()
    {
        await _hubContext.Clients.All.SendAsync("SendAction", "ping", "here");


        await _hubContext.Clients.User("luckynos7evin").SendAsync("SendPing").ContinueWith((value)=> {

            if(value.IsFaulted)
            {

            }

        });


        return "done";
    }
}
```

You can also see the 30 minute highlight on Twitch in which I was trying to debug and figure out what I was doing wrong: [https://www.twitch.tv/videos/273342322](https://www.twitch.tv/videos/273342322)

* Server-Side NuGet Package: Microsoft.AspNetCore.App 2.1
* Client-Side NuGet Package: Microsoft.AspNetCore.SignalR.Client 1.0
*  C# Client
* Kestrel Server
* Windows 10

**Thanks in advance**

Andy (LuckyNoS7evin)

**Comment by anurse** [comment]
Is `luckynos7evin` the value of your `NameIdentifier` claim or the `Name` claim? We use the `NameIdentifier` claim for `User` because it's guaranteed to be unique whereas `Name` isn't guaranteed to be unique. Check our our [freshly minted doc](https://docs.microsoft.com/en-us/aspnet/core/signalr/groups?view=aspnetcore-2.1) on this for some more info.

If that's not the issue, we can dig a little deeper. Could you get server and client logs using the [Diagnostics Guide](https://github.com/aspnet/SignalR/wiki/Diagnostics-Guide)? Also, I notice you seem to be using some custom auth (`x-gladiator-jwt` Header, instead of just using JWT Bearer Auth), so if you able to share more of your project (including how you have your auth configured) that would be helpful. You should be able to use the `AccessTokenProvider` option to provide a JWT token rather than using a custom header.

**Comment by LuckyNoS7evin** [comment]
@anurse wow, missed that, thanks absolutely perfect and quick response to.

I missed it was NameIdentifier not Name.

Also thanks for the advice on the custom auth, we are trying a few things with the dev on this project, a few things to change down the line.
