### ISSUE TITLE
signalr-protocol-msgpack.js points to the app directory to look for msgpack5.js

### ISSUE THREAD

**Issue by dr130873** [aspnet/SignalR#2511]
Hi there,

First of all I would like to apologize if this seems like a silly question, but I think there is a issue in the signalr-protocol-msgpack.

We use gulp to bundle our js files, everything is working until I decided to use signalr-protocol-msgpack.
Now when we execute gulp, I get an error stating that msgpack5.js could not be found in the application directory, other npm packages we use do not behave the same so can you please help me.

Thank you...

versions indicated below 
{
  "@aspnet/signalr": "^1.0.0",
  "@aspnet/signalr-protocol-msgpack": "^1.0.0",
  "requirejs": "^2.3.5",
  "devDependencies": {
    "del": "^3.0.0",
    "gulp": "^3.9.1",
    "gulp-bundle-assets": "^2.29.0",
    "gulp-clean": "^0.3.2",
    "gulp-requirejs": "^1.0.0",
    "gulp-strip-debug": "^1.1.0",
    "gulp-uglify": "^3.0.0",
    "pump": "^1.0.3"
  },

var gulp = require('gulp');
var rjs = require("requirejs");

gulp.task('signalr-bundle', function () {
    var config = {
        baseUrl: "./",
        out: "wwwroot/dist/signalr-bundle.js",
        include: [

            './node_modules/@aspnet/signalr/dist/browser/signalr.min.js',
            './node_modules/msgpack5/dist/msgpack5.js',
            './node_modules/@aspnet/signalr-protocol-msgpack/dist/browser/signalr-protocol-msgpack.js'

        ]
    };
    rjs.optimize(config, function (e) {
        console.log(e);
    });
});

when running this gulp task i get the following error

{ [Error: Error: ENOENT: no such file or directory, open '{app folder}\msgpack5.js'
In module tree:
    node_modules/@aspnet/signalr-protocol-msgpack/dist/browser/signalr-protocol-msgpack.js
    at Error (native)
]
  originalError: 
   { [Error: ENOENT: no such file or directory, open '{app folder}\msgpack5.js']
     errno: -4058,
     code: 'ENOENT',
     syscall: 'open',
     path: 'C:\\{app folder}\\msgpack5.js',
     fileName: 'C:/{app folder/msgpack5.js',
     moduleTree: [ 'node_modules/@aspnet/signalr-protocol-msgpack/dist/browser/signalr-protocol-msgpack.js' ] } }
Process terminated with code 1.

**Comment by anurse** [comment]
I think you're not quite configuring requirejs correctly. It's a module loader, so the names you provide to `include` should be module names and not paths (like `@aspnet/signalr` or `msgpack5`) (see http://requirejs.org/docs/optimization.html#basics : "For properties that are module IDs, they should be module IDs, and not file paths. Examples are name, include, exclude, excludeShallow, deps.").

Because you're using file paths, requirejs is loading them as modules named after their file path. When `signalr-protocol-msgpack` goes to declare it's dependency on `msgpack5`, requirejs doesn't see that in the list of available modules (since the one you specified is called `./node_modules/msgpack5/dist/msgpack5.js`) so it goes to resolve it using the default behavior, via the app folder.

You need to use module names in `include`. The requirejs loader should be smart enough to look in `node_modules` for you automatically. If not, you can also use the `paths` option (see the requirejs docs I linked above) to give the specific path mapping for a named module.

**Comment by dr130873** [comment]
Thank you anurse, I did it a slightly different way... but you pointed me to the right direction
I added @aspnet/signalr and msgpack5 to the path object of the config object and now runs correctly
updated gulp task below:

gulp.task('signalr-bundle', function () {
var config = {
baseUrl: "./",
out: "wwwroot/dist/signalr-bundle.js",
paths: {
            //External packages
            'msgpack5': './node_modules/msgpack5/dist/msgpack5',
            '@aspnet/signalr': './node_modules/@aspnet/signalr/dist/browser/signalr'
        },
include: [

        './node_modules/@aspnet/signalr/dist/browser/signalr.min.js',
        './node_modules/msgpack5/dist/msgpack5.js',
        './node_modules/@aspnet/signalr-protocol-msgpack/dist/browser/signalr-protocol-msgpack.js'

    ]
};
rjs.optimize(config, function (e) {
    console.log(e);
});
});

**Comment by anurse** [comment]
You really should avoid using the full paths in `include`, it's not how requirejs is designed to work. I'd strongly suggest you try just specifying `@aspnet/signalr`, `@aspnet/signalr-protocol-msgpack` and `msgpack5` in `include` and, if necessary, use the `paths` value to point requirejs at the right files.

Anyway, I'm closing this as the question has been answered. Feel free to comment further if you need clarification on something!
