### ISSUE TITLE
After update to 1.0.0 Group not receving message.

### ISSUE THREAD

**Issue by PedroHFranco** [aspnet/SignalR#2513]
Hello,

I update my Core.SignalR version from 1.0.0-alpha2-final to 1.0.0, both side and now message sended to group not working, i have tested send to All and Other, and its working fine.

I'm adding in group when its connected in my Server, like this:

`Groups.AddToGroupAsync(Context.ConnectionId, "log4net");`

And sending like this:

`Clients.Group("log4net").SendAsync("RecieveMessage", Context.ConnectionId, message);`

It's was working fine in alpha version.
I'm doing something wrong or it's has been changed?

Thx.

**Comment by BrennanConroy** [comment]
That should be working, could you collect client and server logs? 
https://github.com/aspnet/SignalR/wiki/Diagnostics-Guide#server-side-logging

**Comment by PedroHFranco** [comment]
After include the Diagnostics its start working, do u think could be something is this way? 
Anyway thx.

**Comment by anurse** [comment]
Did it start working after you changed the log level on the server? Perhaps you had a race condition somewhere and the additional logging changed who was winning the race. Can you include the full code around where you add to group and send to the group? Perhaps something wasn't being `await`ed properly?

**Comment by PedroHFranco** [comment]
Yes it's working...

```
public override Task OnConnectedAsync()
{
	var httpContext = Context.GetHttpContext();
	var token = httpContext.Request.Query["Token"];
	switch (token)
	{
		case "log4net":
			Groups.AddToGroupAsync(Context.ConnectionId, "log4net");
			break;
		case "autoupdate":
			token = httpContext.Request.Query["Conta"];
			UpdateConnectionIdAutoUpdate(token, Context.ConnectionId);
			Groups.AddToGroupAsync(Context.ConnectionId, "autoupdate");
			break;
		default:
			UpdateConnectionIdConta(token, Context.ConnectionId);
			break;
	}

	return base.OnConnectedAsync();
}
```
Sending:

```
public void MessagedLogger(string message)
{
	Clients.Groups("log4net").SendAsync("RecieveMessage", Context.ConnectionId, message);
}
```

And this is my Js client side:

```
function startConnectionSignalR() {
	currentConnection = new signalR.HubConnectionBuilder()
		.withUrl("/monitoring?token=log4net")
		.configureLogging(signalR.LogLevel.Trace)
		.build();
	
	logBody.append("<p style='color: yellow;'>Iniciando conexão ao servidor da conta " + nomeConta + ".</p>");
	currentConnection.start().catch(err => console.error(err.toString()));
	listenStateConnection();
	stateConnection = currentConnection.connection.connectionState;

	currentConnection.on("RecieveMessage", (connectionId, message) => {
				if (message.indexOf("INFO") > -1) color = "aqua";
			if (message.indexOf("DEBUG") > -1) color = "#7CFC00";
			if (message.indexOf("ERROR") > -1) color = "red";

			logBody.append("<p style='color:" + color + "'>" + message + "</p>");
	});
}
```

**Comment by anurse** [comment]
> Groups.AddToGroupAsync(Context.ConnectionId, "log4net");
> Groups.AddToGroupAsync(Context.ConnectionId, "autoupdate");
> Clients.Groups("log4net").SendAsync("RecieveMessage", Context.ConnectionId, message);

Yep, these are causing the problem. You aren't `await`ing any of the Async calls. This causes a a race because the group add/send action is occurring in the background and you aren't waiting for it to finish so if you try to send to the group before it completes, the connection won't have been added to the group in time. Change these to use `await Groups.AddToGroupAsync(...)` (etc.) and that should resolve the issue even when diagnostics are disabled.

See the [documentation on Groups](https://docs.microsoft.com/en-us/aspnet/core/signalr/groups?view=aspnetcore-2.1#groups-in-signalr) for more information.

> currentConnection.start().catch(err => console.error(err.toString()));

This is also going to cause a similar race. The `.start` method is asynchronous, you need to register a callback using `.then` to run code after the connection has started. Also you should register your `.on` callbacks **before** starting the connection, just in case the server sends an invocation before your client can run that code.

See the [documentation on the JavaScript client](https://docs.microsoft.com/en-us/aspnet/core/signalr/javascript-client?view=aspnetcore-2.1) for more information
