### ISSUE TITLE
SendGroupsAsync may send to same connection more than once

### ISSUE THREAD

**Issue by johannes-maierhofer** [aspnet/SignalR#2527]
Not necessarily a bug, but undesirable bahaviour.

The SendGroupAsync method in the DefaultHubLifetimeManager enumetates each of the groups passed by name and sends the message to all connections within that group (SendToGroupConnections method). However, if a connection is in more than one group, the connection will get the message more than once.

Expected behaviour: SendGroupAsync gets all the distinct connections from the groups and sends to those.

**Comment by mikaelm12** [comment]
I'm assuming you meant the `SendGroupsAsync` method rather than the `SendGroupAsync`?

This is the expected behavior. There's an easy work around for the `DefaultHubLifetimeManager` case because all the connections live on the same server but imagine the Redis scenario for example. Instead of writing directly to connections, the `RedisHubLifetimeManager` publishes to channels that connections are subscribed to. There's not a simple way there to ensure that you're not publishing to two different channel that have no overlap of subscribers.

**Comment by johannes-maierhofer** [comment]
Thanks. Of course I meant the SendGroupsAsync (it's correct in the title of the post). You say that there is an easy work around? Which one?

I could implement my own HubLifetimeManager. In this case, just inheriting from DefaultHubLifetimeManager and overriding the method would not work. The HubConnectionStore and HubGroupList instances are private. HubGroupList is internal. However, it's doable.

Still not sure why this should be the expected behaviour. It might be different in the case of Redis. But there is a seperate RedisHubLifetimeManager anyway.

**Comment by aspnet-hello** [comment]
We periodically close 'discussion' issues that have not been updated in a long period of time.

We apologize if this causes any inconvenience. We ask that if you are still encountering an issue, please log a new issue with updated information and we will investigate.
