### ISSUE TITLE
Version numbering out of sync between client and server?

### ISSUE THREAD

**Issue by tonywr71** [aspnet/SignalR#2546]
I notice the Microsoft.AspNetCore.SignalR nuget package is 1.0.1, while the latest npm package is 1.0.0.  One issue I've had in the past is where the version numbers are out of sync and the client stops communicating with the server (or vice-versa.) Was having these out of sync intentional, because to me, even if there were no changes in one or the other, the version numbers should be kept in sync so that there isn't confusion about whether your versions match or not.

**Comment by anurse** [comment]
The requirement that the client and server versions match applies to preview builds only. In general, we expect released builds of the client to work with any released build of the server (at this time).

There were no changes to the JS client in 1.0.1 so we didn't ship a new version, that's been our pattern for most things in ASP.NET Core since the beginning. We could certainly consider a different strategy for this NPM package, but in general we've been sticking with what we've done elsewhere.

**Comment by aspnet-hello** [comment]
We periodically close 'discussion' issues that have not been updated in a long period of time.

We apologize if this causes any inconvenience. We ask that if you are still encountering an issue, please log a new issue with updated information and we will investigate.
