### ISSUE TITLE
How to not convert DateTime to UTC when serializing to send to Hub?

### ISSUE THREAD

**Issue by spudcud** [aspnet/SignalR#2549]
In JsonHubProtocol.ts the message is serialized using `return TextMessageFormat.write(JSON.stringify(message));`. This converts all date objects to UTC and then is sent to the Hub. I need a way to have this serialization conversion not happen and to pass the Date unconverted to the Hub. On the Hub side I am using a JsonConverter to handle the DateTime. In old SignalR we overrode `$.signalR.transports._logic.stringifySend` in order to not serialize the date. Is there a way to do this?

**Comment by spudcud** [comment]
The only thing I can think of is to globally replace JSON.stringify with a custom function. That is clearly not ideal as it would be nice if there was a way to provide the JsonHubProtocol with the encoding function to use rather than hardcoded to JSON.stringify. Thoughts?

**Comment by spudcud** [comment]
Thanks Andrew. I will give it a shot and see how it goes. Would it be possible to add this feature for the future to make the encoder configurable? Understood about entering the real of unsupported so definitely want to get back onto the right side of the line when possible :)

**Comment by anurse** [comment]
Yeah, I think we're definitely interested in some kind of configuration here. If you have some ideas about how to add this configuration, let us know! One of the core things we would want to do is ensure that we only expose configuration for the **user payload** pieces of JSON. The main reason the workaround I suggested is unsupported is because you are now in control of the underlying protocol as well as the JSON for the objects/arrays/etc. you passed in.

**Comment by spudcud** [comment]
Yesterday I spent my time making sure I could get everything working with overriding JSON.stringify and I did. Now I'll start looking at the JsonHubProtocol so I'll see if I can find a good way to do it. My initial 10 sec thought is to simply allow the protocol to get a function that is used as the payload/message encoder. I've only briefly looked at it so far so I'm not sure the complexity or anything.

**Comment by anurse** [comment]
Yeah, that sounds like what I'd suggest. I think the best way to do this would be to have the function transform the payload values from `object` to `object` rather than from `object` to `string`. The reason is that the only JSON serialization API we have is `JSON.stringify`. We can't "serialize" the payload and then insert that preserialized blob into the outer protocol. However, since we're in JavaScript, there's not really a need to. If we provide a transformer for the object that is expected to return **another object** (perhaps with a `Date` property transformed into a `string` property or with `camelCased` property names transformed into `PascalCased`, etc.) then we simply need to replace the objects in the message with the transformed objects and run `JSON.stringify` on them again.

Some pseudo-code:

```javascript
public writeMessage(message: HubMessage): string {
    switch(message.type) {
        case MessageType.Invocation:
            message.arguments = message.arguments.map(value => this.payloadTransformer(value));
            break;
        // etc... for other message types.
    }

    return TextMessageFormat.write(JSON.stringify(message));
}
```

As I said, if you're up for it, we'd definitely consider a PR for this. We'd want to make sure it has some unit and functional tests and I'm happy to help guide you through that if you need some assistance. Feel free to submit a PR with the changes prior to writing full tests if you need some guidance. If you're not able to make a PR that's OK too, we'll still consider this for a future release.

**Comment by spudcud** [comment]
I wholeheartedly agree with this approach as it will fit my need and be flexible for others and keep the internals consistent. Looks like you already got it all done. Ship it right ;)? Unfortunately I contractually cannot contribute to open source with work otherwise I would enjoy it a lot.

**Comment by anurse** [comment]
That's unfortunate, but I totally understand 😄. Thanks for your input!

**Comment by anurse** [comment]
merging this with #2685
