### ISSUE TITLE
Cannot send SignalR message to specific user when using Windows Auth

### ISSUE THREAD

**Issue by robinho81** [aspnet/SignalR#2558]
I cannot send a SignalR message to a specific user when using Windows Authentication with my ASP .Net Core Web Application. Just to be clear it works when sending to all Clients, but not to s specific user.

I am trying to send a message to a single user (potentially across multiple connections) as per the example from the documentation:
https://docs.microsoft.com/en-us/aspnet/core/signalr/groups?view=aspnetcore-2.1

The following call from my ChatHub does not work: 

To illustrate my issue, I have created a GitHub project at the following location:
https://github.com/robinho81/SignalRChatWindowsAuth

This example is the default Asp .Net Core Web Application template created in Visual Studio, configuring the project with Windows Authentication. Next, I added SignalR by following the getting started guide from the docs: https://docs.microsoft.com/en-us/aspnet/core/tutorials/signalr?view=aspnetcore-2.1&tabs=visual-studio

See readme for instructions on how to run.

The following are the versions I'm running:

**Nuget Versions:**
Microsoft.AspNetCore.SignalR -> 1.0.1
Microsoft.AspNetCore -> 2.0.3

**Client Side Versions:**
@aspnet/signalr -> 1.0.0

**Server:**
IIS Express

**Operating System (Client and Server):**
Windows 10 (1803)

Browser: 
Chrome, Firefox and Edge tested with the same result.

**Comment by robinho81** [comment]
Thanks a lot for the feedback. I had actually just forgotten to register this callback when I put together the sample to demonstrate the problem. 

I have added now, and still I don't receive messages when I send only to a specific user (in this case myself).

**Comment by anurse** [comment]
Ok, I see the issue. Windows authentication doesn't set the "Name Identifier" claim in `Context.User`. SignalR uses that to determine the value to use in `Clients.User(...)` (see the [documentation on users in SignalR](https://docs.microsoft.com/en-us/aspnet/core/signalr/groups?view=aspnetcore-2.1#users-in-signalr) for more info).

Fortunately there's a pretty easy workaround to this. Just create a new class that implements `IUserIdProvider` and have that use `connection.User` to find an appropriate value (such as `ClaimTypes.Name` which would be the user's Windows username).

```csharp
public class NameUserIdProvider : IUserIdProvider
{
    public string GetUserId(HubConnectionContext connection)
    {
        return connection.User?.FindFirst(ClaimTypes.Name)?.Value;
    }
}
```

Then register that new class in the DI container **after** `.AddSignalR`:

```csharp
services.AddSignalR();
services.AddSingleton<IUserIdProvider, NameUserIdProvider>();
```

You can always double check the "User Identifier" for a particular connection in the debugger by looking at `Context.UserIdentifier` in the debugger when in a Hub method. The value of that property is the value that another connection would need to put in `Clients.User(...)` to send a message to that user.

I'm working on an authentication doc for SignalR so I'll add a Windows Auth sample to that so we have something to help users in the future! I'm closing this issue since we should have a solution here. Feel free to comment further with any questions and we can file new issues if something else comes up!
