### ISSUE TITLE
Typescript client unable to negotiate due to unnecessary (?) JSON.parse

### ISSUE THREAD

**Issue by ntrpnr** [aspnet/SignalR#2562]
* Versions of Server-Side NuGet Packages: 1.0.1
* Versions of Client-Side NuGet/NPM Packages: @aspnet-signalr 1.0.0
* Are you using the C# client or the JavaScript client: TypeScript client
* The Server you are using (Kestrel/HttpSysServer/IIS/IIS Express/Azure Web App/etc.):  Azure Web App
* The Operating System on the Server (Windows/Linux/macOS): -
* The Operating System on the Client (Windows/Linux/macOS): Android (NativeScript)
* The Browser on the client, if using the JavaScript client (IE/Chrome/Edge/Firefox/etc.): -

```
JS: Debug: Starting HubConnection.
JS: Debug: Starting connection with transfer format 'Text'.
JS: Debug: Sending negotiation request: http://theapp.azurewebsites.net/gameHub/negotiate
JS: Error: Failed to complete negotiation with the server: SyntaxError: Unexpected token o in JSON at position 1
JS: Error: Failed to start the connection: SyntaxError: Unexpected token o in JSON at position 1
```

Using fiddler, I was able to see that the response from the server was correct.
This row in **HttpConnection.ts** was trying to parse the string `[Object object]`:
```
return JSON.parse(response.content as string) as INegotiateResponse;
```

Changing this row to:
```
return response.content as INegotiateResponse;
```

Solved everything for me:
```
JS: Debug: Skipping transport 'WebSockets' because it is not supported in your environment.'
JS: Debug: Skipping transport 'ServerSentEvents' because it is not supported in your environment.'
JS: Debug: Selecting transport 'LongPolling'
JS: Debug: Sending handshake request.
JS: Debug: Server handshake complete.
JS: Information: Using HubProtocol 'json'.
JS: Hub connection started
```

So the question is, is this JSON parse necessary? Should I create a pull request with this change?

**Comment by anurse** [comment]
The `JSON.parse` is definitely necessary in browser environments. The `response.content` value comes from [`XMLHttpRequest.response`](https://developer.mozilla.org/en-US/docs/Web/API/XMLHttpRequest/response) and the type of it depends upon the value of `XMLHttpRequest.responseType`, which we leave set to the default value `""` which means it will be text.

Since you're running on NativeScript, it sounds like maybe NativeScript has different behavior from the browser here. Looking at [it's XHR implementation](https://github.com/NativeScript/NativeScript/blob/master/tns-core-modules/xhr/xhr.ts#L150) it seems it tries to automatically detect the Content Type, which is not what browsers do. I'm surprised the NativeScript would be doing something different from the browser when trying to polyfill it since this may cause compatibility issues with other libraries as well.

Currently, the SignalR JavaScript client only officially supports browser environments. We can look at improving our support for other platforms like NativeScript in the future.

**Comment by anurse** [comment]
Also, we'd definitely consider a PR fixing this to work in NativeScript, as long as it doesn't break browser scenarios. In this case, the logic will have to be updated everywhere `HttpClient` is used.

**Comment by anurse** [comment]
Since this is caused by NativeScript incorrectly implementing XHR, I don't think there's something we want to do here. We'd still consider a PR to make this better if it can be done that doesn't break the browser scenario.
