### ISSUE TITLE
Client disconnects after 15 minutes

### ISSUE THREAD

**Issue by devindran** [aspnet/SignalR#2565]
Server version: Microsoft.AspNetCore.SignalR 1.0.1
Client version: Microsoft.AspNetCore.SignalR.Client 1.0.1

Using C# client
Server: Kestrel on Pivotal Cloud Foundry instance
Client: Kestrel on Pivotal Cloud Foundry instance

Server OS: Linux
Client OS: Linux

Browser: None

I am attempting to deploy some AspNet Core 2.1 workloads on Pivotal Cloud Foundry, and testing SignalR as a mechanism for back end communication between instances.

I'm noticing an odd behavior from Clients running on PCF. After exactly 15 minutes of connecting, they will disconnect from the server. The server registers a OnDisconnectedAsync event from the connection id. However, from the client side, the Closed event is not fired.

I have tried to use the KeepAlive interval, as well as manually sending pings from the client to server.

However, at times this does not happen. The client is able to stay connected indefinitely. If I run the client from my local windows machine, this problem does not happen either.

My question: 
1. Is there anywhere in the settings which defaults to 15 minutes that I can override?
2. Has anyone else seen this behavior outside of Pivotal i.e. cloud instances running on linux

Thanks.

**Comment by anurse** [comment]
There's nothing that I'm aware of, nor have I seen this behavior before. Can you collect client and server logs as well as network traces as described in the [Diagnostics Guide](https://github.com/aspnet/SignalR/wiki/Diagnostics-Guide) referenced in the Issue template? That would help us understand what is terminating the connection 😄

**Comment by BrennanConroy** [comment]
In `WithUrl` in the delegate you can set `Credentials`, `ClientCertificates`, and `WebSocketConfiguration`. The `Credentials` and `ClientCertificates` are automatically copied into the `WebSocketOptions` when websockets is started up.

As for ServerCertificateCustomValidationCallback on websockets it looks like there is a new API on the options `RemoteCertificateValidationCallback` but it isn't available in the current version.

**Comment by anurse** [comment]
> it looks like there is a new API on the options RemoteCertificateValidationCallback

The API is available in .NET Core 2.1 only according to the [API reference](https://docs.microsoft.com/en-us/dotnet/api/system.net.websockets.clientwebsocketoptions?view=netcore-2.1).

You can use the `WebSocketConfiguration` option to configure this (see the [configuration docs](https://docs.microsoft.com/en-us/aspnet/core/signalr/configuration?view=aspnetcore-2.1#configure-additional-options) for some details). Because of how `ClientWebSocketOptions` works, you have to provide a delegate to *modify* the existing options rather than providing your own options. For example:

```csharp
var connection = new HubConnectionBuilder()
    .WithUrl(uri, configure => {
        configure.WebSocketConfiguration = options => {
            options.RemoteCertificateValidationCallback = ...;
        }
    })
    .Build();
```

**Comment by anurse** [comment]
Closing this as a proposed solution was provided a while ago. If that solution isn't working for you, feel free to comment further and we can continue investigation and re-open the issue if necessary!

**Comment by seriouz** [comment]
Under ubuntu linux 16 with SDK 2.1.402 , the `RemoteCertificateValidationCallback` never gets called.

**Comment by anurse** [comment]
Can you show the code you are using the register the callback?

**Comment by anurse** [comment]
Sorry, it looks like my comment above wasn't entirely clear. Because of the different APIs in use (`ClientWebSocket` and `HttpClient` do not share config information) you have to define the callback in **both** places. Even when WebSockets is in use, a standard `HttpClient` is used for the initial handshake process.

```csharp
void MyValidationCallback(object sender, X509Certificate certificate, X509Chain chain, SslPolicyErrors sslPolicyErrors)
{
    // ... your validation implementation
}

var httpClientHandler = new HttpClientHandler
{
    ServerCertificateCustomValidationCallback = MyValidationCallback
};
var connection = new HubConnectionBuilder()
    .WithUrl(url, configure => {
        configure.HttpMessageHandlerFactory = () => new HttpClientHandler
        {
            ServerCertificateCustomValidationCallback = MyValidationCallback;
        };
        configure.WebSocketConfiguration = options =>
        {
            options.RemoteCertificateValidationCallback = MyValidationCallback;
        };
    })
    .Build();
```

We've talked briefly about trying to make this easier. We could do what we do with other options like Headers and provide our own place to configure the callback and then copy the callback into each place it's needed. However, the main problem is that `ClientWebSocket` only supports a remote validation callback as of .NET Core 2.1, but the SignalR Client needs to support all .NET Standard 2.0 platforms. So if we don't do this carefully, it could create the illusion that a callback is supported when it isn't actually supported.

**Comment by seriouz** [comment]
@anurse Thanks for clearification!
I added the HttpMessageHandlerFactory and it is now properly working. 

```c#
                        configure.HttpMessageHandlerFactory = _ =>
                        {
                            return new HttpClientHandler
                            {
                                ServerCertificateCustomValidationCallback = (message, cert, chain, errors) => { return true; }
                            };
                        };
```
