### ISSUE TITLE
SignalR + Redis pub\sub client for any .Net application

### ISSUE THREAD

**Issue by ralfius** [aspnet/SignalR#2566]
Hi everybody,

Could you please implement the package that allows to publish notifications from any .net application to redis pub\sub so the connected asp.net core signalr application can see and process these messages on its end.

I have provided more details here: [https://stackoverflow.com/questions/51058040/signalr-core-with-redis-pub-sub-and-console-application](https://stackoverflow.com/questions/51058040/signalr-core-with-redis-pub-sub-and-console-application)

I see that there is some infrastructure information like headers, type of message etc. in the redis signalr contract that makes it difficult to emulate using pure redis pub\sub client.

**Comment by anurse** [comment]
You want to publish SignalR messages directly to Redis? This isn't something we have any plans to enable at this time. If you want to make it work, there's nothing stopping you, you just have to implement the [SignalR Redis Protocol](https://github.com/aspnet/SignalR/blob/dev/src/Microsoft.AspNetCore.SignalR.Redis/Internal/RedisProtocol.cs), which isn't officially documented (because it's not designed for other systems to implement at this time) but is fairly well described in the code.

**Comment by ralfius** [comment]
hi @anurse 
Thanks for reply. How reliable is the signalr redis contract? Can I treat current implementation as a final or you are going to change it in future?
I would like to avoid the situation when the contract is changed and new version of signalr + redis is not compatible with my implementation

**Comment by anurse** [comment]
We can't guarantee that it won't change, since we're not committed to supporting it as a way to "plug in" to the SignalR backplane. I don't anticipate much (if any) change, but it's not a formal protocol contract at all.

**Comment by aspnet-hello** [comment]
We periodically close 'discussion' issues that have not been updated in a long period of time.

We apologize if this causes any inconvenience. We ask that if you are still encountering an issue, please log a new issue with updated information and we will investigate.
