### ISSUE TITLE
Support specifying custom JSON.NET options for JsonHubProtocol

### ISSUE THREAD

**Issue by evenflow58** [aspnet/SignalR#261]
I would like to add a contract resolver to signalR requests in order to camel case my return types. I tried used the pattern described [here ](http://stackoverflow.com/a/39410434/1309248) but the contract resolver seems to be ignored. Has this been implemented? [Here](https://github.com/evenflow58/SignalRExample)'s a repository with my attempt. I would expect the returned value from GetMessage to be `{ message: 'a message' }` but I get `{ Message: 'a message' }`.

**Comment by moozzyk** [comment]
No, customizing serialization is not possible at the moment. This case is quite interesting however - you want to modify the payload on the server  to get camelCased property names because you are using only a javascript client. If you used heterogeneous clients (e.g. javascript and C#) then modifying the payload on the server side wouldn't work since the clients use different conventions.

**Comment by muratg** [comment]
cc @DamianEdwards

**Comment by muratg** [comment]
@davidfowl do you have a design in mind?

**Comment by davidfowl** [comment]
This should be in preview. We need a way to configure these options and have them flow to the `JsonHubProtocol` implementation.

**Comment by moozzyk** [comment]
We could try resolving JsonSerializerSettings  from DI in the JSonHubProtocol ctor. 

Note that if we decide to support this we will need two JSonSerializers - one for the hub protocol itself that is not configurable and one for serializing custom types.

**Comment by moozzyk** [comment]
another option (if registering in DI feels to general) is to have it in HubOptions where it could possibly be specified per HubProtocol implementation.

**Comment by anurse** [comment]
That actually feels like the best option to me. Have a way to specify Hub Protocol options (of various kinds, including which protocols to allow)

**Comment by ssougnez** [comment]
Hi, maybe what I'm about to propose is the same as you (because I didn't really understood it :-$) but why can't you just do something like:

`services.AddSignalR(options => options.JsonContractResolver = new CamelCasePropertyNamesContractResolver());`

And this would only applied to what's send in the "arguments" property of the response? This way, the user would be able to choose if he wants to keep the default behaviour (for C# client for example) or switch to Camel case (for JavaScript client).

**Comment by anurse** [comment]
@ssougnez Yep, that's basically exactly what we're talking about. It'll likely be a `JsonSerializerSettings` you'll be able to provide, which gives you Contract Resolver access, but also a bunch of other settings.

**Comment by BrennanConroy** [comment]
This is now in via https://github.com/aspnet/SignalR/pull/743
