### ISSUE TITLE
Microsoft.AspNetCore.SignalR.1.0.2 for ASP.NET Core 2.0 projects

### ISSUE THREAD

**Issue by eduardoyupanqui** [aspnet/SignalR#2650]
Can i use this nuget for ASP.NET Core 2.0 projects?. We plan to migrate to ASP.NET Core 2.1 next month.

Thanks.
Eduardo

**Comment by BrennanConroy** [comment]
It's an unsupported scenario, however it will probably work. Leave it up to you to decide how risky it is.

**Comment by anurse** [comment]
I wouldn't go as far as saying it will probably work. It may partially upgrade parts of your dependency graph (i.e. you might have a mix of ASP.NET Core 2.1 and ASP.NET Core 2.0 components, at various levels in your system). As @BrennanConroy said it is not officially supported, so there could be unknown issues that occur. We don't test that scenario, and will not fix bugs that occur because of mismatching versions. Is something blocking your migration to ASP.NET Core 2.1? I'd definitely encourage doing that migration before adopting SignalR.

**Comment by eduardoyupanqui** [comment]
I was mapping references between "Microsoft.AspNetCore.All(2.0.5)" and "Microsoft.AspNetCore.SignalR(1.0.2)", and not found different version references.

![sin titulo](https://user-images.githubusercontent.com/6488091/42848545-8b7f0df2-89e5-11e8-95b6-ef8e041b567f.jpg)



I need to publish a implementation with SignalR this week, but need that its works.

**Comment by aspnet-hello** [comment]
We periodically close 'discussion' issues that have not been updated in a long period of time.

We apologize if this causes any inconvenience. We ask that if you are still encountering an issue, please log a new issue with updated information and we will investigate.
