### ISSUE TITLE
Consider removing Debugger.IsAttached checks from shipping code

### ISSUE THREAD

**Issue by BrennanConroy** [aspnet/SignalR#2698]
It was useful when originally writing the library but now can just cause weird unexpected behavior.

**Comment by anurse** [comment]
As we discussed in person, I think we should keep it. Removing it would cause weird behavior when a user is debugging their Hub methods (if they take longer than the timeout, the connection could just disappear out from under them while debugging). Also there's precedent here since Kestrel does similar things with TCP connections.

**Comment by anurse** [comment]
I think we mostly decided to keep it.
