### ISSUE TITLE
The server disconnected before the handshake was completed

### ISSUE THREAD

**Issue by NaiShengYu** [aspnet/SignalR#2773]
Microsoft.AspNetCore.SignalR.client (verson(1.0.2))
in C# 
 connection = new HubConnectionBuilder().WithUrl("http://gx.azuratech.com:30021/signalr-loggingEventHub").Build();
 await connection.StartAsync();

have a Exception 
 the Exception.message is “The server disconnected before the handshake was completed”

**Comment by anurse** [comment]
Can you collect the client and server logs requested in the [Diagnostics Guide](https://github.com/aspnet/SignalR/wiki/Diagnostics-Guide)? We need more information to be able to diagnose the issue.

**Comment by anurse** [comment]
We need more than the stack trace and exception message to be able to diagnose this issue. Can you please collect the server and client logs described in the [Diagnostics Guide](https://github.com/aspnet/SignalR/wiki/Diagnostics-Guide)? In Xamarin, the Console is difficult to use, but you can use the [Debug logger](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/logging/?view=aspnetcore-2.1#debug-provider) to log to the Visual Studio Debug console when you run under the debugger. Even just server-side logs would help though.

Also can you answer the relevant questions that were listed in the New Issue template?

* Versions of Server-Side NuGet Packages:
* Versions of Client-Side NuGet/NPM Packages:
* Which client are you using? (.NET, JavaScript, Java, etc.):
* The Server you are using (Kestrel/HttpSysServer/IIS/IIS Express/Azure Web App/etc.): 
* The Operating System on the Server (Windows/Linux/macOS):
* The Operating System on the Client (Windows/Linux/macOS/iOS/Android):

This kind of error occurs when the server or some intermediate abruptly terminates the connection, so we need more information than just the stack trace in order to identify where it could be occurring.

**Comment by anurse** [comment]
Closing this as we haven't heard from you. Please feel free to comment if you're able to get the information we're looking for and we can reopen the issue if we're able to identify the problem.
