### ISSUE TITLE
Enable batch processing of requests.

### ISSUE THREAD

**Issue by scalablecory** [aspnet/SignalR#2775]
In many cases, it can be faster to process a batch of requests rather than multiple concurrent requests. Think e.g. inserting into a database.

I'd love for SignalR Core to allow me to transition this:

```
Task SendMessage(string user, string message)
{
    ...
}
```

To something like this:

```
[Batch(MaxSize = 100)]
Task SendMessage(IEnumerable<(string user, string message)> requests)
{
    ...
}
```

The idea being that when reading messages from the socket it would queue messages for as long as the socket had data immediately available, up to `MaxSize`. From the protocol's perspective this would be transparent.

**Comment by scalablecory** [comment]
Not sure if SignalR would efficiently handle it, but doing this with a Nagle-like algorithm can already be handled at a higher level right now due to being able to return tasks.

The primary benefit of integrating this idea of batching directly into SignalR is to optimize around I/O patterns: at a minimum, deplete your sockets 100% (or up to some limit) and then process all the requests you received as a single batch. An optional Nagle feature on top of that would be a cherry on top.

**Comment by davidfowl** [comment]
I'm not a fan of adding this level of complexity unless there were massive benefits. It complicates the dispatching code and it complicates the programming model.

**Comment by scalablecory** [comment]
>I'm not a fan of adding this level of complexity unless there were massive benefits (and I'm not seeing them).

As I said, bulk updates in databases (maybe via a TVP) tend to be significantly faster than concurrent individual updates.

This isn't a problem we _need_ SignalR itself to solve, of course, and there are arguments to be had against more tightly coupling the simple idea of a Hub with I/O patterns. However, having implemented it on top of SignalR already and dealt with those issues firsthand, I think some rock-solid core code is worth exploring.

In my implementation I first started with a timeout-based approach (as @anurse mentioned), but quickly realized that the simplest approach would result in large latency issues during lulls in request frequency.

Next I added some code to detect those lulls and disable the timeout. Didn't feel quite perfect because it didn't 100% remove the issue, but it worked pretty well.

Following this, rather than detecting lulls, I made a second operation Flush() which felt cleaner and removed the latency issue completely. However, this also has its own complexity once you need to decide what Flush() means when multiple callers are sending requests concurrently.

So, while I do feel like a timeout-based approach would be a useful tool to have, I also believe that the complexity of this may be a bit much. Which lead me to a much simpler ask of simply following the I/O of the sockets:

> SignalR effectively already "drains the socket" already.

It's a suggestion on how one would enable batches with minimal complexity while avoiding the latency issues I arrived at. I want to drain the socket's buffers. Once the buffers are drained (and we're waiting for more data from the wire), dispatch the batch. Some pseudocode:

```
Task readTask = socket.ReadAsync();

for(;;)
{
	var batch = new List<Request>();
	
	do
	{
		await readTask;

		while(socket.HasRequest)
		{
			batch.Add(socket.DequeueRequest());
		}
		
		readTask = socket.ReadAsync();
	} while(readTask.IsCompleted);
	
	DispatchBatchToHub(batch);
}
```

> it complicates the programming model.

I'd argue that doing it on top of SignalR complicates hub code a whole lot more than an attribute and `IEnumerable`. I decided in the end to scrap my implementation because I was not confident a jr/mid dev would be able to maintain it.

**Comment by anurse** [comment]
The process you went through to solve this seems very application-specific. Each application is going to have significant differences in the way messages are received. If we build something into the core, we have to handle all those edge cases and provide deep configuration in order to allow an application to take advantage of it. We've been burned before with these kinds of things (automatic message replay comes to mind) and generally find that application-specific logic is necessary no matter how we implement it because of how complex the space is.

More questions to consider:
* Would we only batch messages from the same caller?
  * If so, what value is this providing over batching on the client?
  * If not, how would thinks like `Context.Caller` react to this (since there would be multiple "callers")? 
* If the connection drops mid-batch, do we dispatch the batch in-progress or drop it? 
  * If we dispatch it, we're invoking a Hub method when we know there's no connection, which isn't something we've done before.

It'd definitely be interested to look at what *extensibility* SignalR could provide to allow a batching extension to be built. I'm a lot more open to that since it allows application developers to choose the solutions that work for them.

As @davidfowl said, we already do drain the socket. The socket read is not coupled to the invocation of the Hub method, so we'll keep reading messages from the socket while the Hub method is running and then we'll dispatch the incoming messages as quickly as possible. We *do* synchronize Hub method invocations so that a single connection is only running a single invocation at a time, but if you had your Hub methods add the incoming messages to a batching system that you control you'd effectively end up with the batching system you're discussing. Something like the below would accomplish what you're looking for (presuming `_batchProcessor.Add` adds a data item to the current batch and a background process is flushing the batches according to your policy):

```csharp
public class MyHub: Hub
{
    public Task ReceiveItem(string data)
    {
        _batchProcessor.Add(data);
        return Task.CompletedTask;
    }
}
```

I'm sure there are plenty of existing tools out there to handle batching in .NET, and I'm not sure we could do as well as they could given everything else we have to focus on.

**Comment by anurse** [comment]
We aren't looking to provide this kind of batching as a native SignalR scenario. It's totally reasonable to do batching on top of our APIs.
