### ISSUE TITLE
signalr > http.sys > doesn't work when using computer name for url

### ISSUE THREAD

**Issue by talanc** [aspnet/SignalR#2841]
### Please include as much of the following as you can in your bug report

* Versions of Server-Side NuGet Packages: Microsoft.AspNetCore.App 2.1.1
* Versions of Client-Side NuGet/NPM Packages: 1.0.2
* Are you using the C# client or the JavaScript client: Yes
* The Server you are using (Kestrel/HttpSysServer/IIS/IIS Express/Azure Web App/etc.):  Http.Sys
* The Operating System on the Server (Windows/Linux/macOS): Windows 7
* The Operating System on the Client (Windows/Linux/macOS): Windows 7
* The Browser on the client, if using the JavaScript client (IE/Chrome/Edge/Firefox/etc.): Tested on Firefox and Chrome

* Please use the Diagnostics Guide at https://github.com/aspnet/SignalR/wiki/Diagnostics-Guide to collect server-side and client-side logs and network traces if possible. Please **do not** put the traces and logs in the Issue text as they are quite large. The Diagnostics Guide describes how to attach them to the issue.
[server.txt](https://github.com/aspnet/SignalR/files/2304963/server.txt)
[client-626ff2s-1534829995314.log](https://github.com/aspnet/SignalR/files/2304964/client-626ff2s-1534829995314.log)

### Info

I think there's an issue when using SignalR and HTTP.sys. My signalr connection won't work when you set the application url to your computer name.

My use case for this is a real-time dashboard for an intranet application. The application is hosted on a windows 7 machine on our network, it doesn't have IIS, and it requires windows authentication. The last two parts are why I'm using HTTP.sys.

I can't share the proper application but I've created a small application which can replicate the issue :
https://github.com/talanc/fetch-and-signalr-problem
- Open in Visual Studio 2017
- Start program, expect results from fetch and signalR (it's set to localhost at this stage)
- Go to launchSettings.json and change applicationUrl from localhost to your computer name (find via echo %COMPUTERNAME%)
- Start program, expect results from fetch but not signalR

**Comment by anurse** [comment]
Are you able to access the application via a browser using this URL? I believe HTTP.sys does require specific server configuration to work from an external URL (i.e. the computer name) (cc @Tratcher).

**Comment by talanc** [comment]
Yes, it works with my computer name.

Using localhost:
Pages work
Fetch/Controller works
SignalR works
![image](https://user-images.githubusercontent.com/13086414/44432877-3fba4300-a5e7-11e8-8a99-062f8cea1fed.png)

Using my computer name:
Pages work
Fetch/Controller works
SignalR doesn't work
![image](https://user-images.githubusercontent.com/13086414/44432891-46e15100-a5e7-11e8-8c3f-85928abcb5c7.png)

**Comment by anurse** [comment]
I'm not having any problem running your sample on my machine. The steps I followed:

1. Cloned your sample
2. Added a URL reservation so that my user could listen on that URL: `netsh http add urlacl url=http://mycomputername:5000/ user=MyUserName`
3. Changed the `applicationUrl` in `launchSettings.json` to read `http://mycomputername:5000/`
4. Ran the sample with Ctrl-F5

I get this result:

![image](https://user-images.githubusercontent.com/7574/44434887-726e2800-a562-11e8-80ca-a62683a06dc7.png)

When you said the rest of your app was working, did you hard-refresh the page (Ctrl-F5)? If you had previously tested with Kestrel, it's possible your main application page was cached, but the SignalR content can't be cached. So while it would have appeared that the HTML page was working, it was only working because the browser had cached it.

If the HTML content is working even when you hard-refresh it, then there may be a SignalR issue to investigate. If not, it's either a configuration issue or an issue with the HttpSys server itself.

**Comment by talanc** [comment]
**URL Reservation**
Nothing changes after I added the URL reservation and test the program.
![image](https://user-images.githubusercontent.com/13086414/44437666-8c5d4880-a5fe-11e8-8d74-bd38d50cdd7e.png)

**Hard-refreshing**
Nothing changes after hard-refreshing multiple times.

**Kestrel**
It works with Kestrel.

> If the HTML content is working even when you hard-refresh it,
> then there may be a SignalR issue to investigate. If not, it's either
> a configuration issue or an issue with the HttpSys server itself.
The reason I added it as an issue on SignalR is because:
- The page and static files: works on Kestrel and HttpSys
- JS fetch plus server controller result: works on Kestrel and HttpSys
- signalr result: works on Kestrel but not HttpSys

**Comment by talanc** [comment]
Here's something I noticed in the console when running Kestrel and HttpSys:

**Kestrel**
`dotnet run --urls http://626FF2S:5000` (commented out UseHttpSys() in Program.cs)
...
`Now listening on: http://[::]:5000`
...
`Request starting HTTP/1.1 GET http://626ff2s:5000/favicon.ico`

**HttpSys**
`dotnet run --urls http://626FF2S:5000`
...
`Now listening on: http://626FF2S:5000`
...
`Request starting HTTP/1.1 GET http://626ff2s:5000/favicon.ico`

_Notice the 'Now listening on...' part_

If I try to run `dotnet run --urls http://[::]:5000` on Kestrel, navigating to http://626FF2S:5000 doesn't work. On HttpSys it comes up with this error: [httpsys.err.txt](https://github.com/aspnet/SignalR/files/2308625/httpsys.err.txt)

**Comment by anurse** [comment]
There is definitely something fishy going on here if the HTML content and the XHR fetch are working. I'm using Windows 10, so there could be a difference there. I know WebSockets doesn't work, but we also detect that case and ensure the transport falls back.

Let me see if I can get a repro on Windows 7 box. If you're able to collect network traces using a tool like [Fiddler](https://github.com/aspnet/SignalR/wiki/Diagnostics-Guide#fiddler-windows-and-macos) that might also help.

**Comment by talanc** [comment]
[Fiddler.sazes.zip](https://github.com/aspnet/SignalR/files/2308769/Fiddler.sazes.zip)

**Comment by talanc** [comment]
I found a workaround. If I specify Long Polling then it works, like so: `.withUrl("/valuesHub", **signalR.HttpTransportType.LongPolling**)`

Also my test program works on my win10 home computer, as well as a win7 vm on that computer as well. 

One thing I should have mentioned initially is that I'm under a corporate proxy (my work).

**Comment by anurse** [comment]
It's very possible HTTP.sys or your proxy are interfering with the Server-Sent Events transport as well. We've seen issues where proxies buffer data coming from the server which completely breaks the Server-Sent Events transport because that transport depends on being able to send small chunks of data over a long-running request that only completes when the connection ends.

I'll close this for now since it appears to be an issue in your specific environment. I'm glad Long Polling is working out for you, that's why we have it there ;). If you encounter any other issues, please feel free to open a new issue!
