### ISSUE TITLE
Is the JavaScript client form release/2.2 compatible with ASP.NET Core 2.1?

### ISSUE THREAD

**Issue by ArtemAvramenko** [aspnet/SignalR#2844]
NPM version (1.0.2) has some critical bugs, that were fixed in branch 2.2.

So I want to build client lib from source. Is it compatible with SignalR from ASP.NET Core 2.1?

**Comment by anurse** [comment]
Yes, the 2.2 client is *designed* to be compatible with the 2.1 server. However, since it is a very early preview, please remember that there may be compatibility issues. If you do encounter an issue, please file an issue here!

We do produce nightly builds for `release/2.2`, but it looks like maybe they aren't published to an NPM feed anywhere. I'll see if it's possible for us to get them published to a MyGet feed to make things easier. (cc @natemcmaster). Otherwise, building from source should work fine.

**Comment by ArtemAvramenko** [comment]
It will be great if you publish npm package with `preview` tag.

**Comment by anurse** [comment]
We don't push nightly builds to NPM. When we push the first official preview build (coming this week) we'll use a tag to allow you to quickly install it.

**Comment by ArtemAvramenko** [comment]
> coming this week
Great news!

**Comment by anurse** [comment]
FYI this has now been published under the tag `next`. The tag `latest` continues to point at the latest non-preview build (currently `1.0.3`). You should be able to install the latest versions using the following commands:

```
> npm install @aspnet/signalr@next
> npm install @aspnet/signalr-protocol-msgpack@next
```
