### ISSUE TITLE
Protocol versioning

### ISSUE THREAD

**Issue by muratg** [aspnet/SignalR#289]
- Version negotiation
- ~Behavior with bare websocket connections~ 

Things to do (by @anurse):
* [x] Change MsgPack protocol to assert minimum size of array for each message, rather than exact size and skip things it doesn't care about.

**Comment by moozzyk** [comment]
We can now plugin different protocols so instead of versioning a protocol we could just implement a different version with a different name. 

There were also some ideas about the client sending protocols it supports and the server picking one.

**Comment by anurse** [comment]
We need to make sure the v1 protocol is clear on a few behaviors before we ship it:

1. How should servers/clients behave when they see an unexpected (higher or lower than supported) version from the other party

2. How should servers/clients behave when they see unexpected message types (i.e. ignore them, error out, etc.)

See #894 - We need to make sure the protocol is set up so that we understand how a protocol change like that would be made (even if we never end up making it ;))

**Comment by anurse** [comment]
Finally got a work item for this: We should make sure that for MsgPack, we don't validate the exact length of the argument array. This will allow additional values to be added to the end and ignored by older clients.
