### ISSUE TITLE
Channel or Stream Support from Client to Server?

### ISSUE THREAD

**Issue by faryu** [aspnet/SignalR#2981]
I'm currently using SignalR Core in a project and it does a great job so far!

I currently have a little problem with data send from the client to the server, which exceeds the data limit.
I know that the limit can be adjusted, but it doesn't really solve my use case.
What I want to do is stream a variable list of items from the client to the server. If the list get's to large, I will have to split it into smaller chunks or set the transfer limit higher (which is risky, because I don't know how many items there will be).

A better solution would be to use the ChannelReader, just like it's currently used to stream data from the server but in the opposite direction.
Is it possible to add the support to stream data from the client to the server?
Or does the current architecture forbid it?

I'm currently using the C# client and server. So far I do not require the javascript client in my project.

**Comment by anurse** [comment]
This is something we're actively considering for the 3.0 release next year. See https://github.com/aspnet/SignalR/issues/2699 .

I'm going to close this issue just because we're already tracking this. Glad to hear this feature would be useful to you! Feel free to continue discussion on this thread or the referenced issue!
