### ISSUE TITLE
Consider RTM versioning for Java Client

### ISSUE THREAD

**Issue by anurse** [aspnet/SignalR#3002]
Right now the Java Client is versioned at 0.1.0. We need to decide what to ship for the final version number. There are some things that we might not get to in 2.2 (Streaming, MessagePack, other transports, for example). Should we wait until those land before setting the version to 1.0? Or should set it now and simply document that those features are coming in later releases?

**Comment by Tragetaschen** [comment]
I would prefer that an RTM versioned package properly feels like a SignalR client. I could live with fewer protocol options or transport types (because by and large those things are abstracted in the library), but omitting Streaming from a first RTM would hurt my Hubs on the server-side.

Couldn't the Java client be released "in the 2.2 time frame" as opposed to "on the RTM date"?

**Comment by anurse** [comment]
@Tragetaschen Are you planning to use the Java Client with your streaming hubs? I'd love to know more about the scenario that you need support for.

**Comment by anurse** [comment]
We talked about this for a while and we decided that the least confusing option for customers is to set the version number to `1.0` even though we aren't going to include support for Streaming in this first release. A couple reasons why:

1. The missing streaming feature is obvious as soon as you start using it, the `.stream` method isn't there
2. Shipping a "pre-release" version of the Java Client with ASP.NET Core 2.2 RTM is a lot of added confusion

We will plan on releasing a "1.1" release of the Java Client well before the ASP.NET Core 3.0 RTM that does include Streaming, so customers won't have to wait all the way until the next ASP.NET Core release for it.
