### ISSUE TITLE
Handle cases where a method called from the server does not exist on the client

### ISSUE THREAD

**Issue by moozzyk** [aspnet/SignalR#312]
Consider non-open formats like Protobuf

**Comment by muratg** [comment]
@moozzyk isn't this also a problem the other way?

**Comment by muratg** [comment]
@anurse has some ideas around this.

**Comment by moozzyk** [comment]
Yes, this is also a problem on the server. I think we stopped throwing on the server so it "works" but we don't have coverage for non-JSON formats.

**Comment by anurse** [comment]
For protobuf, we need to consider this when we're designing the Hub Protocol over Protobuf. I think we're going to want to have a closed "outer" frame that stores arguments a simple length-prefixed buffers so we can decode the whole frame and then look up how to parse arguments.

**Comment by davidfowl** [comment]
This is figured out now that we have a length prefix right?

**Comment by moozzyk** [comment]
Still needs to be implemented.

**Comment by anurse** [comment]
We need to verify the code path fully here. With the spec'ed Protobuf definitions, we are able to parse the outer "Invocation" message regardless of if the application provided a schema for the requested method (since the arguments are just a raw, uninterpreted, binary payload), so we should be all set. We just need to make sure that the fact that the binder will fail to bind the arguments flows through properly as an error indicating that the method does not exist.

**Comment by davidfowl** [comment]
We're dropping protobuf 😄
