### ISSUE TITLE
Send `IDictionary<string, object>` to server, the server received the dictionary but modify the key: Change the first letter to lower case.

### ISSUE THREAD

**Issue by realwanpengli** [aspnet/SignalR#3140]
* Versions of Server-Side NuGet Packages: 2.1.2
* Versions of Client-Side NuGet/NPM Packages: 1.1.0-preview2-35157
* Are you using the C# client or the JavaScript client: C# client
* The Server you are using (Kestrel/HttpSysServer/IIS/IIS Express/Azure Web App/etc.): 
* The Operating System on the Server (Windows/Linux/macOS): Windows
* The Operating System on the Client (Windows/Linux/macOS): Windows

The hub protocol is `json`.

Send `IDictionary<string, object>` to server, the server received the dictionary but modify the key: Change the first letter to lower case.

For example: `Key` => `key`

How to keep the key unchanged?

**Comment by anurse** [comment]
We configure JSON.NET to convert property names to `camelCase` by default because it is more familiar on the JavaScript side. However, we have documentation on how to disable this in our documentation [JSON/MessagePack serialization options
](https://docs.microsoft.com/en-us/aspnet/core/signalr/configuration?view=aspnetcore-2.1#jsonmessagepack-serialization-options). In fact, the example on that document describes exactly what you are trying to do: preserve the casing of your JSON property names.

**Comment by realwanpengli** [comment]
I see. Thank you.

But if I set hub protocol = `messagepack`, the convert property names are not changed by default. 

Therefore, If I change hub protocol while using default configurations, I have to care about all my dictionaries' property names... That's inconvenient.

**Comment by anurse** [comment]
Correct, each serialization library has it's own way of handling property names.

**Comment by realwanpengli** [comment]
Okay
