### ISSUE TITLE
OnDisconnected method is not calling on the server even user has been disconnected more than CloseTimeout

### ISSUE THREAD

**Issue by sarvabowmen** [aspnet/SignalR#3158]
### Please consider the following before filing an issue

* If you are using NuGet Packages that start with `Microsoft.AspNet.SignalR`, use the issue tracker at https://github.com/SignalR/SignalR to report the issue. This 
repository is for packages that start with `Microsoft.AspNetCore.SignalR` (and NPM packages that start with `@aspnet/signalr`)

### Please include as much of the following as you can in your bug report

* Versions of Server-Side NuGet Packages: 1.0,4
* Versions of Client-Side NuGet/NPM Packages: 1.0.4
* Are you using the C# client or the JavaScript client: JavaScript
* The Server you are using (Kestrel/HttpSysServer/IIS/IIS Express/Azure Web App/etc.):  Azure Web App
* The Operating System on the Server (Windows/Linux/macOS): Windows
* The Operating System on the Client (Windows/Linux/macOS): Windows
* The Browser on the client, if using the JavaScript client (IE/Chrome/Edge/Firefox/etc.): Chrome
* Please use the Diagnostics Guide at https://github.com/aspnet/SignalR/wiki/Diagnostics-Guide to collect server-side and client-side logs and network traces if possible. Please **do not** put the traces and logs in the Issue text as they are quite large. The Diagnostics Guide describes how to attach them to the issue.

When in doubt, feel free to file the issue, we're happy to help answer questions. We also suggest using the `asp.net-core-signalr` tag on StackOverflow to ask questions.

The Scenario: 
Client Named "A" connects to the server through chrome browser and established a connection, Then client named "B" connects to the server through chrome browser and established a connection, Now both are connected to the server, **Then "A" decides to manually disconnect the Wifi connection by clicking on the disconnect button next which is placed to wifi name in the network list**.

**Expected:** 
OnDisconnected event for user "A" should be triggered after default wait timeout
**Actual:**
OnDisconnected event is not triggered in the server for client A, even after default timeout which is 30 secs.

**Comment by anurse** [comment]
This is a known issue in 2.1 and will be fixed in 2.2 (https://github.com/aspnet/SignalR/issues/2289). The client doesn't "ping" the server so the server doesn't have a way to tell the difference between an idle connection and a connection that terminated without a "close" message.

If you can try the [latest 2.2 preview](https://blogs.msdn.microsoft.com/webdev/2018/10/17/asp-net-core-2-2-0-preview3-now-available/) and see if that fixes your problem that would be great! The RTM version of that should be released [by the end of the year](https://github.com/aspnet/Announcements/issues/307).

Closing this as the issue should be resolved in the next version.
