### ISSUE TITLE
Loads of Failed Connection Handshake

### ISSUE THREAD

**Issue by joelnotified** [aspnet/SignalR#3169]
* Versions of Server-Side NuGet Packages: Microsoft.AspNetCore.SignalR 1.0.3
* Versions of Client-Side NuGet/NPM Packages: @aspnet/signalr 1.0.3
* Are you using the C# client or the JavaScript client: Both. I think these errors originates from javascript clients
* The Server you are using (Kestrel/HttpSysServer/IIS/IIS Express/Azure Web App/etc.):  IIS
* The Operating System on the Server (Windows/Linux/macOS): Windows
* The Operating System on the Client (Windows/Linux/macOS): Not sure
* The Browser on the client, if using the JavaScript client (IE/Chrome/Edge/Firefox/etc.): Not sure unfortunately

Since updating to ASP.NET Core 2.1 (and the latest package versions of SignalR, both client and server). We've started to receive loads of errors like `Failed connection handshake`. Most of the connections are fine, but I can't figure out what the problem is with those that are not. 

I'm sorry I can't provide you with more information, hoping that this is enought for someone to understand what might be wrong, or how I can get more information.

I've seen that all the failing connections have about 5 seconds between `OnConnectedAsync started` and `Failed connection handshake`. Maybe some kind of timeout?

Unfortunately I can't log on the client, since I can reproduce it and I do not know what clients cause this. 

Should this be a stackoverflow question maybe? 

Thank you!

![image](https://user-images.githubusercontent.com/27775157/47300917-f05fb580-d61d-11e8-9e9b-3defe289d0ad.png)

**Comment by anurse** [comment]
Are you able to update to the latest 2.2 preview at all? I know we resolved some handshake ordering issues there and also added some improved logging.

**Comment by joelnotified** [comment]
@anurse I could try it out locally, but I haven't been able to reproduce the error (only seing it in production for some clients). So I think I would have to wait until there is a more stable release that I can deploy to production. Sorry..

**Comment by anurse** [comment]
It sounds exactly like the issue we fixed in 2.2. We also added additional logging so that if you do see this issue again in 2.2 you'd get the actual content that the client sent.

I'm going to close this since I believe we've solved the issue in 2.2. When 2.2 releases (see [Roadmap](https://github.com/aspnet/Announcements/issues/307)), give it a try and feel free to come back and re-open this issue (or file a new one) and we can investigate further!

**Comment by bunceg** [comment]
@anurse How is this specific issue not a patch to the existing release? We have production customers hitting this; it may work for 5 minutes and then it fails permanently... it's completely not stable for a production environment. We can't use a preview package (no idea what else might not work) or wait until December for this... it's unbelievable.

Any mitigation? (e.g. don't use Web Sockets?)

**Comment by anurse** [comment]
> We have production customers hitting this; it may work for 5 minutes and then it fails permanently

This sounds like a different issue. What @joelnotified reported was intermittent. Are you seeing a permanent failure to establish connections? That's not something I've heard reports of yet, so filing a new issue with some more details might be appropriate here.

**Comment by grahambunce** [comment]
@anurse I will dig out additional logs but we have been firefighting after this started to happen. So far, disabling WebSockets on our azure web app, and enabling session affinity so forcing long polling seems to have fixed it. It failed on all our customer sites. It’s either something from patch Tuesday or (from another GitHub issue I have seen) the azure load balancer killing the connection.... as we run two app service instances

**Comment by anurse** [comment]
> Our clients connect for 5 minutes or so and then fail and do not appear to reconnect

Do you have reconnection logic in your client? ASP.NET Core SignalR doesn't have automated reconnect.

> So far, disabling WebSockets on our azure web app, and enabling session affinity so forcing long polling seems to have fixed it.

FYI, Session Affinity is generally required even when using WebSockets because of the initial negotiate request. If you are using the SkipNegotiate setting it's not necessarily required, but this is generally not recommended as it means clients have to be updated if you use the "redirect" model.

> the azure load balancer killing the connection.... as we run two app service instances

Yes, this is a well-known problem on App Service. If you have a relatively high-traffic site, App Service can be problematic as it has hard limits on concurrent connections at the front-end. This is one of many reasons we **strongly** recommend using the Azure SignalR Service when using App Service.

**Comment by grahambunce** [comment]
@anurse ok, thanks for the feedback. If this isn’t in the guides (I have not looked for a while) then I suggest it should be - especially the necessity for app affinity regardless of protocol. Azure app service is (was?) in preview at the time of development and the number of connections per $ seems expensive when compared to self hosting (though not if that doesn’t actually work properly!!) or when compared to some of the competitors

**Comment by anurse** [comment]
The main reason we built Azure SignalR is because it is very difficult to scale a self-hosted SignalR app well. 

The core problem is that SignalR connections are persistent connections, whereas standard HTTP users have "transient" connections. An HTTP client establishes a connection, requests some data, disconnects, and then repeats for the next request (there is some "connection pooling" that means this isn't quite the workflow, but the gist is there). That means that there are often much fewer active TCP connections that you have users, when all your users are using HTTP. 

However, with SignalR, every single SignalR user has a persistent TCP connection to your server. In general, 100 TCP connections sending 1 message per second has a higher impact on your resources than 1 TCP connection sending 100 messages per second, so scaling an app that has persistent connections is a very different challenge than scaling a standard HTTP app.

Self-hosting is always an option, but then you need to become an expert in all the scaling issues that come from managing these persistent connections. Azure SignalR takes the burden off your app and converts those `N` connection connections to your app into a single connection to the server through which all the messages to/from your clients flow. That means you can scale your app based on the number of *requests* (both HTTP requests and SignalR messages) rather than having to worry about scaling along two separate pivots (requests and connections)

> If this isn’t in the guides (I have not looked for a while) then I suggest it should be

We do specifically call this requirement out in our [Publish to Azure](https://docs.microsoft.com/en-us/aspnet/core/signalr/publish-to-azure-web-app?view=aspnetcore-2.1#configure-signalr-web-app) documentation.

> when I say clients do not reconnect I mean they are not able to reconnect despite trying

I thought that might be the case but just wanted to make sure :).
