### ISSUE TITLE
The server disconnected before sending a handshake response

### ISSUE THREAD

**Issue by pavanpadavala** [aspnet/SignalR#3207]
We are seeing intermittent disconnected errors between ASP.Net core Hub and Azure SignalR . And when trying to reconnect, the method `HubConnection.StartAsync()` is failing with message

` “One or more errors occurred. (The server disconnected before sending a handshake response)” `

After this, even if we try to reconnect, it is not able to connect and completely stops broadcasting.

When we scale in or scale out the Azure SignalR units, the connections are getting reset and it starts working but again going into the same issue after few hours.
We would like to understand
1.	What is reason for intermittent disconnection?
2.	How scaling out is resetting the connections?

This has been working from few months and we started seeing this error last week only. 

* Versions of Server-Side NuGet Packages: Microsoft.Azure.SignalR 1.0.0-preview1-10011
* Versions of Client-Side NuGet/NPM Packages: Microsoft.AspNetCore.SignalR.Client 1.0.2
                           npm - @aspnet/signalr - 1.0.0
* Are you using the C# client or the JavaScript client: Both
* The Server you are using (Kestrel/HttpSysServer/IIS/IIS Express/Azure Web App/etc.): IIS / Service Fabric
* The Operating System on the Server (Windows/Linux/macOS): Windows
* The Operating System on the Client (Windows/Linux/macOS): Any
* The Browser on the client, if using the JavaScript client (IE/Chrome/Edge/Firefox/etc.): Any

**Comment by anurse** [comment]
Those versions are out of date and include a pre-release package. Can you update to the latest versions?

* [Microsoft.Azure.SignalR 1.0.2](https://www.nuget.org/packages/Microsoft.Azure.SignalR/1.0.2)
* [Microsoft.AspNetCore.SignalR.Client 1.0.4](https://www.nuget.org/packages/Microsoft.AspNetCore.SignalR.Client/1.0.4)
* [@aspnet/signalr 1.0.4](https://www.npmjs.com/package/@aspnet/signalr)

We've fixed a number of issues in those patches and your issue may be resolved there. If the issue is still reproducible when you are running the latest patched version, can you collect server-side traces using the instructions described in the [Diagnostics Guide](https://github.com/aspnet/SignalR/wiki/Diagnostics-Guide) and attach them? Then we can help dig in to this more.

> 2\. How scaling out is resetting the connections?

I'd suggest asking this question of the Azure SignalR team since we don't directly operate that service and don't have detailed knowledge of the system (we work closely with them, but I'd rather not guess at an answer ;)). You can find that team at https://github.com/Azure/azure-signalr . This question may have been asked already so I suggest you search their issue tracker.

**Comment by anurse** [comment]
Closing this as we haven't heard from you. Please feel free to comment if you're able to get the information we're looking for and we can reopen the issue if we're able to identify the problem.
