### ISSUE TITLE
[question] Do you plan to support structured errors in Completion message?

### ISSUE THREAD

**Issue by jerdnox** [aspnet/SignalR#3235]
According to Hub protocol is "error" an "A String encoding the error message." We would like to provide more structured error data for our hub clients in some cases. Error code would be usually enough. Client can then for example decide (based on error code) to retry the operation or give up immediately. More data would be nice in other cases (e.g. recommended retry count, recommended delay between retries, etc.). Basically something like [Google API Design Guide - Errors](https://cloud.google.com/apis/design/errors).

**Comment by anurse** [comment]
I'm not 100% convinced we can do a lot better than what we have given the security issues with revealing arbitrary exception data. If we did this, we'd probably do it by only allowing `HubException` to carry additional data (since `HubException` is the only exception that allows the error message to propagate all the way to the client). That means that if you have strong layering and don't throw `HubException` from deep in your system, you end up with a Hub method that looks like this:

```csharp
public async Task DoTheThing(...)
{
	try
	{
		// Do the thing...
	}
	catch(SomeSpecificException ex)
	{
		throw new HubException("...", code: 1234);
	}
}
```

This doesn't look a lot different from the code you could write today to accomplish much the same thing:

```csharp
public async Task<ThingResult> DoTheThing(...)
{
	try
	{
		// Do the thing...
		return ThingResult.Success();
	}
	catch(SomeSpecificException ex)
	{
		return ThingResult.Failed(code: 1234);
	}
}
```

You have to manage `ThingResult` (the type that represents a completed operation) yourself, but you can make it generic and add any parameters you want to it, so you have complete control and flexibility without SignalR introducing new concepts for you to manage.

I'm certainly open to being convinced, but I'm not sure I'm there yet. What kind of design would you expect here?

**Comment by jerdnox** [comment]
Well, I am not trying to convince you. I was just curious if you have any thoughts/plans about handling errors.

The solution with generic result is exactly what we already thought about (and what we will most likely implement). I believe that you are right in that you have complete control and flexibility. But there are some things I don’t like about it.

It is not backward compatible change if you already have existing API (Not actually problem for us. We just started designing our API). You will need to change every method to return your generic result. You need to always add it. Even when you think you don’t need it at first (and may be you never will in that specific call).

```C#
// from
void Foo1();
Bar Foo2();

// to
Result Foo1();
Result<Bar> Foo2();

// if you want stay backward compatible, then you need something like this
void Foo1();
Result Foo1_2();
Bar Foo2();
Result<Bar> Foo2_2();

// where
public class Result
{
  public int ErrorCode;
  public string ErrorDetail;
}

public class Result<T> : Result
{
  public T Payload;
}
```

When you then check the resulting json when serialized you end up with something similar to 'Completion Message'. Because you should either have error or payload. That is why I thought completion message is the right place. 

Streaming would be awkward with generic result. 
```C#
ChannelReader<Result<Bar>>
```
There you would like to send error data only when you complete with error.

Your example with HubException is probably what I would expect. What I am not sure about is how you would extend it if additional error data is needed. In generic response case you can do something like this:
```C#
public class Result<T, TError> : Result<T>
{
  public TError ErrorPayload;
}
```
May be creating generic HubException\<T\>?

**Comment by anurse** [comment]
> Well, I am not trying to convince you. I was just curious if you have any thoughts/plans about handling errors.

No problem :). Just wanted to lay out my current feelings!

> It is not backward compatible change if you already have existing API (Not actually problem for us. We just started designing our API). You will need to change every method to return your generic result.

That's a good point. It's one of the many reasons Exceptions exist, because you want some way outside of the normal flow to communicate an error. API Versioning is something we're going to look at in 3.0 (in relation to https://github.com/aspnet/SignalR/issues/3157) so this may be something we need to consider.

> Streaming would be awkward with generic result

Another good point, `ChannelWriter.TryComplete` only takes an `Exception` so there's no way to flow some arbitrary "completion error data" down.

> May be creating generic HubException<T>?

That's not a bad idea.

This is something ASP.NET SignalR ("Classic SignalR") didn't really handle either, so we're trying not to rush in to adding features, but this is a good one to do some thinking on. I'll toss this in the 3.0 milestone for some further discussion.

**Comment by jerdnox** [comment]
OK then. Thanks for the information. 

API Versioning is also something we talked a lot about in our team. Our current approach is to hold backward compatibility as long as possible by using “good” request/response objects. Something similar to what you mentioned in [#3157](https://github.com/aspnet/SignalR/issues/3157) “use classes as parameters”. When we should introduce breaking change then we plan to create new Major version of that hub. We plan to have multiple “smaller” hubs that group use case functionality. We hope this way it will be less painful to introduce new major versions.

So we use [semantic versioning](https://semver.org/) for our API.

Information about hubs and their versions is available through ApiVersionInfo.json file. File is available on same base URL as hubs (e.g. http://localhost:5000/ApiVersionInfo.json ). This file contains all supported hubs. Every hub lists their available versions. There is only one version entry per *major* version. *Minor* version number represent the actual/latest version. If *DepreciationDate* property is available then this *major* version is obsolete and will be removed after specified date. *Path* property specify part of URL to navigate to this *major* version (e.g. when value is /Foo/V1 then full path can be http://localhost:5000/Foo/V1 ).

Example:
```JSON
{
    "Hubs": [
        {
            "Name": "Foo",
            "AvailableVersions": [
                {
                    "Path": "/Foo/V1",
                    "Major": 1,
                    "Minor": 2,
                    "DepreciationDate": "2018-12-31"
                },
                {
                    "Path": "/Foo/V2",
                    "Major": 2,
                    "Minor": 0
                }
            ]
        }
    ]
}
```

Client is responsible to check this data and compare available hub versions with version that client was written against. If there is hub with matching *major* version and equal or higher *minor* version then it should be OK.

We are updating this file manually now. But later we would like to generate this data at runtime from hub mappings if possible.

We are still at the beginning so we are yet to find out if this approach will really suite us.

**Comment by anurse** [comment]
After some design discussion, we found that the big blocking issue is that the client doesn't have a way to express the type of `T` in something like `HubException<T>`, which means the client logic gets just as complicated as something like `Result<T>`. We're not going to explore this further right now, and will wait for further feedback.
