### ISSUE TITLE
Design and implement support for Hub methods returning Streams and IObservable<T>

### ISSUE THREAD

**Issue by anurse** [aspnet/SignalR#324]
We want to support Hub methods returning streams of data, like this:

```csharp
public IObservable<Thingy> Subscribe()
{
}

public Stream DownloadFile()
{
}
```

We need a design and implementation to support this.

**Comment by anurse** [comment]
Related, but not covered here: Sending binary data to the Hub. We can do this using `byte[]` right now, we just have to make it as efficient as possible.

**Comment by ReubenBond** [comment]
As a little proof of concept, not quite related to SignalR, but which I made because SignalR didn't support it: [WebStreams](https://github.com/WebStreams/WebStreams.Server), eg: https://github.com/WebStreams/WebStreams.Samples/blob/master/StockTickerController.cs

And methods can also consume observables: https://github.com/WebStreams/WebStreams.Samples/blob/master/ChatRoomController.cs#L48
I used [Orleans](https://github.com/dotnet/orleans) as the "backplane", but that's not in any of those repos.

**Comment by davidfowl** [comment]
Nice!
