### ISSUE TITLE
Add timeouts to server side waiting logic

### ISSUE THREAD

**Issue by davidfowl** [aspnet/SignalR#361]
There are a bunch of places we wait on tasks to complete where we should be timing out:

1. The transport completes and the application is running forever.
2. The application completes and the transport is running forever (only happens with websockets).

The first is likely an application bug. We closed the transport either gracefully or ungracefully and have told the application this much but that signalr is being ignored.

The second is our bug since the application told us that it was done sending data but we don't close because nothing is timing out the receive loop.

We *may* not want to tackle 1. because the user should just make their application work. 2 on the other hand is our issue.

/cc @anurse @BrennanConroy

**Comment by anurse** [comment]
There's a more nuanced side to 1 in WebSockets. "The Transport Completes" indicates that both ends have closed. WebSockets allows for a half-close, where one side sends a close frame, indicating that it's finished **sending**, but it still expects to read data **received** from the other side.

In general, in WebSockets, sending a Close frame gives no guarantee as to when or even if a Close frame will come from the other party. EndPoints should be able to support this behavior if they want to.

I am 100% in favor of a system that aborts the socket after the EndPoint returns from `OnConnectionAsync` (after a certain timeout), because then the EndPoint has **also** indicated that it no longer wishes to **read** data. But simply closing the outbound channel does not indicate that the connection is complete and the socket should be terminated.

**Comment by davidfowl** [comment]
Discussed with @anurse and we agree this is a super edge case. We won't be adding an application timeout either.
