### ISSUE TITLE
Usage on Debian with WSS

### ISSUE THREAD

**Issue by Hantse** [aspnet/SignalR#376]
Hello,

I try to deploy my code on debian server, when i try to connect WS i receive this error :

Unable to handle WebSocket request, there is no WebSocket feature available.

For precision, i try to use wss :)

**Comment by moozzyk** [comment]
Does it work with ws and not wss? What client do you use? Do https requests work correctly? Also do you have more details like stack trace etc. Sample app in form of github repo would be useful. 

Asking because we have end to end tests that run on each change on Windows, Linux and Mac and which use ws so this should work. SignalR is not doing do anything specific for wss - all that is needed should be done by lower level layers.

**Comment by moozzyk** [comment]
No follow up. Closing.

**Comment by Hantse** [comment]
Sorry,

I use apache as proxy pass :

<IfModule mod_ssl.c>
<VirtualHost *:443>
        ServerName mywebsite.tech
        SSLCertificateFile /etc/letsencrypt/live/mywebsite.tech/fullchain.pem
        SSLCertificateKeyFile /etc/letsencrypt/live/mywebsite.tech/privkey.pem
        Include /etc/letsencrypt/options-ssl-apache.conf
        ProxyPreserveHost On
        ProxyRequests off

        ProxyPass / http://127.0.0.1:5000/
        ProxyPassReverse / http://127.0.0.1:5000/

        ProxyPass /editor/ wss://127.0.0.1:5000/editor/
        ProxyPassReverse /editor/ wss://127.0.0.1:5000/editor/

        ErrorLog /var/log/httpd/mywebsite-error.log
        CustomLog /var/log/httpd/mywebsite-access.log common
</VirtualHost>
</IfModule>

**Comment by moozzyk** [comment]
You haven't answered my questions: https://github.com/aspnet/SignalR/issues/376#issuecomment-292371357 or provided a repro. Also, in your case - who is supposed to terminate https - Apache or Kestrel (i.e. is the traffic between Apache and Kestrel encrypted)?

**Comment by Hantse** [comment]
Apache redirect request to Kestrel, traffic is not encrypted.

**Comment by Hantse** [comment]
No idea ?

**Comment by moozzyk** [comment]
No one has tried it yet.
