### ISSUE TITLE
Make TypeScript clients consistent with other JavaScript event names

### ISSUE THREAD

**Issue by anurse** [aspnet/SignalR#449]
Our events have camel-cased names (`onClosed`, `onDataReceived`), but most JavaScript events in the browser have all-lower-case names (see https://www.w3schools.com/jsref/dom_obj_event.asp).

Unfortunately NodeJS is not consistent with this and does have camel-cased names, for example: https://nodejs.org/api/process.html#process_event_beforeexit. However, our events use the DOM style of having a property that is set to a function, rather than the NodeJS style of using [`EventEmitter`](https://nodejs.org/api/events.html#events_class_eventemitter). So it seems more appropriate to use the DOM event format.

We could also just decide to switch to `EventEmitter` and use that syntax, that's fine with me. We should just be consistent.

**Comment by moozzyk** [comment]
Our event names are camel cased to follow TS conventions.

**Comment by anurse** [comment]
My main concerns is discovery. All DOM events are strictly lowercase, and since JavaScript is case-sensitive, it can be difficult to realize why an event isn't firing. In theory we could support both, with one as an accessor aliasing to the other.

If we're fine with diverging from the DOM, that's OK with me, but it should be a conscious decision. I definitely agree that SignalR will be used outside the DOM but the primary environment in which the JavaScript client will run is the browser, so we should probably aim to support those conventions. What did SignalR 2.x do?

Either way, as long as we make a decision and stay consistent, I'm OK with it. I've just hit this a few times, and seen others hit it and wondered if we're aligning to the right convention :).

**Comment by moozzyk** [comment]
OK, let's discuss it during team meeting. I think, I am not concerned about diverging from the DOM too much since we want the client to be DOM/browser agnostic. If, however, camel case makes it difficult for the user to use the client (i.e. they have hard time figuring out why things don't work because they just have a typo in their code) then it would be the reason to make the names lowercase. 

SignalR 2.x used [camel case](https://github.com/SignalR/SignalR/blob/dev/src/Microsoft.AspNet.SignalR.Client.JS/jquery.signalR.core.js#L54-L63)

**Comment by anurse** [comment]
The 2.x data makes me feel much more comfortable with camelCase. We can stick with this as-is and get some feedback on it.
