### ISSUE TITLE
SignalR backend/scaleout - CosmosDB

### ISSUE THREAD

**Issue by grahamehorner** [aspnet/SignalR#450]
Please consider SignalR scaleout/backend using CosmosDB  IMO CosmosDB would be great from a globally distributed SignalR community given the SLAs for global replication off messages to regions & provide some interesting data analytic options using other Azure services that using CosmosDB

**Comment by anurse** [comment]
My understanding of CosmosDB is that it's designed for durable consistent storage. That doesn't seem like a good fit for SignalR scale out. SignalR scale-out requires very low-latency consistency and has very minimal (if any) persistence requirement. The scale-out system is simply responsible for delivering a message from one node out to the other connected nodes, as fast as possible.

It's true that we previously support SQL Server, which has some similarlity to CosmosDB (in being a database built for durable storage), but my understanding is that we supported it primarily to allow people to use an existing tool to solve the problem rather than forcing them to spin up new infrastructure.

The scale-out infrastructure in SignalR will be pluggable, so there's always room for community efforts. If there's a benefit and support behind adding CosmosDB as an option, we'd certainly look at that, but our resources are limited and I doubt we'll be able to throw any behind exploring a new system like this for a while.

**Comment by grahamehorner** [comment]
Not sure I fully understand then? seem a good fit to me with the following form the CosmosDB site

. Azure Cosmos DB guarantees single-digit-millisecond latencies in the 99th percentile anywhere in the world, offers multiple well-defined consistency models to fine-tune performance and guarantees high availability with multi-homing capabilities – all backed by industry-leading, comprehensive service-level agreements (SLAs).

**Comment by grahamehorner** [comment]
correct me if I'm incorrect but wasn't there a backplane for mongodb ? not sure if it was written by Microsoft or an intern ?

**Comment by davidfowl** [comment]
> correct me if I'm incorrect but wasn't there a backplane for mongodb ? not sure if it was written by Microsoft or an intern ?

We didn't write it.

**Comment by davidfowl** [comment]
> Not sure I fully understand then? seem a good fit to me with the following form the CosmosDB site

> . Azure Cosmos DB guarantees single-digit-millisecond latencies in the 99th percentile anywhere in the world, offers multiple well-defined consistency models to fine-tune performance and guarantees high availability with multi-homing capabilities – all backed by industry-leading, comprehensive service-level agreements (SLAs).

That's a good fit for pub sub?

**Comment by grahamehorner** [comment]
Q: use case I have a set of websites spanning azure multi azure regions the sites use signalr hubs; how would I enable a signalr a backend to scale across regions?  could the SignalR RabbitMQ backend route/forward messages to other RabbitMQ services in other regions ?

**Comment by davidfowl** [comment]
> Q: use case I have a set of websites spanning azure multi azure regions the sites use signalr hubs; how would I enable a signalr a backend to scale across regions? could the SignalR RabbitMQ backend route/forward messages to other RabbitMQ services in other regions ?

I'm not understanding what you're getting at. You can use *anything* to store messages and relay them to other webservers (even SQL server) but some things are better than others because they were designed with that in mind. If you're in Azure, you should really be using service bus or redis to push messages back and forth.

**Comment by anurse** [comment]
Even if it had some value, and I'm certainly open to being convinced of that, I don't think it's something that would happen in 1.0 simply because of resources and time. This seems like a thing where we need to see what the community does and what users need. The scale-out model will be pluggable and if CosmosDB support becomes necessary we can revisit it then.

I (and I think most of the team) learned about CosmosDB the same time you did, and after we've planned out the 1.0 feature set and roadmap, so just thinking logistically it's not likely to make 1.0. Still worth keeping this on our backlog and being ready to get feedback from the community :)

> Azure Cosmos DB guarantees single-digit-millisecond latencies in the 99th percentile anywhere in the world, offers multiple well-defined consistency models to fine-tune performance and guarantees high availability with multi-homing capabilities – all backed by industry-leading, comprehensive service-level agreements (SLAs).

We haven't had a chance to dig in to this in depth. It's not clear yet to me if the latency they are talking about is transport latency (i.e. how fast the service responds to requests) or actual data-flow latency (how long it takes all nodes to become aware of a change).

**Comment by moozzyk** [comment]
This is not something we are planning to do at this point.

**Comment by wesamco** [comment]
@moozzyk now that SignalR was released, can we continue the discussion? 

@anurse "_**a single-digit-millisecond latency**_" I think I heard that term from a keynote, i'm currently reading the SLA, finally just got the legal definitions and stuff behind me, haven't got to anything that confirm it or define it _yet_ in the SLA.
a <10ms latency, How does that compare to redis's latency, 1 order of magnitude lower I think? 
i'm thinking about it with Jeff deans latency table in front of my eyes. 

@davidfowl, as you are the author IIRC.
was the redis on the same vm or another vm on the same local network? 
is there docs/stuff I can read about it? what is the required latency also?

i'm trying so hard not to be naive, currently doing research, can strong low latency multi regional consistency been done, to use as a shared state for SignalR in multiple regions?
can CosmosDB's strong multi-regional consistency work and be low latency enough to be a shared state? 

it seems I have the same need as @grahamehorner's, and I know it's a big premature optimization, but multi-regional SignalR backplane & state scaling would be a nice problem to start with.

**Comment by davidfowl** [comment]
Anything that has a notification API could be used. It cosmos has one then it could work. As for message deletion, something would have to be designed around that. 

There seems to be a misconception about how we use redis. We don’t store anything in redis. We use it’s pub sub capabilities to implement the backplane. Whenever somebody brings up a backplane based on a database them seem to forget that the only thing required is the ability to communicate with other nodes, not storage.

**Comment by wesamco** [comment]
@davidfowl oh, then why not use Kafka? it's a better tool for the job, certainly more than Redis.
you can use Kafka as a pub/sub Message Bus, it's fast, with single-digit-millisecond latency, **scaleable**, durable, highly available by design.
it's become very popular over the past few years, wildly being used as a message bus between micro-services, I already can find literature on multi-regional scaling for Kafka with 1 search, it seems to be by Yahoo engineers.

**Comment by anurse** [comment]
@wesamco That sounds like a pretty good platform for SignalR scale-out, but I don't expect we'll be writing a provider for it any time soon. We've got a Redis implementation up and running and the extension points for anyone to go in and build scale-out based on other platforms. We've got enough to focus on just shipping our v1 without adding new features 😛 .

**Comment by wesamco** [comment]
@anurse sure, I don't expect you guys to do it, because it's not your job, I just wanted to remind you of Kafka. 😄
you wrote "The scale-out infrastructure in SignalR will be pluggable", that's all I needed to read.

I need to start thinking about how to scale beyond one data center/region and the (network) latency implications, 
SignalR reactive streams and reactive Kafka streams bring up dots in my mind that need to be connected.
