### ISSUE TITLE
Connection ID as a token & date/time in each log line

### ISSUE THREAD

**Issue by muratg** [aspnet/SignalR#553]
- [x] - Client
- [x] - Server
- [x] - Remove date/time from logs
- [x] - Add scope
- [ ] - ~~Add log level to function names for readability e.g. `_logger.DebugInvocationReceived`~~

**Comment by davidfowl** [comment]
@BrennanConroy after playing with the logs in Seq I think we need to change them because they aren't extremely useful right now. For example, I can't even filter on Hub method invocations with the same name:

![image](https://user-images.githubusercontent.com/95136/28156127-3ccb2332-6766-11e7-8e82-aee7c18de01a.png)

We also print out the `Task` return type instead of saying it's void:

![image](https://user-images.githubusercontent.com/95136/28156134-4cf02474-6766-11e7-90ae-a64be84683b6.png)

Lots of small things to change.

**Comment by muratg** [comment]
@BrennanConroy this is in preview1 now.

**Comment by Eilon** [comment]
@muratg / @BrennanConroy - anything to do here for preview1?
