### ISSUE TITLE
Do we need ITransport and IConnection

### ISSUE THREAD

**Issue by davidfowl** [aspnet/SignalR#569]
https://github.com/aspnet/SignalR/blob/d169b96d2d794d52ae4c613df0854e2525314500/client-ts/Microsoft.AspNetCore.SignalR.Client.TS/Transports.ts#L10

https://github.com/aspnet/SignalR/blob/d169b96d2d794d52ae4c613df0854e2525314500/client-ts/Microsoft.AspNetCore.SignalR.Client.TS/IConnection.ts#L4

They're almost identical at this point.

Thoughts @moozzyk ?

**Comment by moozzyk** [comment]
I prefer to keep those even though they look similar because they are different concepts. Transports should be dumb and should be managed by the Connection. It is one way relationship. Connection does not care about how data is being sent/received. I am afraid that merging this interface will make the boundaries blurry.

**Comment by davidfowl** [comment]
That's fine. One motivation was to allow passing a websocket directly to the HubConnection API.
