### ISSUE TITLE
.NET Client Not Receiving

### ISSUE THREAD

**Issue by los93sol** [aspnet/SignalR#648]
I'm not sure what I'm doing wrong, my ts client works as expected, and my .NET client can send messages to the hub without issue, but I cannot seem to figure out how to catch a calls from the hub to the .NET client....

HubConnection = new HubConnection(new HttpConnection(new Uri(Consts.HubURL), TransportType.WebSockets));
HubConnection.On("WriteMessage", (string message) => { Console.WriteLine(message); });
await HubConnection.StartAsync();

**Comment by davidfowl** [comment]
Put a sample on github that reproduces the issue so we can take a look.

**Comment by los93sol** [comment]
Can you show an example of how to use the overload for methodName, Type[], and Func

**Comment by moozzyk** [comment]
Are you asking about this: https://github.com/aspnet/SignalR/blob/dev/src/Microsoft.AspNetCore.SignalR.Client/HubConnectionExtensions.cs#L123 ?

**Comment by los93sol** [comment]
This one:
[https://github.com/aspnet/SignalR/blob/dev/src/Microsoft.AspNetCore.SignalR.Client/HubConnection.cs#L95](https://github.com/aspnet/SignalR/blob/dev/src/Microsoft.AspNetCore.SignalR.Client/HubConnection.cs#L95)

I'm really stumped why the .NET client isn't receiving, I'm thinking I just have some syntax not quite right since I'm not familiar with Action and Func

**Comment by moozzyk** [comment]
If you have less than 9 arguments you will be better off using the generic method
```
HubConnection.On<string>("WriteMessage", message => { Console.WriteLine(message); });
```
The one you pointed to is private so you cannot use it directly - it is just a convenience method for generic `On` method that invokes this: https://github.com/aspnet/SignalR/blob/dev/src/Microsoft.AspNetCore.SignalR.Client/HubConnection.cs#L95
If you really want to use this one you would have to do something like this:
```
HubConnection.On("WriteMessage", new Type[] { typeof(string)},  message => { Console.WriteLine(message[0]);  return Task.CompletedTask; });
```
I doubt however you don't receive messages because you are using extension methods. More likely it is a parameter mismatch, typo in the name of the method, some kind of deadlock (if you use .Wait()). As @davidfowl said - show the code.

**Comment by los93sol** [comment]
Thanks, I'll get some code up as soon as I can, I think it's a context issue since I'm creating the HubConnection in one thread, then storing it in another.  The callback is getting registered in that first thread so thinking the reference simply doesn't exist anymore to call it back

**Comment by mikaelm12** [comment]
Any luck @los93sol ?

**Comment by los93sol** [comment]
@mikaelm12, nope, I couldn't get it working, I went with DI instead since I think it's probably a better approach for what I was doing
