### ISSUE TITLE
Include Header in http requests (C# client)

### ISSUE THREAD

**Issue by malichishti** [aspnet/SignalR#686]
Hi,

I'm using **Microsoft.AspNetCore.SignalR.Client** to connect to Signal r hub from a .Net Core 2.0 Console Application.
I have to include an authorisation header into the requests, i achieve that by extending **HttpClientHandler** and adding the headers in **SendAsync**
`var httpConnection = new HttpConnection(url, new HubHandler());`

```
class HubHandler : HttpClientHandler
    {
        protected override async Task<HttpResponseMessage> SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
        {
            //insert headers here
            request.Headers.Add("xx", "yy");
            return await base.SendAsync(request, cancellationToken);
        }
    }
```

The first **OPTIONS** request gets authenticated fine, however the very next **GET** request does not as it never goes through the **HttpClientHandler.SendAsync** which would have added the headers.

Is there another way to achieve this?
Ali

**Comment by moozzyk** [comment]
I assume that you did not specify the transport when starting the connection and therefore are using the default transport which is WebSocketsTransport. WebSocketTransport does not use the HttpClientHandler to establish a webSocket connection. At the moment HttpConnection does not have any API that would allow setting headers etc. regardless of the transport being used and setting headers for the WebSocketsTransport does not seem possible at all. We will need to fix that.

**Comment by darioairoldi** [comment]
We had the same problem and solved passing the parameters by means of the querystring.

**Comment by moozzyk** [comment]
Related: https://github.com/aspnet/SignalR/issues/769

**Comment by NtFreX** [comment]
@darioairoldi Did you solve it by setting the base url? What do you do when you refresh your access token? The property is not exposed on the connection type.
@moozzyk Maybe somehow exposing the `Url` property of the `HttpConnection` type would be enough.

**Comment by moozzyk** [comment]
> Maybe somehow exposing the Url property of the HttpConnection type would be enough. 
I don't think this going to happen. The `IConnection` interface implemented by `HttpConnection` is not tied to HTTP. We will explore this area more (I linked #1039) to see what we want to do. I guess for now you could use HTTP handler to send access tokens in headers and use queryString for WebSockets (WebSocket is persistent). We may allow setting headers with features similarly to what we do to enable binary vs. text transfer mode.

**Comment by NtFreX** [comment]
@moozzyk But when I use the transport type `WebSockets` the message handler won't get called for the second request. Is the message handler intended to be used for all transport types?

The only workournd is to set the access token in the base url. But then you can't change it anymore.

**Comment by moozzyk** [comment]
You will need to acquire the token before you start the connection. The OPTIONS request [is being removed](https://github.com/aspnet/SignalR/pull/1036) if you select the WebSockets transport so you may not even have the first OPTIONS request. 
As I said above - we still need to explore this area to see how we can improve/fix the experience.

**Comment by NtFreX** [comment]
> if you select the WebSockets transport so you may not even have the first OPTIONS request.

The options request was just an example of how the message handler not be called for all requests.

> As I said above - we still need to explore this area to see how we can improve/fix the experience.

I think the message handler should either be removed or be used for all transport types. And if the query string is the way to pass the token then the query string should be changeable.

> You will need to acquire the token before you start the connection

So when I refresh my token I need to disconnect and reconnect?

-----------

Sorry if I annoy too much or misunderstand something.

**Comment by moozzyk** [comment]
The http handler is used [for all HTTP](https://github.com/aspnet/SignalR/blob/dev/src/Microsoft.AspNetCore.Sockets.Client.Http/HttpConnection.cs#L81) requests sent by the client, including OPTIONS. The handler is not being used to open the webSocket though. This is because the `WebSocketClient` works differently and does not take an HttpClient that it would use to handle HTTP handshake. 
Passing tokens in query string will be required for the JavaScript client as there is no way to set headers when using websockets. In case of the C# client I can imagine using headers because [an API that allows this doing this already exists](https://msdn.microsoft.com/en-us/library/system.net.websockets.clientwebsocketoptions.setrequestheader(v=vs.110).aspx). One of the the ways to improve the experience could be to allow the user to somehow set headers and then propagate headers to both http and websocket clients.
Again, for websockets authentication happens only once so even if the token expires to websocket remains open and you don't have to do anything. For other requests you could handle tokens in your HttpMessageHandler where you can replace the token in the url or set headers.

**Comment by davidfowl** [comment]
I think we can fake this a little so the APIs don’t get forked too much. Let’s try to make a prototype of using the HTTP message handler to allow setting headers and the cookie then applying that to then websocket request on the client web socket.

**Comment by springy76** [comment]
Is there a newer beta/prerelease NuGet package than **1.0.0-alpha2-final** somewhere (ex myget)?

**Comment by anurse** [comment]
The nightly builds for SignalR are part of ASP.NET Core 2.1 nightly builds: https://github.com/aspnet/Home#builds
