### ISSUE TITLE
SignalR .Net Client - Latest Packages

### ISSUE THREAD

**Issue by simonpbond** [aspnet/SignalR#688]
What packages are currently required to use SignalR core (client) in a .NET 4.6.1 application?

When trying to install Microsoft.AspNetCore.SignalR.Client in my 4.6.1 project it seems to require many other packages to be installed separately via Nuget (for example: extensions.logging, aspnetcore.sockets.client.http)

I'm just wondering what the correct package names are on the client side.

On the server side I'm using AspNetCore.All, AspNetCore.SignalR and AspNetCore.SignalR.Http all are version 26462, and it's working great.

**Comment by moozzyk** [comment]
On the client side the bare minimum is `Microsoft.AspNetCore.SignalR.Client,Http` and `Microsoft.AspNetCore.SignalR.Client`. You may need to install `Microsoft.Extensions.Logging` and packages containing concrete logging implementations (e.g. `Microsoft.Extensions.Logging.Console` for console logger) if you are planning to use logging since the client depends only on [Microsoft.Extensions.Logging.Abstractions](https://github.com/aspnet/Logging/tree/dev/src/Microsoft.Extensions.Logging.Abstractions) which provides only interfaces and some basic implementations that do nothing.
