### ISSUE TITLE
Using app.UseSignalR causes a System.MissingMethodException at Startup

### ISSUE THREAD

**Issue by ssougnez** [aspnet/SignalR#690]
Hi,

I'm trying to host a simple hub in my ASP.NET Core 2.0 Application. Here are the relevant part of my code:

```
public static IWebHost BuildWebHost(string[] args) =>
    WebHost.CreateDefaultBuilder(args)
        .UseStartup<Startup>()
        .UseDefaultServiceProvider(options => options.ValidateScopes = false)
        .Build();
```

```
public void ConfigureServices(IServiceCollection services)
{
    services.AddSignalR();
}
```

```
public void Configure(IApplicationBuilder app, IHostingEnvironment env)
{
    app.UseWebSockets();

    app.UseSignalR(options =>
    {
        options.MapHub<ChatHub>("chat");
    });
}
```

```
public class ChatHub : Hub
{
}
```

When I try to run this application, I get the error:

> Method not found: 'System.Collections.Generic.Dictionary`2<System.String,System.Object> Microsoft.Extensions.Configuration.IConfigurationBuilder.get_Properties()'.

With the following stack trace:

>    at Microsoft.Extensions.Configuration.FileConfigurationExtensions.SetFileProvider(IConfigurationBuilder builder, IFileProvider fileProvider)
>    at Microsoft.Extensions.Configuration.FileConfigurationExtensions.SetBasePath(IConfigurationBuilder builder, String basePath)
>    at Microsoft.AspNetCore.Hosting.WebHostBuilder.BuildCommonServices(AggregateException& hostingStartupErrors)
>    at Microsoft.AspNetCore.Hosting.WebHostBuilder.Build()
>    at RobotWar.Program.BuildWebHost(String[] args) in C:\XXX\Program.cs:line 18

The stack trace seems to indicate that it's not directly coming from SignalR but when I remove `app.UseSignalR(...)`, I don't have the issue anymore.

I'm using the version 1.0.0-alpha1-26462.

**Comment by davidfowl** [comment]
They are incompatible, you can wait for ASP.NET Core 2.0 to be released or update to a newer ci build.

**Comment by ssougnez** [comment]
Ow okay, didn't know that. 

I'll see how I can update my version of ASP.NET Core 2.0 with the CI build :-D 

Thanks

**Comment by mclasson** [comment]
@davidfowl When I upgrade to the latest aspnetcore and signalr
 <PackageReference Include="Microsoft.AspNetCore.All" Version="2.1.0-preview1-26462" />
 <PackageReference Include="Microsoft.AspNetCore.SignalR" Version="1.0.0-alpha1-26462" />
I get this error:
Could not load file or assembly 'System.Diagnostics.DiagnosticSource, Version=4.0.2.1, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51'. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)

**Comment by ssougnez** [comment]
Yep, got the exact same issue, I'm trying to figure it out right now xD

The least we can say is that trying to use the latest version of SignalR is not a piece of cake :-D (no pun intended ;-))

**Comment by davidfowl** [comment]
You need to also get the latest version of .NET Core. Update *everything* together.

**Comment by mclasson** [comment]
There is newer one than 2.0.0-preview2-006497? Can't find it.

**Comment by ssougnez** [comment]
Yay, I installed ASP.NET Core 2.1.0 and indeed, it solves the issue. mclasson, you can find the binaries here : https://github.com/dotnet/cli

Just another question, I installed the "signalr-client 0.0.17" npm package and I see that there is a sample in there. Is it still compatible with the current version of SignalR ?

Thanks

**Comment by moozzyk** [comment]
@ssougnez - where did you install it from? It does not seem to be correct. The latest is 0.1.0-alpha1-26553.

**Comment by ssougnez** [comment]
Indeed, sorry, in the meantime, I found the issue. There is actually a "signalr-client" package on the default npm registry, I didn't see that I had to install the one from MyGet. I succedded installing it and so far, it seems to work pretty well.

Thanks

**Comment by zhimaqiao1** [comment]
dude i had the same issue struggled for 4 days mixing and matching packages but then Marcus Classon came to my rescue and directed me here.  Thanks Marcus.   David Fowler also answered my emails .. he says 

It's because SignalR is building against the latest ASP.NET Core ci builds. The way to make it work would be to update *everything*:
- Get the latest preview VS version
- Get the latest Microsoft.AspNetCore.All package from (https://dotnet.myget.org/F/aspnetcore-release/api/v3/index.json)
- Get the latest SignalR packages from the same feed.
- Get the javascript client from the same NPM channel or just copy it from the source.

The key is to align the build numbers. SignalR is currently 1.0.0-alpha-{buildnumber} and ASP.NET Core is 2.0.0-rtm-{buildnumber}.


Another option would be to wait on the 2.0.0 release.


But now im having another problem.
getting it to run in a docker container.. I could have sworn i got it to run the first time but now its not going... heres my issue inside the docker container...



-------------------------------------------------------------------
You may only use the Microsoft .NET Core Debugger (vsdbg) with
Visual Studio Code, Visual Studio or Visual Studio for Mac software
to help you develop and test your applications.
-------------------------------------------------------------------
realpath(): Invalid argument
realpath(): Invalid argument
realpath(): Invalid argument
It was not possible to find any compatible framework version
The specified framework 'Microsoft.NETCore.App', version '2.0.0' was not found.
- Check application dependencies and target a framework version installed at:
/
- Alternatively, install the framework version '2.0.0'.
The target process exited without raising a CoreCLR started event. Ensure that the target process is configured to use .NET Core. This may be expected if the target process did not run on .NET Core.
The program '[52] dotnet' has exited with code 131 (0x83).
The program '' has exited with code 131 (0x83).

**Comment by zhimaqiao1** [comment]
docker image
microsoft/aspnetcore:2.0

**Comment by muratg** [comment]
Wrong dependencies.

**Comment by brolaugh** [comment]
Had this same issue after the release of .NET Core 2.0. Took me a while to realize that I was running on a pre release version of 2.0 (which I had downloaded a while back). Just downloading and installing the [final release](https://www.microsoft.com/net/core) fixed it for me.
