### ISSUE TITLE
Nuget Package Restore fails

### ISSUE THREAD

**Issue by BaluJr** [aspnet/SignalR#737]
Hi,

when opening the #rel/2.0.0 solution I get several [Nuget Package Restoring issues](https://github.com/aspnet/SignalR/files/1236192/PacketRestoreFailed_71issues.txt). 
After a subsequent build (of course) this amount of errors [even grows](https://github.com/aspnet/SignalR/files/1236191/PacketRestoreFailed_AfterBuild_232Issues.txt).

I use a fresh installation of  Visual Studio 2017 15.3 with all necessary packages and ASP.net Core 2.0.

Do I have to adjust something?

**Comment by moozzyk** [comment]
What are you trying to do? SignalR was not shipped as part of Asp.NET Core 2.0 and the #rel/2.0.0 release has been created only because SignalR is part of the Asp.NET Core build system. If you want to build from sources clone the repo, go to the dev branch and and run build.cmd/build.sh from repo root. It will install the runtime (SignalR requires 2.1.0 runtime at the moment) and all dependencies. If you want to just try packages use this [NuGet.config](https://github.com/aspnet/SignalR/blob/dev/NuGet.config) install a 2.1.0 runtime.

**Comment by BaluJr** [comment]
Ahh thank you very much. 
That the  #rel/2.0.0 release was only created because of sharing the built system with Asp.Net Core solves the confusion. Than it is obvious, that the problems appear because of the lack of Asp.Net Core  2.1.0 packages.

I tried to port an Asp.Net MVC/SignalR project to Asp.Core to run it in Service Fabric. But if I have to move to the early 2.1.0 version, I will deploy my project in a Docker container until we can enjoy Asp.Core 2.1.0 and SignalR in Q4. :)

**Comment by moozzyk** [comment]
@BaluJr - we are planning an alpha release and we want it to work on top of Asp.NET Core 2.0 so you should be able to try it out sooner.
