### ISSUE TITLE
Expose "connectionId" member of HttpConnection (in signalr-client) as public readonly member

### ISSUE THREAD

**Issue by williamBurgeson** [aspnet/SignalR#788]
My implementation (which I am currently migrating from the previous jquery based .net core signalr client) relies on getting the connectionId when the connection is established. 

I saw that there is a connectionId private field in the HttpConnection; I have referenced this in the "hacky" js way: ```let connectionId: string = myHttpCon['connectionId']```

I can see that this class implements the IConnection interface, therefore it would also stand to reason for the interface to contain the member

e.g.

```
IConnection {
  ...
  readonly connectionId: string;
}

HttpConnection implements IConnection {
  ...
  // private connectionId: string;
  // replace all internal instances of this.connectionId with this._connectionId
  private _connectionId: string;
  get connectionId() : {
    return this._connectionId;
  }
}
```

Could you consider making this amendment to the public interface

**Comment by davidfowl** [comment]
@williamBurgeson why do you need the connection id?

**Comment by williamBurgeson** [comment]
Our project is a sports scoreboard built in angular 4, rendered in a web browser. Based on the url (routing, querystring etc) the page registers itself with SignalR, and then using the connection id and other information (lane number, group name etc) makes an API call which stores that information in a small cached in-memory structure.
We then fire events (currently for dev using postman, but in production using an external system) making API calls to another endpoint in our web app, which is able to update the scoreboard using SignalR. In other words this is a push-only SignalR architecture, with calls back home using API calls.
Our "routing" system (i.e. the logic which accepts a number of criteria to determine which clients to send an update to) depends on the connection ids to know which clients to update.
We started off back in February, and up until now we have been using the .net core 1.1 friendly, jquery-based, old version of SignalR (and of particular importance for us, the client). This has worked OK for us, however we are trying to move to the new version and this lack of a connection id member (publicly exposed) would force us to use the workaround I suggested in the opening comment.

**Comment by davidfowl** [comment]
Sounds good.

**Comment by williamBurgeson** [comment]
I haven't used the .net client (or any other client other than the typescript client) however after raising this I did notice there does seem to be a parity (or at least parallel) between the .net and typescript clients. It would stand to reason therefore to do the same thing as what I have suggested with a .net client. However in raising this it doesn't really affect me in one way or the other what you decide to do with the .net client

**Comment by moozzyk** [comment]
@williamBurgeson - given that in SignalR Core there is no reconnects what do you do when a connection dies? When you start it again it will have a different id.

**Comment by williamBurgeson** [comment]
@moozzyk thanks for pointing this out. Would there be any way for the client to know that the connection had died, without polling? In itself, this shouldn't be a problem, as upon finding out that our connection is no longer valid (however that happened), the client would simply make another registration request, and with that connection id register itself with our "routing" system.

**Comment by davidfowl** [comment]
@moozzyk Why would that be a problem? That has to be dealt with in the old SignalR anyways.

**Comment by moozzyk** [comment]
@williamBurgeson - if the connection is closed the Closed event is being raised. I was just thinking that you could create your own client id and pass it when starting the client (e.g. in query string). In this case when the connection is restarted the client id does not change and everyone continues to use the client id. Keeping a mapping between client id and connection id on the server should be relatively simple - you could use OnConnected/OnDisconnected events to do that. 

@davidfowl - from my experience in the old SignalR a lot of people relied on automatic reconnect and oftentimes did not handle the situation when the client actually failed to re-connect.

**Comment by williamBurgeson** [comment]
I'll be honest and I'm struggling to get things working on the server side anyway with the new stuff. The latest build seems to break all sorts of things (including ```app.UseSignalR(routes => { ... });``` ) and trying to invoke the hub methods from the context classes server side (which I was doing previously), however the connection Id bit looked like an easy win so I thought I would log it.
It would be useful to have a sample of how to selectively and programmatically invoke a hub method from the server side in the new format so that only certain clients as we specify would receive a given update message (or data packet etc), however if needs be I can log an issue for that...

**Comment by davidfowl** [comment]
> @davidfowl - from my experience in the old SignalR a lot of people relied on automatic reconnect and oftentimes did not handle the situation when the client actually failed to re-connect.

Then they're sites never worked 😄 . 

@williamBurgeson The one thing you need to be aware of is in a server farm scenario, you need to send to the right server in order to send data to the client via signalr (or you need to get it to the right server).
 
> It would be useful to have a sample of how to selectively and programmatically invoke a hub method from the server side in the new format so that only certain clients as we specify would receive a given update message (or data packet etc), however if needs be I can log an issue for that...

Yea, we're working on samples. It's pretty much the same API as before, but ASP.NET Core is DI enabled so you inject the IHubContext\<THub\> instead of using GlobalHost that thing is dead.

**Comment by williamBurgeson** [comment]
In our scenario it's a closed system, no server farm or access to the outside world.

I got SignalR up and running as one of the very first things we did, and it just works, so I struggle to remember all the ins and outs of it. I should emphasise we have been using .net core 1.1 from day 1.

In terms of connection Ids, I would say that to us it's the equivalent of an identity value in SQL - it's not a natural ID, but it is the canonical ID assigned by the system for that particular display, displaying for example the scores for lane 4 or lane 17 at that particular time. The "external" system which fires updates  to our end point should not need to know the connection id of the particular lane display which is going to be updated - all it should need to know is the lane number and the data it is going to fire to that lane number.

My understanding, based on the very watchable video with @DamianEdwards and @davidfowl was that we're getting closer to the metal with this iteration of the software, so I think a scenario such as ours would be a good example of where we are managing quite a lot of the logic in our own code, and relying on SignalR just for the actual transport.

**Comment by mysiteptyltd** [comment]
I have come across a similar scenario where I was hoping to have access to the connectionID.  I am building an API which consists of two App Services, both of which need to fire SignalR msgs to the browser.  The App Services are stateless so I'm trying to avoid caching connectionId's on the server. Instead I plan to provide the connection id on every POST to the API (which expects a SignalR msg in return).

Are there plans to expose the connection id?  William Burgeson's js hacky workaround does work but a better approach would be nice.

**Comment by davidfowl** [comment]
After some discussion with @moozzyk , we don't think it makes sense to expose the connection id client side. There are some scenarios we will enable in the future where it won't be possible to get it and exposing it will just break then.

> The App Services are stateless so I'm trying to avoid caching connectionId's on the server. 

Once you're using this version of SignalR, you need sticky sessions for your load balancer because connections can no longer span multiple servers. So in a sense, the moment you use SignalR, you're stateful.

**Comment by SaltyDH** [comment]
Sticky sessions at the load balancer seems like a very different problem from Signalr now requiring stateful connection/session management in the application layers. In order to correlate a Signalr connection with an incoming web request (i.e. same 'user session') this will require additional session management complexity to store, invalidate and flush this information.

I realise the use case described by @mysiteptyltd is just one in a myriad of use cases but a single page app using SignalR for near realtime communication with clients seems like it would be one of the more common place usages for this technology (I realise I don't have anything other than my experiences to back this up). With this in mind, having a low cost of entry for correlating SignalR connections and Web requests is definitely something I'm keen to explore. @davidfowl Is there any information you can share so that we can plan for these new changes that you describe above which make ConnectionIds incompatible?

@davidfowl Thanks for the heads up - This may just be my initial reaction as I just got this all working today :sad:

**Comment by williamBurgeson** [comment]
If we're not going to have access to an individual client from the server, what would be the proposition? In our scenario we need to have some way of individually identifying the client, from the server side. Ours isn't a "group based" system. Furthermore, it is much better from our point of view for that "uniqueness" to be generated server side. The connectionId fitted that requirement perfectly and has worked well, even in a live tournament, in the previous .net core 1.1 jquery based version of signalr.

**Comment by davidfowl** [comment]
> Sticky sessions at the load balancer seems like a very different problem from Signalr now requiring stateful connection/session management in the application layers. In order to correlate a Signalr connection with an incoming web request (i.e. same 'user session') this will require additional session management complexity to store, invalidate and flush this information

Don't get me wrong, I'm not saying there's more we can't do to help with "session management" in fact this came up the other day and I'm looking at potential extensibility for users to have sessions that span across connection lifetime. 

Think of the stickyness requirement as trying to turn SignalR into websockets. That's our main target now, it's been 5 years, websockets are everywhere, fallback will not be the norm (assuming https of course 😉 ). Your websocket is connected to a specific server, if you want to send web requests, to the same server where your websocket exist.

>  @davidfowl Is there any information you can share so that we can plan for these new changes that you describe above which make ConnectionIds incompatible?

Support a direct connect via websockets without negotiation. In this scenario, the client connects with directly to the signalr end point and the connection id only ever exists on the server side.

**Comment by davidfowl** [comment]
@williamBurgeson 

> If we're not going to have access to an individual client from the server, what would be the proposition?

Use a group with your own "connection id". I don't see why that wouldn't work.

**Comment by williamBurgeson** [comment]
@davidfowl thanks for the response - I was reading the previous response when you responded directly to my question. The issue would be that the "uniqueness" needs to be from the server side really - even with an SPA the client is essentially stateless when it starts up.
From the previous response you gave it seems like we might be better off managing our connections on the websockets layer directly (both client and server) as it seems we're essentially misusing signalr if we are sending messages to individual clients instead of broadcasting??

I'm assuming that all the web sockets stuff is baked into .net core 2.0 or is that that under your team's auspices too? 

Good to know your thoughts on this. If we do have to rewrite some of our code I guess that's just the price of working with prerelease!

**Comment by SaltyDH** [comment]
@davidfowl Thanks for taking the time to expand on your thoughts. Very much appreciated - I'll pursue the groups approach. Should work for what we need for now. Cheers!

**Comment by davidfowl** [comment]
> From the previous response you gave it seems like we might be better off managing our connections on the websockets layer directly (both client and server) as it seems we're essentially misusing signalr if we are sending messages to individual clients instead of broadcasting??

Let me clarify this now because I've seen it a few times. Implementing using websockets directly yourself won't save you anything, and I have no idea how people end up at that conclusion after understanding what the new version of SignalR (doesn't) give you. You have the exact same problem to solve, with more code 😄 .

> I'm assuming that all the web sockets stuff is baked into .net core 2.0 or is that that under your team's auspices too?

Yes, it's all ASP.NET. It's what SignalR is built on.

**Comment by williamBurgeson** [comment]
@davidfowl would you suggest the following logic in our case (given the connection id isn't going to be available)
1) Make an API call to get a GUID (or whatever unique id)
2) Subscribe to a new group with that "connection id" (better call it something else for clarity)
3) Use that "group" for the duration of the connection

I'm assuming there's no major performance impact with using the slightly higher level of abstraction which signalr offers over bare websockets? Apologies, I have used signalr with this project and understand the general principles, but haven't really dug underneath very much.

Another consideration of course has to be time to market / mature for the technology. I know it's like asking how long is a piece of string but is there an estimated release schedule for this iteration?

**Comment by davidfowl** [comment]
> would you suggest the following logic in our case (given the connection id isn't going to be available)

> Make an API call to get a GUID (or whatever unique id)
> Subscribe to a new group with that "connection id" (better call it something else for clarity)
> Use that "group" for the duration of the connection

Yes.

> I'm assuming there's no major performance impact with using the slightly higher level of abstraction which signalr offers over bare websockets? Apologies, I have used signalr with this project and understand the general principles, but haven't really dug underneath very much.

That's correct. I think the general problem is that people make the assertion that they'll just use websockets with no prior knowledge of what's involved even at the most basic level. By all means if you have to use them do it, but just know you'll have to implement:

- Connection Timeouts 
- Connection management
- Efficient buffering for websocket messages
- You have to do it all in a thread safe manner
Granted, you could just use JSON and have each message have a "type" property.
- You have to implement keep alives so that the when you go offline it's detected in a reasonable time.
- Integration with the ASP.NET Authentication and Authorization stack
- Integration with dependency injection so that you can inject things per websocket message instead of per request
- You have to invent a protocol the moment to want to send more than a single message type. This is what SignalR adds on top of that most basic layer. A programming model for dispatching to methods in both directions.

That's not everything and it's just the bare minimum. That leaves out scaling out across multiple nodes.

> Another consideration of course has to be time to market / mature for the technology. I know it's like asking how long is a piece of string but is there an estimated release schedule for this iteration?

Next year.

**Comment by moozzyk** [comment]
Another option could be to use authentication. If users are authenticated you could use UserId instead of ConnectionId to address a given user. In this case the UserId will be the same even if connection id changes.

**Comment by williamBurgeson** [comment]
For this particular system we don't have any users, or any security for that matter - it's a completely closed system with no access to the outside world (we even use wires instead of wifi) 
I think David Fowler's suggestion of using a "group" for each connection is the way we'll need to go.

**Comment by cbmek** [comment]
Think bout this scenario:
You write public chat with chat rooms (no auth, no usernames). When someone is typing new message you want other users to know that someone (doesn't matter who) is writing a message. 
On client you do simple invoke:

```
myHubConnection.invoke("iAmTypingNow")
```

Then on the hub you broadcast it to all clients in this room (use Groups for that):

```
Clients.Groups("my-room-name").NotifyAboutTyping();
```

...and user who is typing also receives this notification and he shouldn't.

So there are two options:
1. Implement Clients.GroupExcept("group-name", new[] { Context.ConnectionId }); // same as Clients.AllExcept(...)
2. Expose connectionId on client side, so we can ignore our own broadcasts.

I think both should be possible, because there are handful of scenarios in witch one can behave different on own broadcasts.
