### ISSUE TITLE
Hardening the Sockets layer

### ISSUE THREAD

**Issue by KPixel** [aspnet/SignalR#820]
[The WebSockets Protocol has a section on Security Considerations](https://tools.ietf.org/html/rfc6455#section-10), and I think that most of these issues are not currently handled.

For example: A rogue client could connect using raw WebSockets and send endless messages with `EndOfMessage = false`, making the server run out of memory.

So, at the very least, we need to be able to configure:
1. The maximum incoming fragment & message sizes
2. The maximum number of incoming fragments per message
3. The minimum transfer rate for an incoming message (like aspnet/KestrelHttpServer#1939)

Other potential issues:
4. Set WebSocket opening & closing handshake timeouts + ping timeout
5. Option to verify the Origin of clients
6. Ability to turn off the validation of incoming WebSocket text messages for UTF8 conformance (for performance reasons)

Some of these may need to be implemented at a lower level (WebSockets internals)...

I focused on the Sockets layer with the WebSockets transport. But this issue could be extended to the rest of this library.

**Comment by davidfowl** [comment]
Just FYI, the existing sockets layer isn't anywhere near it's final form see https://github.com/aspnet/KestrelHttpServer/issues/1980 for more details.

> The maximum incoming fragment & message sizes
> The maximum number of incoming fragments per message

Does it really need to be that specific? Seems like size is good enough.

> The minimum transfer rate for an incoming message (like aspnet/KestrelHttpServer#1939)

Not sure we need to add anything on top of what kestrel adds here. This should be in a higher layer before the actual websocket layer (IMO).

> 4. Set WebSocket opening & closing handshake timeouts + ping timeout
> 5. Option to verify the Origin of clients

We could expose this at the websocket middleware level.

> For example: A rogue client could connect using raw WebSockets and send endless messages with EndOfMessage = false, making the server run out of memory.

Old SignalR used to have max message size, we need to bring that back for message fragments. We'll need to see how much of this is web socket specific vs not.

> 6. Ability to turn off the validation of incoming WebSocket text messages for UTF8 conformance (for performance reasons)

Why? That's a protocol error which should also be handled by the websocket middleware.

**Comment by KPixel** [comment]
I did expect the current implementation to not be final, I just thought it would be helpful to have a place to keep track of these issues.

Regarding the sizes, each of them is needed to protect against different types of attacks.

UTF8 validation causes text-based WebSocket to be a lot slower than binary-based. So, in case where a team controls the server and client, they may want to turn that off... (But I don't really care about this option because I use binary WebSocket.)

By the way, I copied some of these ideas from the [Crossbar.io WebSocket options](http://crossbar.io/docs/WebSocket-Options/).

**Comment by muratg** [comment]
cc @blowdart

**Comment by davidfowl** [comment]
@stephentoub We might need some of these things for the managed web socket implementation.

**Comment by blowdart** [comment]
No turning off validation just for performance if it's part of the spec please :)

**Comment by anurse** [comment]
> No turning off validation just for performance if it's part of the spec please :)

No worries :). There are no plans to remove UTF-8 Validation of Text frames. We have a Binary format for high-performance stuff like that.

**Comment by anurse** [comment]
It looks like we can do all this from the WebSocket api itself, so we can make the changes in our repo.

**Comment by anurse** [comment]
Merging https://github.com/aspnet/SignalR/issues/426 into this one.

**Comment by davidfowl** [comment]
Summary of what we're doing about this bug:

> The maximum incoming fragment & message sizes and The maximum number of incoming fragments per message

We won't be providing knobs for this. We no longer buffer anything at the sockets layer see (https://github.com/aspnet/SignalR/commit/7a53e07623b83f81ea9ab7ec0ca69f13cf324f4f). We'll treat the websocket like a stream and will flow data as we get it off the wire. The only internal buffering will be that done by the websocket itself which has been improved https://github.com/dotnet/corefx/commit/06aa6f0ce4cdf78985f029f218007a7d55f8965f. 

> The minimum transfer rate for an incoming message (like aspnet/KestrelHttpServer#1939)

Since we won't be buffering at the transport layer we don't see a need to provide anything here, instead we might look into timeout infrastructure (or piggy backing on what Kestrel offers here) for higher level protocols to implement. For example, we'd never time out a websocket message itself since the only thing being buffered is the websocket header itself (which has a max size of 14 bytes). The HubConnectionHandler may need to timeout various parts of its own protocol parsing but that's unrelated to this.

> 4. Set WebSocket opening & closing handshake timeouts + ping timeout

https://github.com/aspnet/Home/issues/3012, there's no ping timeout, or close handshake timeouts. We have our own settings for waiting on the drain https://github.com/aspnet/SignalR/blob/90aa48c09f79fe7c0f3c0e8aeb420816ec15c7f0/src/Microsoft.AspNetCore.Http.Connections/WebSocketOptions.cs#L10.

> 5. Option to verify the Origin of clients

https://github.com/aspnet/Home/issues/2992

> 6. Ability to turn off the validation of incoming WebSocket text messages for UTF8 conformance (for performance reasons)

No. That's spec violation, use binary if you want da perf!

**Comment by davidfowl** [comment]
I'm closing this issue in favor of this one https://github.com/aspnet/SignalR/issues/1799 which has the only remaining work.
