### ISSUE TITLE
SignalR server in UWP

### ISSUE THREAD

**Issue by Bortxx** [aspnet/SignalR#834]
I have a desktop application that acts as a SignalR server using ASPNET core self hosted through Owin. I am currently using project Centenial (desktop bridge) to try to deploy the app to the windows store. As you might know this requires MS techs to approve your app. They've told me that the Microsoft store doesn't allow admin privileges although they do allow full trust apps and told me I can't self host.

Is there a way for SignalR server to run on UWP or is there a version of it made for UWP or is this technology not possible for Windows Store apps.

**Comment by moozzyk** [comment]
UWP sandbox won't allow for this. I don't think you can host a web server in a UWP app.

**Comment by davidfowl** [comment]
This Is a larger ASP.NET thing not a SignalR thing

**Comment by moozzyk** [comment]
When I last talked with the UWP team about running Kestrel in UWP apps they required a tailored version of libuv (which Kestrel is currently built on top of) so that it can run in the sandbox. Unfortunately some of the functions they had to block were ones that Kestrel uses. It might be possible in the future when Kestrel has an alternative to libuv but to my knowledge you won't be able to run Kestrel in UWP at  the moment.

**Comment by Bortxx** [comment]
So then I should give up on a self hosted SignalR server that can be deployed through the Windows store?

**Comment by davidfowl** [comment]
@Bortxx There are a bunch of issues here about it https://github.com/aspnet/Home/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aopen%20uwp. The next version of UWP will support netstandard 2.0 and if sockets works, then it might be possible to make kestrel function with the sockets transport. For now, there's nothing SignalR will do differently since it runs on ASP.NET Core.
