### ISSUE TITLE
Select message formatter

### ISSUE THREAD

**Issue by xperiandri** [aspnet/SignalR#86]
I want be able to pass required format at connect request and then all the messages be formatted with it.
I. e. JSON, BSON, XML, etc.

**Comment by moozzyk** [comment]
There is not built-in support from BSON and XML but you can plug in formatters that know how to handle these formats. 

For the socket level - take a look at the SocialWeather sample. 
For hubs you need to implement the `IInvocationAdapter` interface and register it. Take a look at [JsonNetInvocationAdapter](https://github.com/aspnet/SignalR/blob/dbf27c30c3022ccb9ad902a9a36f358269dd130c/src/Microsoft.AspNetCore.SignalR.Common/JsonNetInvocationAdapter.cs) and [HubEndpoint](https://github.com/aspnet/SignalR/blob/dbf27c30c3022ccb9ad902a9a36f358269dd130c/src/Microsoft.AspNetCore.SignalR/HubEndPoint.cs).

**Comment by xperiandri** [comment]
So the adapter will be selected by specifying `formatType` parameter of metadata?
What is metadata?
Why not to use HTTP Accept header?

**Comment by moozzyk** [comment]
Currently you select the format and formatType by appending this information to the url when you start the the connection (opening a websocket, polling, creating eventSource) and they end up in the [connection metadata](https://github.com/aspnet/SignalR/blob/dev/src/Microsoft.AspNetCore.Sockets/HttpConnectionDispatcher.cs#L57-L58). This turned out to be problematic and is going to be changed.

**Comment by xperiandri** [comment]
That's good. Accept header would be much more standard way.
