### ISSUE TITLE
Bring back progress support

### ISSUE THREAD

**Issue by StephenCleary** [aspnet/SignalR#894]
I'd like to see:

- [ ] Progress message definitions in the protocol, possibly as a special case of streaming.
- [ ] `IProgress` support for .NET server and client.
- [ ] A library that provides progress support for the JavaScript client.

**Comment by davidfowl** [comment]
We have no plans to bring back progress support.  If we do anything in this space, we'll reconsider streaming arguments like we do streaming results.

/cc @anurse

**Comment by anurse** [comment]
To clarify, streaming arguments are different than progress as they would be streaming from Client to Server. We currently support streaming from Server to Client which could be used to build a hub that returns "Progress" messages by returning `IObservable<AppMessage>` (where `AppMessage` is some application-specific message type that supports progress reporting)

The protocol is intentionally designed with some consideration for defining new message types in later versions, so this isn't something that's impossible in the new design. We just wanted to simplify for our v1 rewrite in order to avoid trapping us in the same old design decisions from previous versions. There are a lot of moving parts to getting progress right, as you point out in your issue (client support, etc.). Progress was added as an afterthought in the previous version of SignalR so **if** we want to bring it back we'll want to do it the right way this time and we just don't have the bandwidth to do that in the v1.

**Comment by muratg** [comment]
We aren't planning to do this. Based on customer feedback in the future, we can reconsider this but closing this for the initial release.
