### ISSUE TITLE
New client side API design

### ISSUE THREAD

**Issue by davidfowl** [aspnet/SignalR#900]
I'm proposing a new client side API design to solve a bunch of issues:
- https://github.com/aspnet/SignalR/issues/858
- https://github.com/aspnet/SignalR/issues/842
- https://github.com/aspnet/SignalR/issues/836
- https://github.com/aspnet/SignalR/issues/212
- The fact that subscriptions cannot be removed once added
- Passing state to callback to avoid closers

The big changes are:
- Events registration method calls instead of .NET events. This allows taking a state parameter to avoid closure allocations.
- Event registration methods also return IDisposable to allow removing the underlying subscription.
- The other big benefit of methods for event registration are the ability to add overloads. We can support non async overloads of event handlers which means callers aren't forced to return Task.CompletedTask.
- The Connected event has been removed since StartAsync represents the same thing. If we need to support a model where outside actors need to subscribe to the event we can consider making Start return the same task instead of throwing.
- The closed event is removed in favor of a cancellation token. It means you can poll for closure as well as use a callback. It also allows passing the connection lifetime to other APIs. It also means you can get notified that the connection has closed after it has closed. One downside of this is that you can't run async logic that we wait on.

```C#
public interface IConnection
{
    Task StartAsync(CancellationToken cancellationToken = default);
    Task DisposeAsync(CancellationToken cancellationToken = default);
    Task SendAsync(byte[] data, CancellationToken cancellationToken = default);

    public CancellationToken ClosedToken { get; }

    public IDisposable OnReceived(Func<byte[], object, Task> callback, object state);

    IFeatureCollection Features { get; }
}

public class HubConnection
{
    Task StartAsync(CancellationToken cancellationToken = default);
    Task DisposeAsync(CancellationToken cancellationToken = default);
    Task InvokeAsync(string method, CancellationToken cancellationToken = default, params object[] args);
    Task SendAsync(string method, CancellationToken cancellationToken = default, params object[] args);
    Task<ReadableChannel<object>> StreamAsync(string method, CancellationToken cancellationToken = default, params object[] args);

    public CancellationToken ClosedToken { get; }

    IDisposable On(string methodName, Type[] parameterTypes, Func<object[], object, Task> callback, object state);
}
```

PS: This doesn't take into account the possibility that we might want to change `IConnection` to be pipe based in the near future (this means Send and Receive would go away).

/cc @moozzyk

**Comment by KPixel** [comment]
Looking good.

Maybe `ClosedToken` should be called `DisposedToken` to be consistent with the method that triggers it?
My understanding is that "close" can be a temporary state (ie: the object could be "re-opened"). But "dispose" is final.

Also, is this usage of the `CancellationToken` class is ok? I understand the value of its disposable subscription feature, but it was designed to cancel tasks...
The `IObservable` API would be perfect here, but it does require a lot of plumbing code.

And, I don't understand the signature of the callback parameter in `OnReceived()`. Is it a typo? (The fact that it takes a Task as param and returns an object.)

**Comment by davidfowl** [comment]
> Also, is this usage of the CancellationToken class is ok? I understand the value of its disposable subscription feature, but it was designed to cancel tasks...

Rules were meant to be broken.

> The IObservable API would be perfect here, but it does require a lot of plumbing code.

Perfect where?

> And, I don't understand the signature of the callback parameter in OnReceived(). Is it a typo? (The fact that it takes a Task as param and returns an object.)

It was a typo, fixed now.

**Comment by KPixel** [comment]
Regarding `IObservable`, I mean that it offers a similar disposable subscription feature without the semantic baggage. But, like I said, it does require some plumbing code to get going.

**Comment by KPixel** [comment]
By the way, I would like to tell you how I am using the Sockets library, because it might broaden how this API is perceived, especially the `IConnection` interface:

I am implementing a number of messaging services that are simplified versions of XMPP and [WAMP](https://github.com/Code-Sharp/WampSharp):
- Publish/Subscribe
- Presence
- RPC
- Data "synchronisation" (which is a layer on top)

`IConnection` is the foundation of these services, and they don't distinguish between client & server sides.
To take RPC as the simplest example, it means that the client can "invoke" the server, and the server can "invoke" the client.

By the way, "client" in my case means Xamarin apps. So, all this code is shared and there is no javascript to deal with.

To achieve that, the server has an `IConnection` implementation that basically looks like this:

```C#
internal class ClientConnection : IConnection
{
    [NotNull]
    private readonly ConnectionContext _connection;

    public ClientConnection([NotNull] ConnectionContext connection)
    {
        _connection = connection;
    }

    [NotNull]
    public Task SendAsync(byte[] data, CancellationToken cancellationToken)
    {
        return _connection.Transport.Out.WriteAsync(data, cancellationToken);
    }

    [NotNull]
    public async Task ReceiveAsync()
    {
        while (await _connection.Transport.In.WaitToReadAsync().ConfigureAwait(false))
            if (_connection.Transport.In.TryRead(out var buffer))
                await OnReceived(buffer).ConfigureAwait(false);
    }

    [NotNull]
    private Task OnReceived(byte[] bytes)
    {
        return Received.InvokeSequentially(bytes);
    }
}

internal class ServerEndPoint : EndPoint
{
    public override async Task OnConnectedAsync([NotNull] ConnectionContext connectionContext)
    {
        var client = new ClientConnection(connectionContext);
        await client.ReceiveAsync().ConfigureAwait(false);
    }
}
```

Note: `InvokeSequentially()` is the extension method I mentioned here #836.

There is obviously more code to track the connection, but it isn't relevant here.

What do you think?

**Comment by LarsKemmann** [comment]
@davidfowl `IConnection.OnReceived` and `IConnection.ClosedToken` are probably just another way of representing `IObservable<{something}>`. Similarly with `HubConnection`. And when you look at `StartAsync` and `DisposeAsync` that's really just `IConnectableObservable<{something}>`. Being able to use standard interfaces would open up some beautiful opportunities for composing via Rx without having to write any adapter code.

**Comment by mot256** [comment]
I'm also for the IObservable approach. It is a .NET Standard supported
interface, so makes it not directly dependent on Rx, but makes it really
useful when it comes to using it with Rx. And with that you do not need to
expose a CancellationToken to monitor connection closure (IObservable will
simply call IObserver.OnCompleted() when the connection closes).

In my opinion IObservable/IObserver has by far the best potential then
trying to implement a custom interface, which as Lars said, has to be
wrapped if you want to use it with Rx.

On 21 Sep 2017 16:44, "Lars Kemmann" <notifications@github.com> wrote:

@davidfowl <https://github.com/davidfowl> IConnection.OnReceived and
IConnection.ClosedToken are probably just another way of representing
IObservable<{something}>. Similarly with HubConnection. And when you look
at StartAsync and DisposeAsync that's really just IConnectableObservable<{
something}>. Being able to use standard interfaces would open up some
beautiful opportunities for composing via Rx without having to write any
adapter code.

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/aspnet/SignalR/issues/900#issuecomment-331178856>, or mute
the thread

**Comment by davidfowl** [comment]
@KPixel That's really cool! I've actually done something like this before on a branch though I can't find it. I did some experimentation around various IConnection implementations (like redis) https://github.com/aspnet/SignalR/blob/b91a6ee7ca597fd9b8f82eb47aaec6e88b760ee3/src/Microsoft.AspNetCore.SignalR.Redis/RedisConnection.cs but nothing has come of it yet. I think there's something to be said about merging the 2 abstractions once we move to pipelines.

> Regarding IObservable, I mean that it offers a similar disposable subscription feature without the semantic baggage. But, like I said, it does require some plumbing code to get going.

I'm not convinced that `IConnection` should be fundamentally observable, also `IO<T>` isn't really useful without RX and we're not taking a dependency on RX.

**Comment by KPixel** [comment]
My point about `IObservable` was that it is an extreme way to expose the disposable subscription feature. And it can inspire a simpler middle-ground solution (that doesn't makes weird use of `CancellationToken`) :)

I was also emphasizing the importance of `IConnection` (since it is an interface that will appear "everywhere") so, it is worth the extra effort.

**Comment by davidfowl** [comment]
> My point about IObservable was that it is an extreme way to expose the disposable subscription feature. And it can inspire a simpler middle-ground solution (that doesn't makes weird use of CancellationToken) :)

I'm aware and disagree 😄 . IConnection won't be `IObservable<T>`, as for having a method to convert? Maybe. This interface will end up turning into a Streaming interface at some point soon so it won't be as straight forward to map things.

**Comment by KPixel** [comment]
I'm saying that I do**n't** want `IConnection` to be `IObservable<T>` :P

**Comment by davidfowl** [comment]
Good. Me neither 😄

**Comment by KPixel** [comment]
Then, you agree :)

**Comment by LarsKemmann** [comment]
Huh. @davidfowl @KPixel I disagree -- but am okay with that. :) `I[Connectable]Observable<T>` is still valuable without Rx because it represents a universally understandable contract (fewer concepts to learn = better). I'm curious as to how a "Streaming" interface is different from an "Observable" interface. Care to explain?

**Comment by KPixel** [comment]
@LarsKemmann Making such a low-level API dependent on Rx is a very big deal. Too big to be justified by this scenario.
Also, the fact that `IConnectableObservable.Connect()` is not async makes it a non-starter.

**Comment by LarsKemmann** [comment]
@KPixel `IObservable<T>` is in the BCL for that reason. I never meant that Rx should be a dependency. :)

**Comment by KPixel** [comment]
Looks like this is not the first time that `CancellationToken` is being used like that.
It is already the case with [IApplicationLifetime](https://github.com/aspnet/Hosting/blob/dev/src/Microsoft.AspNetCore.Hosting.Abstractions/IApplicationLifetime.cs) ([its implementation](https://github.com/aspnet/Hosting/blob/dev/src/Microsoft.AspNetCore.Hosting/Internal/ApplicationLifetime.cs)), and it was even discussed here: dotnet/corefx#2704

I still find that weird, but oh well...

**Comment by davidfowl** [comment]
@KPixel are you basing all of your protocol parsers on the `IConnection` interface?

**Comment by KPixel** [comment]
@davidfowl I have a Message-based layer on top of `IConnection` that is similar to `HubConnection`, but I only support one binary parser.

**Comment by mikaelm12** [comment]
@davidfowl  What about the exceptions in the closed callback. We can't do this with the closed token.
