### ISSUE TITLE
MsgPack: add a way for configuring SerializationContext

### ISSUE THREAD

**Issue by AndriySvyryd** [aspnet/SignalR#904]
This would allow to add serializers for types that aren't supported by default and serializing to a more compact format.

**Comment by davidfowl** [comment]
That's required for both server and client right?

**Comment by AndriySvyryd** [comment]
Client would be nice, but just server could be useful for the TS client.

**Comment by moozzyk** [comment]
I have not investigated it yet but it also may be useful if you want camelCase property names.

**Comment by davidfowl** [comment]
@moozzyk Do we need to separate the payload context from the outer framing context like we do with JSON.NET?

**Comment by moozzyk** [comment]
No - we write the message directly without using the context. We only use the context to write user values. We will have to set some settings on the context and if the user changes them they might shoot themselves in the foot (e.g. they change the serialization to use arrays for objects instead of maps and they won't be able to deserialize in JavaScript).

**Comment by davidfowl** [comment]
So the context is only ever for user values. We should treat it like we do JSON.NET settings.

**Comment by moozzyk** [comment]
+1 to both

**Comment by davidfowl** [comment]
Moved it into alpha2

**Comment by moozzyk** [comment]
Fixed in ba25dee1417b882a1c0993118a4fe6cfaa98c3fc
