### ISSUE TITLE
Changelog

### ISSUE THREAD

**Issue by zigzag95** [aspnet/SignalR#950]
Could you pleas add a Changelog file with Breaking Changes chapter.
Kr,

**Comment by moozzyk** [comment]
If you are asking about alpha2 release you can see bugs we fixed in the [milestone](https://github.com/aspnet/SignalR/milestone/8).
We will post information about breaking changes in the [Announcements](https://github.com/aspnet/Announcements) repo once we ship the first final version of SignalR. Currently we are working on prelease versions and things are going to be changed without a notice. We will call out bigger breaking changes (like API changes in alpha2) in the alpha2 announcement.
